### ISSUE TITLE
check_swap does not accept threshold of zero

### ISSUE THREAD

**Issue by cgd8d** [nagios-plugins/nagios-plugins#100]
Currently check_swap uses 0 as the default values for warn_percent, crit_percent, warn_size_bytes, and crit_size_bytes.  Then when a user tries to monitor swap without issuing notifications, eg:
check_swap –w 0 –c 0
the arguments are rejected as invalid.

It should be possible to set any nonnegative values for each of these parameters so that the user can choose to always return a status of OK.  Alternatively, it should be possible to omit all threshold arguments, which should be interpreted as the choice to set thresholds at zero.

**Comment by jfrickson** [comment]
Fixed in 'maint' branch via commit https://github.com/nagios-plugins/nagios-plugins/commit/75d35ad9f3664fce99a3c87632d7f64c79151ab3
