### ISSUE TITLE
check_swap uses inconsistent checks on negative thresholds

### ISSUE THREAD

**Issue by cgd8d** [nagios-plugins/nagios-plugins#101]
Currently the following is rejected:
check_swap –w -1 –c -1
but not:
check_swap –w -1:0% -c -1:0%
or
check_swap -w -1% -c -1%
There should be a choice of whether negative byte_free and percent_free thresholds are permitted, and that requirement should be uniformly enforced.

[Note that this bug should probably be treated as dependent on #100 because, currently, using negative thresholds is the only way to use an effective threshold of zero.]

**Comment by jfrickson** [comment]
Fixed in 'maint' branch via commit https://github.com/nagios-plugins/nagios-plugins/commit/75d35ad9f3664fce99a3c87632d7f64c79151ab3
