### ISSUE TITLE
Error performance data with check_snmp

### ISSUE THREAD

**Issue by trentasis** [nagios-plugins/nagios-plugins#102]
We have detected a problem with performance data with check_snmp, in performance data c characher is printed and this generates that pnp4nagios can make graphs with this data

4 examples:
[root@server libexec]# ./check_snmp -V
check_snmp v2.0.3 (nagios-plugins 2.0.3)
[root@server libexec]#  ./check_snmp -H 194.0.0.251 -C public -P 2c -o STONESOFT-FIREWALL-MIB::fwMemBytesUsed.0
SNMP OK - 1874554880 bytes | STONESOFT-FIREWALL-MIB::fwMemBytesUsed.0=1874554880c

[root@plugins]# ./check_snmp -V
check_snmp v2.1.1 (nagios-plugins 2.1.1)
[root@server plugins]# ./check_snmp -H 194.0.0.251 -C public -P 2c -o STONESOFT-FIREWALL-MIB::fwMemBytesUsed.0
SNMP OK - 1877135360 bytes | STONESOFT-FIREWALL-MIB::fwMemBytesUsed.0=1877135360c

[root@server plugins]# ./check_snmp -H 172.22.150.210 -C public -P 2c -o 1.3.6.1.2.1.2.2.1.14.20
SNMP OK - 2008790 | iso.3.6.1.2.1.2.2.1.14.20=2008790c

[root@server plugins]# ./check_snmp -H 172.22.150.210 -C public -P 1 -o 1.3.6.1.2.1.2.2.1.14.20
SNMP OK - 2008790 | iso.3.6.1.2.1.2.2.1.14.20=2008790c

tried with nagios plugins 2.0.3 and with 2.1.1

**Comment by scottwilkerson** [comment]
The c is the UOM and is supposed to be there.  My guess would be that you have a pnp4nagios template that is not accounting for the UOM.

https://nagios-plugins.org/doc/guidelines.html#AEN200

**Comment by trentasis** [comment]
Sorry, but I'dont understand, what is UOM?

2015-09-10 21:00 GMT+02:00 Scott Wilkerson <notifications@github.com>:

**Comment by tmcnag** [comment]
This is explained on the page that @scottwilkerson linked to:

>UOM (unit of measurement) is one of:
>
>    no unit specified - assume a number (int or float) of things (eg, users, processes, load averages)
>
>    s - seconds (also us, ms)
>
>    % - percentage
>
>    B - bytes (also KB, MB, TB)
>
>    c - a continous counter (such as bytes transmitted on an interface)

**Comment by trentasis** [comment]
OK, tahnks.

we are monitoring ram or disk and seems that is defined as counter but we need no units or other units kb or bytes, because this objects are not counters, and not sure, but this could be my problem whay graph is not generated correctly, contains data lost and anormal graphs

Thanks

**Comment by trentasis** [comment]
Hi, I think that is a problem of snmp, mib is incorrect is defined as counter64 and must be integer, not?

**Comment by scottwilkerson** [comment]
That sounds correct, and hence why check_snmp is using c as the Unit Of Measure

**Comment by trentasis** [comment]
Our vendor has described that is defines as countergauge64 and details that is a problem of net-snmp or plugin?
