### ISSUE TITLE
check_http problem with chunked encoding in v2.1.1

### ISSUE THREAD

**Issue by ludmilmm** [nagios-plugins/nagios-plugins#103]
Reported by frank_brandt on the Nagios Plugin Development Support Forum here:
https://support.nagios.com/forum/viewtopic.php?t=34548#151502

Hi,

I can see in release notes of v2.1.0 there were some changes in check_http regarding chunked encoding but text is broken with v2.1.1. The server is running WebSphere Application Server with a simple servlet that checks availability of an application and returns a few lines (no HTML). I had to obfuscate some information so the 0084 length info from v2.0.3 does not fit with the real length anymore but you can see that status and duration strings in the content is broken with v2.1.1

Best Regards,
Frank

/usr/share/nagios-plugins-2.0.3/libexec/check_http -H xxx -p 8443 -u /xxx-alivecheck/xxxam -R "status._OK" -S -J /usr/share/nagios-plugins/libexec/xxx.pem -K /usr/share/nagios-plugins/libexec/xxx.key -v
GET /xxx-alivecheck/xxxam HTTP/1.1
User-Agent: check_http/v2.0.3 (nagios-plugins 2.0.3)
Connection: close
Host: xxx:8443
Accept: */_

https://xxx:8443/xxx-alivecheck/xxxam is 332 characters
STATUS: HTTP/1.1 200 OK
***\* HEADER ****
Connection: close
Date: Sat, 05 Sep 2015 17:55:17 GMT
Transfer-Encoding: chunked
Content-Type: text/plain; charset=ISO-8859-1
X-Powered-By: Servlet/3.0 JSP/2.2
***\* CONTENT ****
0084
status=OK
duration=20 ms
version=3.0.4
time=2015-09-05_19:55:17
hostname=xxx

0000

HTTP OK: HTTP/1.1 200 OK - 332 bytes in 0.144 second response time |time=0.144261s;;;0.000000 size=332B;;;0
# 

/usr/share/nagios-plugins/libexec/check_http -H xxx -p 8443 -u /xxx-alivecheck/xxxam -R "status._OK" -S -J /usr/share/nagios-plugins/libexec/xxx.pem -K /usr/share/nagios-plugins/libexec/xxx.key -v
GET /xxx-alivecheck/xxxam HTTP/1.1
User-Agent: check_http/v2.1.1 (nagios-plugins 2.1.1)
Connection: close
Host: xxx:8443
Accept: */_

https://xxx:8443/xxx-alivecheck/xxxam is 332 characters
STATUS: HTTP/1.1 200 OK
***\* HEADER ****
Connection: close
Date: Sat, 05 Sep 2015 17:54:48 GMT
Transfer-Encoding: chunked
Content-Type: text/plain; charset=ISO-8859-1
X-Powered-By: Servlet/3.0 JSP/2.2

***\* CONTENT ****
stK
duratiduration=24 ms
version=3.0.4
time=2015-09-05_19:54:48
hostname=xxx

HTTP CRITICAL: HTTP/1.1 200 OK - pattern not found - 332 bytes in 0.157 second response time |time=0.156843s;;;0.000000 size=332B;;;0

**Comment by tmcnag** [comment]
Note:  Reported but not verified.

**Comment by AstroProfundis** [comment]
I may have the same issue here.

In our system, we have servers with specified uris (in this case, a `/monitor/ok.htm`) with only a single line of "server is ok!" in it, with no HTML code.

When using check_http to test this page, we normally get this:

check_http -p 80 -I 'xxx.xxx.xxx.xxx' -u '/monitor/ok.htm' -R 'server is ok' -H 'hostname.example.com' -v

    **** HEADER ****
    (Headers are always correct and removed due to security issue)
    **** CONTENT ****

        server is ok!

    HTTP OK: HTTP/1.1 200 OK - 796 bytes in 0.009 second response time |time=0.009191s;;;0.000000 size=796B;;;0

But after every few random retries, we get something like:

    **** CONTENT ****

        er is  is ok!

    HTTP CRITICAL: HTTP/1.1 200 OK - pattern not found - 794 bytes in 0.017 second response time |time=0.016561s;;;0.000000 size=794B;;;0

The content of the page is randomly messed. Looks like some sort of uncleaned buffer.

I have made some very simple debugging and located the problem to line 702 of check_http.c (https://github.com/nagios-plugins/nagios-plugins/blob/release-2.1.1/plugins/check_http.c#L702), in `decode_chunked_page()`:

    // move chunk from raw into dst, only if we can fit within the buffer
    if (*raw_pos && *dst_pos && (raw_pos + chunksize) < raw_end ) {
      strncpy(dst_pos, raw_pos, chunksize);
    }
    else {
      die (STATE_UNKNOWN, _("HTTP UNKNOWN - Failed to parse chunked body, too large for destination\n"));
    }

After this `strncpy()` the content is broken, I'm not sure what happens here yet.

BTW, the monitoring-plugins 2.1.1 doesn't have this problem, as it doesn't have this feature about chunked pages.

**Comment by jfrickson** [comment]
I put a fix in the 'maint' branch for chunked encoding that _**might**_ fix this. Please test it and let me know if it's working.

**Comment by jfrickson** [comment]
No response for over two weeks, and I am unable to reproduce. I'm assuming the fix I mentioned above took care of it.

**Comment by arekm** [comment]
Fix works for me (just tested). Thanks!

**Comment by frank-brandt** [comment]
Hi jfrickson,
the fix is working. Thanks...

**Comment by akomakom** [comment]
Did this fix make it into any release?
I have 2.2.1 and I'm seeing this issue when monitoring an installation of Jira (chunked response):

    curl -L https://jira.OUR.COMPANY  | wc -c
    45531
       
    /usr/lib64/nagios/plugins/check_http -S -w 10 -c 20 -r Projects  -H jira.OUR.COMPANY -p 443 -f sticky -v | wc -c
    11366

(and -r reports "pattern not found"):
HTTP CRITICAL: HTTP/1.1 200 OK - pattern not found - 46188 bytes in 0.361 second response time |time=0.360544s;10.000000;20.000000;0.000000 size=46188B;;;0

(Of course, pattern is there, but not in the first 11k chunk).
