### ISSUE TITLE
check_http segmentation fault (FreeBSD)

### ISSUE THREAD

**Issue by jas01** [nagios-plugins/nagios-plugins#104]
On FreeBSD,I didn't try on Linux, but some people don't think the problem is related to FreeBSD, the new version of check_http go to segmentation fault when you try to check a host who don't have anything running on the port 80 (the host must be reachable). To reproduce just try
check_http -H 127.0.0.1
you get a segmentation fault and core dump.
(without anything listen on port 80 on the computer of course).

Regards

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/33d42b197f1be171cb0e9b5e3494c9b6069b2b32
