### ISSUE TITLE
[check_snmp] Timeticks are not being parsed correctly before performance data

### ISSUE THREAD

**Issue by lgroschen** [nagios-plugins/nagios-plugins#108]
When using certain OIDs with check_snmp the performance data after the '|' (pipe) is not being written because of the "Timeticks(n)" label.  Currently, it will see that the output it is not an integer and it will not be displayed.

Reported here: https://support.nagios.com/forum/viewtopic.php?f=7&t=34920

**Comment by jfrickson** [comment]
Fixed in branch master with commit https://github.com/nagios-plugins/nagios-plugins/commit/1771e44e3f98e0fb004b2db8d916ad8d5bb25fad
