### ISSUE TITLE
check_http doesn't work with url parameter

### ISSUE THREAD

**Issue by geshenyi** [nagios-plugins/nagios-plugins#113]
I am trying to check a webservice with below command.

./check_http -H www.somehost.com --header="Accept:application/json" --content-type="application/json" --method="GET" -v -u /webservice/test?id=1&name=dummy

And the returned message is "Required parameter name is not present"...seems like check_http only pass the first parameter id to the webservice.

**Comment by waja** [comment]
How about './check_http -H www.somehost.com --header="Accept:application/json" --content-type="application/json" --method="GET" -v -u "/webservice/test?id=1&name=dummy"'?

**Comment by jfrickson** [comment]
@geshenyi did the idea from @waja fix your problem?

**Comment by jfrickson** [comment]
As there has been no response from the OP, I'm assuming this has been resolved.
