### ISSUE TITLE
check_http - Regex limiter size too small in some cases

### ISSUE THREAD

**Issue by lgroschen** [nagios-plugins/nagios-plugins#116]
When using '-r ' the regex size is limited by:
MAX_RE_SIZE = 256

Using the plugin to return a long number of strings will return truncated output, but will not throw an error if the MAX_RE_SIZE is exceeded.

**Comment by jfrickson** [comment]
Fixed by commit https://github.com/nagios-plugins/nagios-plugins/commit/327d1b459312393431e1e167e2c6b6347225e40f
in branch https://github.com/nagios-plugins/nagios-plugins/tree/maint
