### ISSUE TITLE
check_http SSL Certificate check returns 12:00:00AM <local timezone>

### ISSUE THREAD

**Issue by rcknag** [nagios-plugins/nagios-plugins#119]
When running .

/check_http -H google.com -f follow -C 1
OK - Certificate '*.google.com' will expire on Tue 19 Jan 2016 12:00:00 AM PST.

date
Tue Nov  3 14:09:16 PST 2015

It is parsing in the local time zone, rather than checking the actual GMT, and causing time to be off on expiration.

**Comment by pirtoo** [comment]
I have a fix for this in https://github.com/nagios-plugins/nagios-plugins/pull/126 which brings the cert tiem in correctly and then displays in local timezone.

**Comment by friesoft** [comment]
Any news on this? Will the fix be merged soon?

We are currently getting results like this:
> Firefox: 2018-03-26
> Chrome: Montag, 26. März 2018 um 01:59:59
> openssl: Mar 25 23:59:59 2018 GMT
> check_http: Mon 26 Mar 2018 12:​59:​00 AM CEST

**Comment by jfrickson** [comment]
Fixed in 'maint' branch via commit https://github.com/nagios-plugins/nagios-plugins/commit/d300f434188e00b78c79a32e446cc52b559850cc, originally from @pirtoo
