### ISSUE TITLE
check_http not returning CONTENT properly.

### ISSUE THREAD

**Issue by rcknag** [nagios-plugins/nagios-plugins#121]
When running -
check_http -v -H ipv6-test.com -u '/json/webdns.php?url=stad.gent'

the check_http result is not rendering properly and returns -
***\* CONTENT ****
{"dns_ok"e,"ue,"dns_servers":["ns4.combell.net","ns3.combell.net"]}

which should be -
{"dns_ok":true,"dns_servers":["ns4.combell.net","ns3.combell.net"]}

This previously worked fine in 2.0.3.

**Comment by waja** [comment]
I think this is something that has changed on the remote server. Even with 1.4.16 I get:

```
$ /usr/lib/nagios/plugins/check_http -v -H ipv6-test.com -u '/json/webdns.php?url=stad.gent'
GET /json/webdns.php?url=stad.gent HTTP/1.1
User-Agent: check_http/v1.4.16 (nagios-plugins 1.4.16)
Connection: close
Host: ipv6-test.com


http://ipv6-test.com:80/json/webdns.php?url=stad.gent is 373 characters
STATUS: HTTP/1.1 200 OK
**** HEADER ****
Date: Sun, 08 Nov 2015 06:46:31 GMT
Server: Apache/2.4.10 (Debian)
Access-Control: allow <http://ipv6-test.com>
Access-Control-Allow-Origin: http://ipv6-test.com
Vary: Accept-Encoding
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8
**** CONTENT ****
43
{"dns_ok":true,"dns_servers":["ns3.combell.net","ns4.combell.net"]}
0


HTTP OK: HTTP/1.1 200 OK - 373 bytes in 0,063 second response time |time=0,062811s;;;0,000000 size=373B;;;0
```

**Comment by willemdh** [comment]
What do you mean with

    something that has changed on the remote server

When we use curl it works fine, but with check_http the output is mangled.

**Comment by waja** [comment]
> @waja What do you mean with

> > something that has changed on the remote server

> When we use curl it works fine, but with check_http the output is mangled?

On the system hosting 'ipv6-test.com'. I did double check that and you can see the same behaviour with 1.4.16.

Anyways ... using ```telnet``` gives you the same messed output. So this is what is the expected output by ```check_http```:

```sh
$ telnet ipv6-test.com 80
Trying 2001:41d0:8:e8ad::1...
Connected to ipv6-test.com.
Escape character is '^]'.
GET /json/webdns.php?url=stad.gent HTTP/1.1
Host: ipv6-test.com

HTTP/1.1 200 OK
Date: Mon, 09 Nov 2015 19:02:08 GMT
Server: Apache/2.4.10 (Debian)
Access-Control: allow <http://ipv6-test.com>
Access-Control-Allow-Origin: http://ipv6-test.com
Vary: Accept-Encoding
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

43
{"dns_ok":true,"dns_servers":["ns4.combell.net","ns3.combell.net"]}
0
```

**Comment by michieldetailleur** [comment]
Hi Waja,

With 1.4.16 you probably get the behavior of the check before the chunking fix.

If you run with check_http -v you will see that chunking markers (43 and 0 in this case) in the body output. Which should not happen since it isn't really part of the content as such.

Why does the check still works? Cause the chunking markers are ignored and on separate lines, i.e. not mixing with the content that is checked for.

With the later check_http that has chunking support (which means it removes the chunking markers properly as every browser/http 1.1 client does) something seems to go wrong and the output is mangled:

{"dns_ok"e,"ue,"dns_servers":["ns4.combell.net","ns3.combell.net"]}
which should be
{"dns_ok":true,"dns_servers":["ns4.combell.net","ns3.combell.net"]}

The markers seem to be removed, but the some other characters in the output are replaced.

**Comment by waja** [comment]
> {"dns_ok"e,"ue,"dns_servers":["ns4.combell.net","ns3.combell.net"]}
> which should be
> {"dns_ok":true,"dns_servers":["ns4.combell.net","ns3.combell.net"]}

Ah .. now I see the issue ... *e,"ue,* vs. *:true,*. Sorry, I missed that.

**Comment by michieldetailleur** [comment]
Ok :) So i understand you can reproduce this then?

**Comment by waja** [comment]
No, I can't cause I'm using monitoring-plugins, which has not implemented chunking support, for various reasons. :-)

**Comment by michieldetailleur** [comment]
Ok, so how do we proceed with fixing this then? :)

**Comment by waja** [comment]
Maybe @koenwtje, who submitted most of the code, can have a look or the ppl from @nagiosllc?

**Comment by AstroProfundis** [comment]
This looks familiar with #103 for me, can anyone confirm it?

**Comment by michieldetailleur** [comment]
Astro: this does indeed look very similar.

**Comment by jfrickson** [comment]
I put a fix in the 'maint' branch for chunked encoding that _**might**_ fix this. Please test it and let me know if it's working.

**Comment by jfrickson** [comment]
No response for over two weeks, and my testing does not produce the error. Closing.
