### ISSUE TITLE
check_smtp returns localtime but certs are in GMT (time is wrong)

### ISSUE THREAD

**Issue by davidgarvey** [nagios-plugins/nagios-plugins#122]
In reference to RFC 5280 which defines X.509 certificate profile the time fields in the certificate MUST be expressed in GMT time. See sections 4.1.2.5, 4.1.2.5.1 and 4.1.2.5.2.
https://www.ietf.org/rfc/rfc5280.txt

I am getting localtime returns when the certificate clearly states GMT. The time returned from this plugin is not accurate. I found that this works but sslutils is used by other checks.

```
[dgarvey@box.in.space plugins]$ diff sslutils.c sslutils.c_old 
219,220c219,220
<         tm_t = timegm(&stamp);
<   strftime(timestamp, 50, "%c", gmtime(&tm_t));
---
>   tm_t = mktime (&stamp);
>   strftime(timestamp, 50, "%c", localtime(&tm_t));
[dgarvey@box.in.space plugins]$ 
```

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/d300f434188e00b78c79a32e446cc52b559850cc on issue https://github.com/nagios-plugins/nagios-plugins/issues/119
