### ISSUE TITLE
check_load hardcodes path to 'uptime'

### ISSUE THREAD

**Issue by zen2** [nagios-plugins/nagios-plugins#124]
Detection then use hardcoded path for system binaries at compilation time is a real problem.
That forces monitoring-plugins to be recompiled/reinstalled each time a binary path change as procps have done with uptime. So it have been detected on gentoo system but since it's a compiled based distribution, monitoring-plugins re-installation will take care of it even if it's an annoying dependence.
But that means re-packaging then update for packages based distributions, that is eve more problematic.

And finally the most important: each time a system binary have a new PATH, we got no result or unknown result from monitoring probes creating unneeded alerts on monitoring systems.
Even worst, that could lead to an acceptable result (result is ok but with problems displayed on stderr) along bad performances data so you lose data without be aware of it.

So system binaries path have to be detected at runtime.

**Comment by jfrickson** [comment]
We're not going to do this. We want plugins to be as fast as possible, and path searches take more time than we would like.

My suggestion, is to do `./configure --with-uptime-command=uptime` (without a path) and let the system find it.
