### ISSUE TITLE
Add state to check_mrtg status output

### ISSUE THREAD

**Issue by tmcnag** [nagios-plugins/nagios-plugins#125]
Currently check_mrtg will properly exit with the correct code, but it does not indicate that code in the status output.  See this thread for more:

https://support.nagios.com/forum/viewtopic.php?f=7&t=35688&p=161991#p161910

The fix should be pretty simple, just add it here:  https://github.com/nagios-plugins/nagios-plugins/blob/1771e44e3f98e0fb004b2db8d916ad8d5bb25fad/plugins/check_mrtg.c#L151

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/f1c1fae8c62152bc5de1b82f270aad86a6c5d588
