### ISSUE TITLE
check_nt uptime returns wrong value (v 2.1.1)

### ISSUE THREAD

**Issue by skeith92** [nagios-plugins/nagios-plugins#127]
The check_nt uptime check will returns a wrong value, seconds are like floating numbers:

./check_nt -H host -p 12489 -s password -v UPTIME -l seconds

results:

System Uptime - 392 day(s)  6 hour(s) 8 minute(s) |uptime=33890897
System Uptime - 392 day(s) 6  hour(s) 8 minute(s) |uptime=33890898
System Uptime - 392 day(s) 6  hour(s) 8 minute(s) |uptime=33890899
System Uptime - 3   day(s) 22 hour(s) 8 minute(s) |uptime=338909

**Comment by jfrickson** [comment]
Is this still happening? I am unable to reproduce the problem, and suspect the result was split into two packets, and the second packet was dropped.

**Comment by jfrickson** [comment]
No response in a month. Closing.
