### ISSUE TITLE
check_http -u is misleading

### ISSUE THREAD

**Issue by PAStheLoD** [nagios-plugins/nagios-plugins#128]
Hello!

-u expects a path, not a full URL. So it should be renamed (deprecated and a new argument introduced, but -p is taken) or enhanced to parse full URLs (which is probably the least promising change, since it could easily conflict with -H and lead to other subtle issues). Or check_http could alert the dear user if the value supplied to -u starts with http.

Thanks for considering this rather academic problem.

**Comment by scottwilkerson** [comment]
I'm going to recommend leaving the -u for URI, but change the help doc, and add an additional flag --uri in addition to the misleading --url

This way we get backwards compatibility, and correct the semantic issue.

**Comment by jfrickson** [comment]
Fixed per @scottwilkerson suggestion in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/732e3f7cdba1d3e6b69d6efd5751d25b89df6b1d
