### ISSUE TITLE
check_snmp sending wrong timeout to snmpget.

### ISSUE THREAD

**Issue by hooolden** [nagios-plugins/nagios-plugins#129]
If you use the check_snmp plugin with the -t flag, it sends the wrong value for -t to /usr/bin/snmpget.  For instance, if you tell it to use a timeout of 30, it sends 7 to snmpget.

Example output: 

[root@core libexec]# ./check_snmp -H x.x.x.x -t 30 -o sysName.0 -vvv

/usr/local/bin/snmpget -Le -t 7 -r 5 -m ALL -v 1 [authpriv] x.x.x.x:161 sysName.0

Notice the -t 30 and -t 7

https://support.nagios.com/forum/viewtopic.php?f=35&t=36087&p=163900#p163900

**Comment by jfrickson** [comment]
This is working as designed. The timeout sent to `snmpget` is the `-t` timeout (defaults to 10 seconds) divided by the number of retries (defaults to 5) plus 1. So using defaults: ` 10 / 5 + 1 = 3 `. Using `-t 30` results in ` 30 / 5 + 1 = 7 `.

The reasoning is `-t` is the _plugin_ timeout, not the _socket_ timeout. Plugin timeout divided by number of retries is the socket timeout.
