### ISSUE TITLE
check_http `--hostname` and `--url` documentation misleading

### ISSUE THREAD

**Issue by dwt** [nagios-plugins/nagios-plugins#137]
Hi there,

we just spent some time figuring this out. The [documentation of check_http](https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_http.c#L1595) tells the user to use the `--hostname` argument when connecting to virtual hosts to set the `Host: ...` header. However, it fails to mention that this is _also_ the host that the check_http plugin uses to look up the ip address to connect to.

Instead it is required to use the [also misleadingly documented](https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_http.c#L1632) `--url` parameter to set the vhost to connect to.

Please change the documentation to be clearer. `--hostname` should document that it actually sets the host to connect to and `--url` should document that it can be used to set the virtual host to connect to.

**Comment by dwt** [comment]
Well, actually the situation is even more complicated, as I just found out that even this is not correct.

It seems that one needs to actually set the `--IP-address` switch to a _hostname_ (!) so that the `--hostname` switch is then actually used to set the 'host' header and make the whole thing work.

Please please please, improve those documentation fields, so there is not so much hunting for the correct usage. :-(

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/dbfc36e4ac15040ecc6ed6e60e8aa2e21e2ad2e1.

I added a line to the `Notes:` section:
`You may also need to give a FQDN or IP address using -I (or --IP-Address).`
