### ISSUE TITLE
check_http ssl doesn't test certificate name (CN) correctness

### ISSUE THREAD

**Issue by arekm** [nagios-plugins/nagios-plugins#138]
Example, we want to check www.google.com certificate but due to config error we specified invalid IP for www.google.com hostname.

Such example by hand:

Note -  23.96.52.53 is address of microsoft.com web server, yet check_http happily says everything is "OK" while it should complain that CN (common name) of certificate doesn't match hostname:

```
$ /usr/lib64/nagios/plugins/check_http -C 14 -H www.google.com -I 23.96.52.53 --sni
OK - Certificate '*.microsoft.com' will expire on Fri Dec  1 02:23:00 2017.
```

**Comment by bgshacklett** [comment]
Agreed. I just ran into this yesterday.

**Comment by friesoft** [comment]
We would also need this. Atm we have to use another check because of this (e.g. https://exchange.nagios.org/directory/Plugins/Network-Protocols/HTTP/check_ssl_cert/details)

**Comment by jfrickson** [comment]
I have code in that _mostly_ works. But suddenly getting WARNING or CRITICAL for stuff that worked before is not good in a bugfix release. So I'm changing this to an Enhancement, and scheduling it for the 2.2.0 release.

**Comment by whereisaaron** [comment]
It is a good feature to be able to check the specified domain matches the certificate common name or SAN. I would like to see this added too, or even the option to verify the chain as well.

I think there should also be the option to disable certificate verification. It is not always wanted behavior. Other test tools like `curl` and `wget` include the option to disable checks, via the `--insecure`, `--no-check-certificate` options respectively.

Please also ensure that the wildcard checking for this feature matches the real world implementation of wildcards, e.g. `foo.bar.example.com` should not match a `*.example.com` CN or SAN nor a `*.*.example.com` CN or SAN, but only a `*.bar.example.com` or `foo.bar.example.com` CN or SAN. According to RFC 2818 it should also match a `f*.bar.example.com` certificate but I wouldn't count on that IRL :-)

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/nagios-plugins/nagios-plugins/commit/8798e4bb0e44541edd0b8e1b4409bcde588f9077

**Comment by noudAndi** [comment]
@jfrickson: Thanks for devloping this feature into the plugin! I was stumbling upon this problem a few days ago.
Do you have an rough ETA for this feature?

**Comment by jfrickson** [comment]
It's now in branch release-2.2.1-rc1, which is due for release April 19.

**Comment by noudAndi** [comment]
Awesome! Thanks!

**Comment by bonki** [comment]
Can we reopen this issue since this got reverted (commit ae6eb85)?

**Comment by noudAndi** [comment]
Hi,
as @bonki mentioned, this enhancement was reverted. Can we reopen this issue pls?

**Comment by jfrickson** [comment]
Back in for release 2.3.0 (currently branch `release-2.3.0-working`)
This will be released in mid-July. Sorry it took so long to get it back in.

**Comment by helmo** [comment]
Not sure where the release-2.3.0-working branch went, it's not in this repo. 

I've created a pull request for this in #359

**Comment by rossigee** [comment]
Any news on when this will make it into a release? Without it all we get is false positives.

**Comment by CPbN** [comment]
> Not sure where the release-2.3.0-working branch went, it's not in this repo.

Unfortunately this project seems rather stalled since about a year...
I hope work will resume 👍 
Perhaps @hedenface, the last committer, could help ?
Many thanks !

**Comment by CPbN** [comment]
Actually it is in `maint` branch.
And already in CentOS 7 package 👍 
`nagios-plugins-http.x86_64 2.2.1-9git5c7eb5b9.el7 @epel `

**Comment by melkamar** [comment]
This still does not seem available in the 2.3.3 release

**Comment by arekm** [comment]
@melkamar It's there

````
nagios-plugins-2.3.3 % grep -r verify-host .
./ChangeLog:	parameter `--verify-host` will check if -H hostname matches the SSL
./ChangeLog:	parameter `--verify-host` will check if -H hostname matches the SSL
./ChangeLog:	Revert "New parameter `--verify-host` will check if -H hostname matches
./ChangeLog:	parameter `--verify-host` will check if -H hostname matches the SSL
./plugins/check_http.c:        {"verify-host", no_argument, 0, VERIFY_HOST},
./plugins/check_http.c:    printf (" %s\n", "--verify-host");
./plugins/check_http.c:    printf ("       [-A string] [-k string] [-S <version>] [--sni] [--verify-host]\n");
./NEWS:	check_http: New parameter `--verify-host` will check if -H hostname matches the SSL certificate
````

**Comment by melkamar** [comment]
🤔  that's odd. I didn't look through the source code but instead downloaded and built the plugins just now and there is no such parameter. 

```
# ./check_http --version
check_http v2.3.3 (nagios-plugins 2.3.3)

# ./check_http --help | grep verify-host
```

Maybe I'm missing some build flags

**Comment by arekm** [comment]
OPENSSL_VERSION_NUMBER >= 0x10002000L needed
