### ISSUE TITLE
check_icmp doesn't work on IPv6

### ISSUE THREAD

**Issue by Freeze** [nagios-plugins/nagios-plugins#143]
gormank left a nice post on the Nagios support forums letting us know there are some issues with IPv6 in check_icmp.  He also left some information regarding check_hp and check_hp_bladechassis, which are not ours, but still could provide some information if need be in the future.  

Here is a link to the post: https://support.nagios.com/forum/viewtopic.php?t=37487&start=9999#bottom

**Comment by jfrickson** [comment]
Looking into this

**Comment by jfrickson** [comment]
There is no code currently for ipv6. We have changed from bug to enhancement and will attempt to get this in the next feature release. -bryan
