### ISSUE TITLE
Exception in Failed to poll counter - No data to return

### ISSUE THREAD

**Issue by toast93** [nagios-plugins/nagios-plugins#147]
Hi,

i am using nagios 0.4.3.131 on Windows Server 2012 R2 (Microsoft SQL-Server)
Since we have install the new servers the nagios log have a lot of entries like this one: 

2016-04-08 04:50:42: error:D:\source\nscp\modules\CheckSystem\check_pdh.cpp:244: Exception in Failed to poll counter: PdhCollectQueryData failed: : 800007d5: No data to return.

We also have Windows Server 2012 R2 without running Microsoft SQL. On this servers we have not any issue. The nsclient.ini is nearly the same as on the SQL-Servers. 

I do not understand why we have these issues on the server. 

Hope anyone can help me! Thanks!

**Comment by box293** [comment]
I would try a newer version of NSClient++ as there have been many fixes since the version you are running.

**Comment by jfrickson** [comment]
No more info in about 4 months, so I'm closing this issue. If it's still a problem, please re-open it. Thank you.
