### ISSUE TITLE
[FR] check_http: Always show full URL in plugin output

### ISSUE THREAD

**Issue by tgriep** [nagios-plugins/nagios-plugins#151]
A customer requested the following.
Add an command line option to the “check_http” to always return the full URL when the status is OK.
When the check is run and the status is  critical, the status output displays the failing URL, I would like to have the full URL displayed in the status output when the check is OK.

**Comment by Hellnino18** [comment]
Hi! I have the same problem. We "need" to know which URL is tested. In OK status, but even in warning status. If /toto doesn't exist, the only thing returned is : 

`HTTP WARNING: HTTP/1.1 404 Not Found - 475 octets en 0,004 secondes de temps de réponse`

Not "/toto 404 Not Found". 

Thx!

**Comment by jfrickson** [comment]
This is a good idea. I'll be doing something about it soon.

**Comment by Madlohe** [comment]
Added this in https://github.com/nagios-plugins/nagios-plugins/commit/998aef3b6b1e159fdd525dee381fac80e2190e67 - closing.
