### ISSUE TITLE
add support for -k to check_disk_smb 

### ISSUE THREAD

**Issue by NikolayMetchev** [nagios-plugins/nagios-plugins#152]
Hello,
check_disk_smb should probably support all options that are available to smbclient. However for me personally I need the -k option (Use kerberos authentication) in order to be able to monitor my smb shares.

Many thanks.

**Comment by jfrickson** [comment]
Added to branch 'maint' vi commit https://github.com/nagios-plugins/nagios-plugins/commit/1ce3b25b047639071e243316d10311ee3c778d17
