### ISSUE TITLE
check_dns needs an option to query via IPv6

### ISSUE THREAD

**Issue by scottchiefbaker** [nagios-plugins/nagios-plugins#154]
Our DNS servers are responding via IPv4 and IPv6 now. I need a way to be able to query DNS via IPv6 in addition to IPv4. I don't see a `-6` option available for `check_dns` and it also doesn't understand IPv6 addresses for `--server`. Is there a way to query DNS via IPv6 I'm missing?

**Comment by jfrickson** [comment]
I ran `./check-dns -H some.hostname.com -s xxxx:xxxx:xxxx:xxxx::xxxx` and it seemed to work just fine.

If you are still having problems, post a comment, show a command line and it's output, and reopen this issue.

**Comment by scottchiefbaker** [comment]
If my dns server is `ns1.domain.com` which has an A and a AAAA record, how do I force my query to go to the ipv6 address? Right now, if the server specified in `-s` has ipv4 A record, it will always query it via ipv4.

I recommend we add a `-6` flag to `check_dns` to force the queries to go out via ipv6.

**Comment by scottchiefbaker** [comment]
Here is my real world example:

`./check_dns -H perturb.org -s ns1.web-ster.com`

I have no way to tell `check_dns` to query this via ipv6. Ideally I'd like to have a nagios check for:

* Is my DNS reachable via ipv4
* Is my DNS reachable via ipv6

You're correct that you can use a ipv6 address for `-s`, but it should **also** be able to work on DNS names with both A and AAAA names. That's why I think we should add a `-6` option to tell `check_dns` what method we prefer to use.

Also, I am unable to re-open this issue. It should be re-opened.

**Comment by jfrickson** [comment]
Sorry it's taking so long to get back to this. It's still on my list, though!

**Comment by 2Belette** [comment]
+1 on this one
I am also lock for the same reason as the host I am testing has dual stack and IPv4 is always tested..

**Comment by jfrickson** [comment]
@scottchiefbaker @2Belette :
Finally getting to this. `check_dns` uses `nslookup` in the background, and the `nslookup` command cannot be forced to connect to the nameserver using IPv6.

However, `check_dig` **can** take `-4` and `-6` parameters. Is there a reason you are unable to use `check_dig` instead of `check_dns`?

**Comment by hedenface** [comment]
As unfortunate as this is, it looks the `check_dig` plugin, even when supplying the `-6` flag is still trying to retrieve the `A` record. Take a look:

```
 $ ./check_dns -H perturb.org -s ns1.web-ster.com
DNS OK: 0.173 seconds response time. perturb.org returns 65.182.224.60|time=0.173009s;;;0.000000
Looking for: 'perturb.org'
CRITICAL - Plugin timed out while executing system call

$ ./check_dig -l perturb.org -H ns1.web-ster.com -6 -v
/usr/bin/dig  -6 -p 53 @ns1.web-ster.com perturb.org A +tries=3 +time=4
```

Not exactly the same problem as the issue you opened, but I'll assign it as a bug and we'll go forward from there. If anyone finds a work around, please post it here. Thanks.

**Comment by 2Belette** [comment]
Hi, any news on this one?
many thanks

**Comment by scottchiefbaker** [comment]
Just wondering where we're at on this issue? 

```
/usr/lib64/nagios/plugins/check_dns -H perturb.org -s 2604:d200::40
```

I need a way to see if that returns a valid IPv6 (AAAA) response. Currently it uses IPv6 to query the DNS server, but it asks for an `A` record instead of `AAAA`. Anything else I can do to help move this along?

**Comment by scottchiefbaker** [comment]
It would be nice if `check_dns` had an option for what **type** of record to query for. For example:

```
/usr/lib64/nagios/plugins/check_dns -H perturb.org -s 2604:d200::40 --type NS
/usr/lib64/nagios/plugins/check_dns -H perturb.org -s 2604:d200::40 --type TXT
/usr/lib64/nagios/plugins/check_dns -H perturb.org -s 2604:d200::40 --type AAAA
```

**Comment by box293** [comment]
I'm going to start looking at this today and see what solution we can come up with.

**Comment by scottchiefbaker** [comment]
The `-q` must be newish? I don't remember seeing that last time I checked. Either way that should be sufficient enough to allow me to check my IPv6 entires. Thanks!

**Comment by box293** [comment]
@kohenkatz thanks for letting us know. Could you please create a new issue in GitHub with some examples so we can get it resolved.

**Comment by kohenkatz** [comment]
@box293 done

**Comment by box293** [comment]
Thank you @kohenkatz

**Comment by rocketraman** [comment]
Thanks for the info re the `-q` parameter. Note the man page does not document this: https://www.monitoring-plugins.org/doc/man/check_dns.html.

**Comment by sawolf** [comment]
@rocketraman, that's documentation for a different project. If you compile this repository from master (or from the latest release) and run `check_dns --help`, the -q parameter is documented.
