### ISSUE TITLE
check_file_age wildcard matching

### ISSUE THREAD

**Issue by Hrachos** [nagios-plugins/nagios-plugins#155]
check_file_age fails to find the file, when there is a wildcard * present in the name. 
````
/usr/bin/sudo /usr/lib/nagios/plugins/check_file_age -w 129600  -c 259200 -f /backup/db/postgresql/localhost/production/lastsnapshots/*.sql.gz
````
I believe this can be fixed using the glob() function, yet I am by far no perl expert, worked for me though.
````
79  # Check that file exists (can be directory or link)
80  unless ( glob($opt_f) ) {

92 $st = File::stat::stat(glob($opt_f));
````

**Comment by svains** [comment]
👍  fine with me

**Comment by jfrickson** [comment]
@Hrachos @svains or anyone else, please check out this version:
https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins-scripts/check_file_age.pl
and let me know if that's what you want to see.

**Comment by svains** [comment]
@jfrickson looks ok, thx

**Comment by jfrickson** [comment]
Great! Closing this issue. Change is in the 'maint' branch, and will be in the next release.
