### ISSUE TITLE
Nagios check_snmp showing negative numbers as positive

### ISSUE THREAD

**Issue by tarn8097** [nagios-plugins/nagios-plugins#156]
/usr/local/nagios/libexec/check_snmp -H 172.19.10.75 -p 161 -C public -o 1.3.6.1.4.1.28946.1.2.8.11.0
SNMP OK - -42 | iso.3.6.1.4.1.28946.1.2.8.11.0=-42

/usr/local/nagios/libexec/check_snmp -H 172.19.10.75 -p 161 -C public -o 1.3.6.1.4.1.28946.1.2.8.11.0 -w -50: -c:-55
Range format incorrect

**Comment by tarn8097** [comment]
Can someone please help me out. new to nagios. and have been trying to figure out sone work around for this.

**Comment by box293** [comment]
I suggest posting this question in the Nagios support forum:
https://support.nagios.com/forum/viewforum.php?f=7

GitHub is best for reporting bugs.

When you post the question there, please provide the version of check_snmp you are using:
```
/usr/local/nagios/libexec/check_snmp -V
```

Also make sure you explain what thresholds you want. For example "-42 is ok, warning at -50 and critical at -55".

**Comment by jfrickson** [comment]
Not a bug
