### ISSUE TITLE
 check_ide_smart: Invalid argument

### ISSUE THREAD

**Issue by danny70437** [nagios-plugins/nagios-plugins#16]
Migrated from https://sourceforge.net/p/nagiosplug/bugs/520/

---

2011-06-29 Creator: Domi Barton

The check_ide_smart plugin fails on some disks w/ the following output:
```
./check_ide_smart -n -d /dev/sda
CRITICAL - SMART_ENABLE: Invalid argument
CRITICAL - SMART_CMD_ENABLE
```
But the disk is SMART capable:
```
./smartctl -i /dev/sda
smartctl version 5.33 [i686-redhat-linux-gnu] Copyright (C) 2002-4 Bruce Allen
Home page is http://smartmontools.sourceforge.net/
Device: MAXTOR ATLAS10K4_36SCA Version: DFV0
Serial number: B2SM1QGM
Device type: disk
Transport protocol: Parallel SCSI (SPI-4)
Local Time is: Wed Jun 29 10:02:31 2011 CEST
Device supports SMART and is Enabled
Temperature Warning Enabled
```

Jan Wagner, 2012-10-18:
There is a bug open Novel: https://bugzilla.novell.com/show_bug.cgi?id=640368
And of course now in debian: http://bugs.debian.org/690760

**Comment by spjmurray** [comment]
Just notified monitoring-plugins of this as well but I've got a check_scsi_smart which will help out people with post 2000 storage :)  https://github.com/spjmurray/check_scsi_smart fell free to test commit changes and I'll make sure they get fanned out to the necessary upstream repos

**Comment by jfrickson** [comment]
Per Nagios Enterprises development meeting, 04/05/2017, we've decided that we are not going to fix check_ide_smart at this time, however, we are going to consider integrating @spjmurray https://github.com/spjmurray/check_scsi_smart as the default SMART check plugin. -bryan

**Comment by arekm** [comment]
Issue exists (got here because was hit by it), other plugin not being integrated but issue closed? Don't undrestand it. Should be open since problem exists.

**Comment by hedenface** [comment]
> We'll have an internal discussion regarding retiring check_ide_smart entirely.

**Comment by box293** [comment]
Perhaps an encompassing disk_health plugin. I've been thinking about one that checks the SSD trim stuff to see if it's going to fail or it's close to reaching it's write rate.

**Comment by arvanus** [comment]
Any news about `disk_health` plugin?
Thanks!
