### ISSUE TITLE
Segfaulting with timeout > 26 sec

### ISSUE THREAD

**Issue by akishkin** [nagios-plugins/nagios-plugins#161]
it's related to nagios-plugins version > 2.0.3
here is an exaple with check_dns, dns server for domain is down, so timeout really works.
problem seems to be related to all plugins, that have -t option

[root@mon plugins]# ./check_dns -t 30 -H down_domain.com -q A
Segmentation Fault
[root@mon plugins]# ./check_dns -t 27 -H down_domain.com -q A
Segmentation Fault
[root@mon plugins]# ./check_dns -t 26 -H down_domain.com -q A
CRITICAL - Plugin timed out while executing system call
[root@mon plugins]# ./check_dns -H down_domain.com -q A
CRITICAL - Plugin timed out while executing system call

**Comment by tmcnag** [comment]
Confirmed on 2.1.1, seems to bail around at the 20-second mark:

```
root@misha: ~/projects/nagios-plugins/nagios-plugins-master/plugins
$ time ./check_dns -t 26 -H down_domain.com -q A
Segmentation fault

real    0m20.005s
user    0m0.003s
sys     0m0.001s
root@misha: ~/projects/nagios-plugins/nagios-plugins-master/plugins
$ time ./check_dns -t 30 -H down_domain.com -q A
Segmentation fault

real    0m20.005s
user    0m0.004s
sys     0m0.000s
root@misha: ~/projects/nagios-plugins/nagios-plugins-master/plugins
$ time ./check_dns -t 10 -H down_domain.com -q A
CRITICAL - Plugin timed out while executing system call

real    0m10.001s
user    0m0.000s
sys     0m0.000s
root@misha: ~/projects/nagios-plugins/nagios-plugins-master/plugins
$ cat /etc/resolv.conf
; generated by /sbin/dhclient-script
search nagios
;nameserver 192.168.XXX.XXX
;nameserver 4.2.2.2
;nameserver 8.8.4.4
;nameserver 8.8.8.8
nameserver 10.1.1.169;not on the network anywhere
root@misha: ~/projects/nagios-plugins/nagios-plugins-master/plugins
$ ./check_dns --version
check_dns v2.1.1.git (nagios-plugins 2.1.1)
```

**Comment by pwo-fg** [comment]
Same behaviour with version : 
check_dns v2.1.2 (nagios-plugins 2.1.2)

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/9c2bce53843002de84e8e5c400ba3b29ef8fd257

`nslookup` has it's own timeout, then it exits with the message:
```
;; connection timed out; no servers could be reached
```
`check_dns` then tries to parse `stdout` looking for a `:` character, which it doesn't find, so `msg` gets set to NULL. Then it tries to print that message and segfaults.
