### ISSUE TITLE
check_disk plugin not working with inode threshold

### ISSUE THREAD

**Issue by sriniprog** [nagios-plugins/nagios-plugins#162]
Hi,

I would like to check the disk value and inode value of the partition using chech_disk plugin.
Whenever i passes the argument with both disk threshold and inode threshold it doesn't work as desired.

Plugin compares the inode threshold with free space instead of used space, with this issue we can't get the plugin to trigger alert on inode free value 10%.

`[root@Nagiosprimary ~]#
[root@Nagiosprimary ~]# /usr/local/nagios/libexec/check_nrpe -H 192.168.98.187 -t 30 -c check_disk -a "-w 20% -c 10% **--iwarning=20% --icritical=1%** -p /"
**DISK OK** - free space: / 29749 MB (31% inode=99%);| /=65924MB;80634;90713;0;100793
You have new mail in /var/spool/mail/root
[root@Nagiosprimary ~]#

[root@Nagiosprimary ~]#
[root@Nagiosprimary ~]# /usr/local/nagios/libexec/check_nrpe -H 192.168.98.187 -t 30 -c check_disk -a "-w 20% -c 10% **--iwarning=20% --icritical=99%** -p /"
**DISK CRITICAL** - free space: / 29749 MB (31% inode=99%);| /=65924MB;80634;90713;0;100793
[root@Nagiosprimary ~]#`

Kindly look into the issue and help us to solve asap.

Regards
Srini

**Comment by jfrickson** [comment]
Sorry this got lost in the weeds. Did you figure out your problem?

**Comment by sriniprog** [comment]
Hi,

No. Its not working. I am currently using check_inode plugin to determine the inode.
Can you change the code in order to make in working fine..?

Or can i have source code to fix it..? I am new to this.. ;)

Regards
Srini

**Comment by chicks-net** [comment]
Howdy srini,

The source is [here](https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_disk.c).

If you're new to this sort of thing you may want to [check out these docs](https://help.github.com/articles/about-pull-requests/).

**Comment by jfrickson** [comment]
Maybe I'm missing something. On my system, I have:

```
$ ./check_disk -V
check_disk v2.2.0.git (nagios-plugins 2.2.0)

$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        40G   29G  9.0G  76% /

$ df -ih
Filesystem     Inodes IUsed IFree IUse% Mounted on
/dev/sda2        2.6M  624K  1.9M   25% /
```
Checking only disk free space:
```
$ ./check_disk -w 80% -c 10% -r /dev/sda2
DISK WARNING - free space: / 9185 MB (24.09% inode=76%)];| /=28942MB;8038;36171;0;40191
```
Checking only inodes free:
```
$ ./check_disk -W 80% -K 10% -r /dev/sda2
DISK WARNING - free space: / 9185 MB (24.09% inode=76%)];| /=28942MB;;;0;40191
```
Checking both (disk ok, inodes warning):
```
$ ./check_disk -w 20% -c 10% -W 80% -K 10% -r /dev/sda2
DISK WARNING - free space: / 9185 MB (24.09% inode=76%)];| /=28942MB;32152;36171;0;40191
```
Checking both (disk warning, inodes ok):
```
$ ./check_disk -w 80% -c 10% -W 20% -K 10% -r /dev/sda2
DISK WARNING - free space: / 9185 MB (24.09% inode=76%)];| /=28942MB;32152;36171;0;40191
```

It seems to be working fine. I also tested with a 2.0.3 version, and that worked fine also.

**Comment by sriniprog** [comment]
Hi..

Thanks for your examples..

In your sample commands, its mentioned that 80% as warning. But i could able to see Warning state returned even though the value is 76%. 

$ ./check_disk -W 80% -K 10% -r /dev/sda2
DISK WARNING - free space: / 9185 MB (24.09% inode=76%)];| /=28942MB;;;0;40191

Please guide me..

Thanks in advance.

Regards
Srini

**Comment by hedenface** [comment]
@sriniprog This is working exactly as described, from the `--help`:

```
 -W, --iwarning=PERCENT%
    Exit with WARNING status if less than PERCENT of inode space is free
```
You're specifying `-W 80%` and the inode is less than that (`76%`).

I'm closing the issue. If you have any further questions, you may re-open or create a new one. Thanks!
