### ISSUE TITLE
check_http not prioritizing outputs

### ISSUE THREAD

**Issue by mcapra** [nagios-plugins/nagios-plugins#166]
Reference: https://support.nagios.com/forum/viewtopic.php?f=7&t=39692

User would like the more pertinent output to come first when checking a certificate. Currently the first line of the output is the SSL protocol used when doing an HTTPS check. User would like the first line to be the more pertinent certificate expiration date, so that when Nagios is displaying the plugins output the user sees the expiration date on the overview screen rather than the SSL protocol being leveraged.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' at https://github.com/nagios-plugins/nagios-plugins/tree/maint via commit https://github.com/nagios-plugins/nagios-plugins/commit/a41c7d1ce8533fe5e895201edd209de59b117991

There was some debugging code left behind. My apologies!
