### ISSUE TITLE
Nagios not showing Certificate expiry warning only SSL Version

### ISSUE THREAD

**Issue by Retro2707** [nagios-plugins/nagios-plugins#168]
Hi,

I updated to the latest nagios plugins and since then all of our checks in nagios just show "SSL Version: TLSv1.2" on the "Status Information" instead of the warning on the 2nd line. Below is an example of the check I run. Can we omit the SSL version line so we can see the warning in Nagios somehow pleaes? Thanks!

```
[root@DALSKMONS01 libexec]# ./check_http -H apps.website.co.uk -C 5,1

SSL Version: TLSv1.2
WARNING - Certificate '*.website.co.uk' expires in 5 day(s) (Wed 17 Aug 2016 01:00:00 PM BST).

```

**Comment by jfrickson** [comment]
Fixed in branch 'maint' at https://github.com/nagios-plugins/nagios-plugins/tree/maint via commit https://github.com/nagios-plugins/nagios-plugins/commit/a41c7d1ce8533fe5e895201edd209de59b117991

There was some debugging code left behind. My apologies!
