### ISSUE TITLE
Option -S produces (left over) debug output

### ISSUE THREAD

**Issue by helgein** [nagios-plugins/nagios-plugins#169]
example:
wheel@debian:~/nagios-plugins-master/plugins$ ./check_http -H myDart.de -S --sni 
SSL Version: TLSv1.2   # <-- that breaks nagios plugin development guidelines
HTTP OK: HTTP/1.1 200 OK - 143955 bytes in 0.500 second response time |time=0.499804s;;;0.000000 size=143955B;;;0

Output comes from plugins/sslutils.c line 160.
That line has a non-matching indentation, thus my believe that this is a leftover debug output.

**Comment by lawre** [comment]
I'm running into this too... thanks for reporting this @helgein .  Has anyone found a workaround for this?  I was going to attempt a wrapper shell script with some '| grep -v' but really, really don't want to have to do this.  Thanks.

**Comment by jfrickson** [comment]
This should be fixed in the current version of plugins (2.1.3). It was only a problem in 2.1.2.
