### ISSUE TITLE
check_http -m min_pg_size not working

### ISSUE THREAD

**Issue by ubellavance** [nagios-plugins/nagios-plugins#173]
check_http v1.4.15.

$ /usr/lib64/nagios/plugins/check_http -m=**100000000** -H www.google.ca
HTTP OK: HTTP/1.1 200 OK - **11661** bytes in 0.292 second response time |time=0.292105s;;;0.000000 size=11661B;;;0

I have tried many numbers to make sure and it always returns OK.

$ /usr/lib64/nagios/plugins/check_http -m=16662 -H www.google.ca
HTTP OK: HTTP/1.1 200 OK - 12982 bytes in 0.308 second response time |time=0.308405s;;;0.000000 size=12982B;;;0

Please note that max_pg_size works though.

$ /usr/lib64/nagios/plugins/check_http -m=11662:111 -H www.google.ca
HTTP **WARNING**: HTTP/1.1 200 OK - page size 11715 too large - 11715 bytes in 0.302 second response time |time=0.302306s;;;0.000000 size=11715B;;;0

**Comment by jfrickson** [comment]
The problem is you're using and equal sign. `-m=10000` is an invalid command-line argument. You need to use `-m 10000` (with a space) or `-m10000` (no space or =).

**Comment by ubellavance** [comment]
Thanks a lot for this precision.  I use the --pagesize syntax with -m.  Sorry.  However, I just tested the max size and it doesn't seem to work:

$ /usr/lib64/nagios/plugins/check_http -m1000:90000 -H www.google.ca
HTTP OK: HTTP/1.1 200 OK - 11423 bytes in 0.295 second response time |time=0.295279s;;;0.000000 size=11423B;1000;0;0

$ /usr/lib64/nagios/plugins/check_http -m10:999999999 -H www.google.ca
HTTP OK: HTTP/1.1 200 OK - 11537 bytes in 0.304 second response time |time=0.304029s;;;0.000000 size=11537B;10;0;0

**Comment by jfrickson** [comment]
I think you have too many zeros on your max size:
```
$ ./check_http -m1000:9000 -H www.google.ca
HTTP WARNING: HTTP/1.1 200 OK - page size 11415 too large - 11415 bytes in 0.117 second response time |time=0.117281s;;;0.000000 size=11415B;1000;0;0
```

**Comment by ubellavance** [comment]
Your are totally right.  I worked so much on the minimum size issue that I used a number that is larger than the page.  Sorry again for the noise.

**Comment by jfrickson** [comment]
No problem. I'm glad it's working! :-)
