### ISSUE TITLE
check_http -S : Invalid option - SSL is not available

### ISSUE THREAD

**Issue by fgentner** [nagios-plugins/nagios-plugins#174]
Installing Nagios 4.2.1, plugins 2.1.2 on Debian 8.5, I got the error "check_http: Invalid option - SSL is not available". 
SOLUTION: The problem comes from a folder mismatch in the configure file. Openssl default bin file location is /usr/bin/openssl and must be added in the file named "CONFIGURE" among the possible openssl dir :

OPENSSL_DIRS="/usr /usr/local /usr/slocal /usr/local/openssl /usr/local/ssl \
              /opt /opt/openssl /usr/bin/openssl"

Then recompile normally.

**Comment by waja** [comment]
maybe you try to use ```--with-openssl```when calling ```configure```?

**Comment by fgentner** [comment]
It didn't change the result, same error. But as explained, the solution is to edit the CONFIGURE file.
Fixed.

**Comment by box293** [comment]
With Nagios Core 4.2.1 and plugins 2.1.3 I don't experience this behaviour on Debian 8.5.

Installed and tested using this guide:
https://support.nagios.com/kb/article.php?id=96
