### ISSUE TITLE
check_file_age does not handle filenames with space

### ISSUE THREAD

**Issue by wellhardh** [nagios-plugins/nagios-plugins#178]
There is a problem in the check_file_age plugin. It does not handle arguments with space correctly. Example:

  localhost:~ admin$ /opt/local/libexec/nagios/check_file_age "/Volumes/Time Machine"
  FILE_AGE CRITICAL: File not found - /Volumes/Time 

  localhost:~ admin$ /opt/local/libexec/nagios/check_file_age --version
  check_file_age v2.1.3 (nagios-plugins 2.1.3)

The same test works in version 1.4.15.

The problem is probably in this line:

  @filelist = glob($opt_f);

It looks like the glob function removes a quoting level and thus split on space.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/d8a41bb07740704ddc3682d6b6b12e09597edb20
