### ISSUE TITLE
check_apt : critical and warning parameters

### ISSUE THREAD

**Issue by JulianVolodia** [nagios-plugins/nagios-plugins#182]
Hi, I need these params:
 -c, --critical = (INT|FLOAT|RANGE|LIST) 
-w, --warning = (INT|FLOAT|RANGE|LIST)
in check_apt (nagios-plugins/blob/master/plugins/check_apt.c)... so I will _do it on my own and contribute_! :)

But always better ask... are you agree to add that features?

---

Btw. If you could clear my thoughts: lines 111:117 should already 'done this' for -c 0 -w 0 values, am I right? :)
...but always says CRIT in my experience...

Take a look at enum {
    STATE_OK,
    STATE_WARNING,
    STATE_CRITICAL,
    STATE_UNKNOWN,
    STATE_DEPENDENT
};

and initial state of result = STATE_UNKNOWN

then when not doing update - result will be still in that state... which is higher than CRIT and WARN :)

So... am I found bug? :)

Best regards and have a nice day! :)

**Comment by nagiosllc** [comment]
HI,

This is an unmanned project currently. Would you like to take it over 
and become the manager of this project/plugin?

Regards,

Mike O'Keefe

Nagios Enterprises, LLC
Email: sales@nagios.com
Phone: 651-204-9102
Fax: 651-204-9103
Web: www.nagios.com

**Comment by JulianVolodia** [comment]
Em... I appreciate. If you want I could.

1. Are there any team who could review changes or it would be "alone programmer game"? : )
2. Is there any other unmanaged plugins?

**Comment by JulianVolodia** [comment]
@jfrickson should I collaborate? I waiting for business guideline from You - Seniors.

And BTW #186 - 'thanks' that I could ask where the that discussion happen actually cause I'm *really* very intrested about it :)

If you want my contribute - say what you want to be done and re-open, please. It's stinks for about 3 months...

Best regards.

**Comment by jfrickson** [comment]
I'm sorry this has been hanging here for so long. If you have a patch, you can do a pull request, or send it to me at jfrickson@nagios.com. Either way, I'll take a look at it as soon as I have a chance.

**Comment by jfrickson** [comment]
No response since Feb 14. Closing.

**Comment by JulianVolodia** [comment]
Read first comment - any feedback? It's a bug "or feature"?

Best...

**Comment by jfrickson** [comment]
STATE_UNKNOWN is numerically higher than CRIT or WARN, but the state severity is not necessarily tied to the numerical value. Unknown is just unknown.

If there is no update, the result will not be STATE_UNKNOWN.
```
$ ./check_apt -U
APT OK: 0 packages available for upgrade (0 critical updates). |available_upgrades=0;;;0 critical_updates=0;;;0
```
returns `STATE_OK`

So that part isn't a bug or feature, you apparently misunderstood ;-)

For the first part:
```
-c, --critical = (INT|FLOAT|RANGE|LIST)
-w, --warning = (INT|FLOAT|RANGE|LIST)
```
Go ahead and put it in. Then do a pull request or send me the diff.

Thanks!

**Comment by JulianVolodia** [comment]
If you update and all is up-to-date --- STATE_OK.
Imagine that you want update only - monitor that state.
Later upgrade manually OK? Did you get it? :)

...and where is maintained code. Being alone programmer sounds unsafe so I think over moving to another system.
