### ISSUE TITLE
ci/travis fails on 'master'

### ISSUE THREAD

**Issue by JulianVolodia** [nagios-plugins/nagios-plugins#185]
...
The command "sed -e 's/cn=admin,dc=nodomain/'$(sudo /usr/sbin/slapcat|grep ^dn:|grep cn=|awk '{print $2}')'/' -i plugins/t/NPTest.cache.travis" failed and exited with 2 during .
...

from my (noop) PR (FF rebase of maint on origin/master === lastest_release (2.1.3))

**Comment by jfrickson** [comment]
Removed the `.travis.yml` file for now, via commit https://github.com/nagios-plugins/nagios-plugins/commit/7622d99178a24833ac5a3eec5d9ac52e44c1e5c3
