### ISSUE TITLE
Should it be maintained? ;)

### ISSUE THREAD

**Issue by JulianVolodia** [nagios-plugins/nagios-plugins#186]
Why don't we focus on new https://github.com/monitoring-plugins/monitoring-plugins and leave this project? ;)

Maybe we should move there? Could somebody spill some infos? ;) even in private @mail to me? :)

Related to talk from #182 and new issues #185 #183.

BTW I use Debian and Arch. ( :P )

**Comment by sni** [comment]
+1

**Comment by box293** [comment]
Please do not create unnecessary issues here.

We wish you all the best with your fork.

**Comment by waja** [comment]
@box293 just for you information, @JulianVolodia is not related with any 'fork' of plugins for monitoring (at least not with [monitoring-plugins](/monitoring-plugins/monitoring-plugins), yet).
And I think you don't want to start a new discussion about which project forked from which project.

**Comment by tmcnag** [comment]
@waja Thank you for the clarification.  We're discussing things on our end, but for now I will be closing this issue.
