### ISSUE TITLE
check_snmp v 1.4.16 drops units when -w -c used

### ISSUE THREAD

**Issue by bmccarthy777** [nagios-plugins/nagios-plugins#187]
Using it without the -w warning or -c critical issues, it returns data as expected:
```
# ./check_snmp -H 192.168.0.214 -P 2c -c public -m /usr/share/snmp/mibs/MyMIB.txt -o DIFFPRES -l DIFFPRES
SNMP OK - DIFFPRES  10.56 psi  | DIFFPRES= 10.56
```
Notice the "psi" unit in the output above.

If I add the -w and - c I get:
```
# ./check_snmp -H 192.168.0.214 -P 2c -c public -m /usr/share/snmp/mibs/MyMIB.txt -o DIFFPRES -l DIFFPRES -w 18 -c 20
SNMP OK - DIFFPRES 10.69 | DIFFPRES=10.69
```
Notice there is no "psi" this time.

More on the issue and verification by Nagios Support Forum moderator are here:
https://support.nagios.com/forum/viewtopic.php?f=7&t=40140

**Comment by jfrickson** [comment]
I believe this is related to issue https://github.com/nagios-plugins/nagios-plugins/issues/180, so this should be fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/655f55c486df31a7591de39bff67238dc3a4147e
