### ISSUE TITLE
check_http -P URL encoded http POST data not working for line break

### ISSUE THREAD

**Issue by 1tft** [nagios-plugins/nagios-plugins#191]
Hello,

I'm trying to POST a file with check_http but it is not working, because I can't encode the line break correctly. Regarding check_http documentation POST (-P) should be URL encoded but that does not seem to work. I tried encodings like "%0D%0A", "<br />", "\\r\\n", "\\n"

At the verbose output of http_check I see my request. Everything is OK except of the line break.
I tried the follwoing requests:

`check_http -H my.server  --url "/cgi-bin/upload.py" -T "multipart/form-data; boundary=---------------------------152933284714739719141417795842" -P  "-----------------------------152933284714739719141417795842%0D%0AContent-Disposition: form-data; name=\"file\"; filename=\"mytext.txt\"%0D%0AContent-Type: text/plain\\ncontent of text file%0D%0A-----------------------------152933284714739719141417795842--" -v`

`check_http -H my.server  --url "/cgi-bin/upload.py" -T "multipart/form-data; boundary=---------------------------152933284714739719141417795842" -P  "-----------------------------152933284714739719141417795842%0AContent-Disposition: form-data; name=\"file\"; filename=\"mytext.txt\"%0AContent-Type: text/plain\\ncontent of text file%0A-----------------------------152933284714739719141417795842--" -v`

`check_http -H my.server  --url "/cgi-bin/upload.py" -T "multipart/form-data; boundary=---------------------------152933284714739719141417795842" -P  "-----------------------------152933284714739719141417795842  <br />Content-Disposition: form-data; name=\"file\"; filename=\"mytext.txt\"<br />Content-Type: text/plain<br /><br />content of text file<br />-----------------------------152933284714739719141417795842--" -v`

`check_http -H my.server  --url "/cgi-bin/upload.py" -T "multipart/form-data; boundary=---------------------------152933284714739719141417795842" -P  "-----------------------------152933284714739719141417795842\\r\\nContent-Disposition: form-data; name=\"file\"; filename=\"mytext.txt\"\\r\\nContent-Type: text/plain\\r\\n\\r\\ncontent of text file\\r\\n-----------------------------152933284714739719141417795842--" -v`

`check_http -H my.server  --url "/cgi-bin/upload.py" -T "multipart/form-data; boundary=---------------------------152933284714739719141417795842" -P  "-----------------------------152933284714739719141417795842\\nContent-Disposition: form-data; name=\"file\"; filename=\"mytext.txt\"\\nContent-Type: text/plain\\ncontent of text file\\n-----------------------------152933284714739719141417795842--" -v`

I always get "HTTP 500" from server.

**Comment by 1tft** [comment]
Consol fellow found a solution:

check_http -H my.server --url "/cgi-bin/upload.py" -T "multipart/form-data; boundary=---------------------------152933284714739719141417795842" -P $'-----------------------------152933284714739719141417795842\nContent-Disposition: form-data; name=\"file\"; filename=\"mytext.txt\"\nContent-Type: text/plain\n\ncontent of text file\n-----------------------------152933284714739719141417795842--' -v

**Comment by jfrickson** [comment]
Reporter found a solution. Closing.
