### ISSUE TITLE
check_smtp: add -L flag to support LMTP (LHLO instead of HELO/EHLO)

### ISSUE THREAD

**Issue by geert-hendrickx-be** [nagios-plugins/nagios-plugins#192]
See [check_smtp.c.diff](https://github.com/nagios-plugins/nagios-plugins/files/597236/check_smtp.diff.txt) for a simple extension of check_smtp to support lmtp as well.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/aa869a35c87e97ce9005ba3c1739c5c60a6f3d4c.

Thanks for the patch!
