### ISSUE TITLE
check_http core dumps if remote server responds with a wrong location

### ISSUE THREAD

**Issue by samm-git** [nagios-plugins/nagios-plugins#193]
Hi, i am found that check_http crashed on one of my hosts 
```
./plugins/check_http 192.168.59.28
Segmentation fault (core dumped)
```
I compiled latest trunk from the git, but issue is still here. Below there is more information:
```
[samm@bunny ~/src/nagios-plugins]$ ./plugins/check_http 192.168.59.28 -v
GET / HTTP/1.0
User-Agent: check_http/v (nagios-plugins 2.1.4)
Connection: close
Accept: */*


http://192.168.59.28:80/ is 203 characters
STATUS: HTTP/1.0 302 Found
Segmentation fault (core dumped)
```
GDB output:
```
(gdb) run  192.168.59.28
Starting program: /usr/home/samm/src/nagios-plugins/plugins/check_http 192.168.59.28
[New LWP 101953]
[New Thread 801c06400 (LWP 101953/check_http)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 801c06400 (LWP 101953/check_http)]
0x0000000000405abb in check_http () at check_http.c:1205
1205	  while (page[0] != '\r' || page[1] != '\n') {
Current language:  auto; currently minimal
(gdb) bt
#0  0x0000000000405abb in check_http () at check_http.c:1205
#1  0x000000000040398c in main (argc=2, argv=0x7fffffffeb00) at check_http.c:180
```

If i am adding -H - everything works as it should. I think that crash is happens because of the redirect to the same host, but not sure. Please let me know if i can provide any other info.

**Comment by samm-git** [comment]
Ok, i think that i found a problem. When "host" header is not set remote side returns wrong location: 
```
        0x0030:  00ac 0350 22e7 1670 4854 5450 2f31 2e30  ...P"..pHTTP/1.0
        0x0040:  2033 3032 2046 6f75 6e64 0d0a 4c6f 6361  .302.Found..Loca
        0x0050:  7469 6f6e 3a20 6874 7470 733a 2f2f 00d5  tion:.https://..
        0x0060:  2028 004f 90d0 0000 0010 0000 0049 0000  .(.O.........I..
```
This causing problem on the check_http side. So main reason here is server, but core dump is still very wrong behavior.

**Comment by samm-git** [comment]
This is response from the server which causing crash:
```
GET / HTTP/1.0
User-Agent: check_http/v (nagios-plugins 2.1.4)
Connection: close
Accept: */*

HTTP/1.0 302 Found
Location: https://� (M~�P���GET / HTTP/1.0�h.jsI�`}� FouQhttps/
Content-Length: 0
Connection: close
Date: Fri, 18 Nov 2016 22:28:34 GMT
Server: lighttpd/1.4.39
```

**Comment by jfrickson** [comment]
It looks to me like it might be a bug in lighttpd. Any chance you can set up a test box and run check_http against lighttpd and Apache?

**Comment by samm-git** [comment]
@jfrickson Hi, problem is actually in the proprietary firmware and already reported to the upstream. However this report not about problem on server side, but about insufficient error check of the location header in the check_http plugin. As far as i could see - page[0]  here is not valid and attempt to access it causing crash.

**Comment by jfrickson** [comment]
Can you try it using plugins v2.1.4 released Nov 17? There's a fix in there that might take care of this problem.

**Comment by jfrickson** [comment]
Or better yet, grab the 'maint' branch.

**Comment by samm-git** [comment]
@jfrickson just tested nagios-plugins 2.1.4 - same crash. Will now check maint branch

**Comment by samm-git** [comment]
@jfrickson on maint it is much better:
```
lugins/check_http 192.168.59.28  -v
GET / HTTP/1.0
User-Agent: check_http/v (nagios-plugins 2.1.4)
Connection: close
Accept: */*


http://192.168.59.28:80/ is 282 characters
STATUS: HTTP/1.0 302 Found
CRITICAL - Socket timeout
```
So it shows error but not crashing anymore

**Comment by jfrickson** [comment]
Do you want additional checks on the redirect, or is it fine as it is?

**Comment by samm-git** [comment]
I think on maint branch it is ok - it is not crashing, and returns some error, so should be find for additional troubleshooting.

**Comment by jfrickson** [comment]
Great. I'll close this issue then. Now go home and get some sleep. Or are you on the night shift?
