### ISSUE TITLE
check_disk and thresholds issue

### ISSUE THREAD

**Issue by tatref** [nagios-plugins/nagios-plugins#195]
Hi,

It seems that the exit status does not match the warning/critical thresholds:

Note how the exit code is WARNING, but the perfdata is still lower than the threshold:
```
check_disk -K 5 -E -w 9% -c 5% -p /u01
DISK OK - free space: /u01 3110 MB (10% inode=63%);| /u01=27950MB;29749;31057;0;32692

check_disk -K 5 -E -w 10% -c 5% -p /u01
DISK WARNING - free space: /u01 3110 MB (10% inode=63%);| /u01=27950MB;29422;31057;0;32692
```

I don't think this is a 1024/1000 unit issue, because if I specify `-u bytes`, I encounter the same behaviour.
This is an old issue, I've seen this since version 1.5.

Do others experience the same thing?

**Comment by jfrickson** [comment]
Run `check_disk -vvv -K 5 -E -w 10% -c 5% -p /u01` and see what that prints out.

**Comment by tatref** [comment]
```
# df -BM -P /u01
Filesystem               1048576-blocks   Used Available Capacity Mounted on
/dev/mapper/vg_os-lv_u01         32693M 24525M     6538M      79% /u01
```

```
# check_disk -vvv -K 5 -E -w 21% -c 5% -p /u01
calling stat on /u01
Thresholds(pct) for /u01 warn: 21.000000 crit 5.000000
calling stat on /u01
For /u01, used_pct=79 free_pct=21 used_units=24524 free_units=6536 total_units=32692 used_inodes_pct=37 free_inodes_pct=63 fsp.fsu_blocksize=4096 mult=1048576
Freespace_units result=0
Freespace% result=1
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
DISK WARNING - free space: /u01 6536 MB (21% inode=63%)];| /u01=24524MB;25826;31057;0;32692
```

```
check_disk -vvv -K 5 -E -w 20% -c 5% -p /u01
calling stat on /u01
Thresholds(pct) for /u01 warn: 20.000000 crit 5.000000
calling stat on /u01
For /u01, used_pct=79 free_pct=21 used_units=24524 free_units=6536 total_units=32692 used_inodes_pct=37 free_inodes_pct=63 fsp.fsu_blocksize=4096 mult=1048576
Freespace_units result=0
Freespace% result=0
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
DISK OK - free space: /u01 6536 MB (21% inode=63%);| /u01=24524MB;26153;31057;0;32692
```

**Comment by jfrickson** [comment]
We calculate % used the same way `df` does. If you use a calculator, you would get this:
````
used = 32693 - 6538 = 26155
used % = 26155 * 100 / 32693 = 80.002
free % = 100.0 - 80.002 = 19.998
````
But `df` and `calc_disk` use a kind of strange integer algorithm, so you end up with 79% used and 21% free. I have no idea why `df` does this, but we do it to match `df`.

**Comment by tatref** [comment]
The issue is not with the percentage, but with the exit code (OK/WARNING/CRITICAL) with respect to the actual thresholds:

I'll take the same examples as my previous entry:

    DISK WARNING - free space: /u01 6536 MB (21% inode=63%)];| /u01=24524MB;25826;31057;0;32692
    ^^^^                                                              ^       ^
    warning is trigered                                            value    warn threshold

24524 (value) < 25826 (warn) so this shouldn't be "warning", it should be "OK", this is the issue.

With my second example

    DISK OK - free space: /u01 6536 MB (21% inode=63%);| /u01=24524MB;26153;31057;0;32692

24524 (value) < 26153 (warn) so status is "OK" (no issue here)


You can see that in both cases, the status should be OK.

**Comment by jfrickson** [comment]
You are triggering the warning using the percentage, so the actual value and warning threshold don't come into play.
```
DISK OK - free space: /u01 6536 MB (21% inode=63%);| /u01=24524MB;26153;31057;0;32692
    WARN is set for 20% ------------^^^                   ^^^^^^^^^^^^^ Ignored for determining WARN
```
I'll check and see if we should revert to the "old" percentage calculations, or possibly select the old way via a command-line parameter.

**Comment by tatref** [comment]
Ok so I understand the issue better now.

The discrepancy between used/available space in `df` is due to the reserved blocks in extX filesystems (see `tune2fs -l /dev/some_device | grep -P '(Reserved block count:|Block size:)'`)

So `really available space = total - (used + block_size * reserved_blocks)`

I'm not sure how the check should take this into account though...

**Comment by jfrickson** [comment]
check_disk also takes reserved blocks into account.

After looking at the calculation some more, I've determined that any fractional percent is rounded up (essentially like ceil(x)). So if used space is 79.1% of the total (free space 20.9%), both programs assume used space is 80% and free space is 20%.

So a better solution might be to round the result instead. You would still have values that get the trigger wrong, but it would be a much smaller set.

**Comment by jfrickson** [comment]
I put a fix in the 'maint' branch via commit https://github.com/nagios-plugins/nagios-plugins/commit/4cd52f89ec84a21eea2bb1a3df7c8de2dfcec8e7.
