### ISSUE TITLE
check_uptime inverted threshold return code

### ISSUE THREAD

**Issue by meabandit** [nagios-plugins/nagios-plugins#198]
>$ /usr/local/nagios/libexec/check_uptime -h
>check_uptime v2.0.3 (nagios-plugins 2.0.3)
>Copyright (c) 2014 Nagios Plugin Development Team
>        <Andy Brist>
>
>This plugin checks the system uptime and alerts if less than the threshold.

The plugin actually does the opposite:

https://support.nagios.com/forum/viewtopic.php?f=6&t=41299#p203781

IMO the documented behavior should remain the same and check_uptime should behave as described.

**Comment by jfrickson** [comment]
Looking into this.

**Comment by jfrickson** [comment]
Since this plugin has been around for a few years, I changed the help text. Changing the functionality would break installations.

Fixed in branch `maint` via commit https://github.com/nagios-plugins/nagios-plugins/commit/32e8a6cf9a00cd15caafd14819ae6be57f07585c
