### ISSUE TITLE
check_http - Cannot make SSL connection behind proxy .

### ISSUE THREAD

**Issue by laconi51** [nagios-plugins/nagios-plugins#199]
Hi , 

When I use check_http (check_http v2.1.1 (nagios-plugins 2.1.1))   behind a proxy , I have a error Cannot make SSL connection :
 
```
check_http  -I PROXY_IP -p PORT -b user:pwd -u https://www.google.fr/ -S -j CONNECT -H google.fr 

CRITICAL - Cannot make SSL connection.
140071647782848:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:769:
```

Have you same problem  with version of check_http ?

**Comment by jfrickson** [comment]
This is the same issue as #90. We currently don't support proxy connections, but it is in the works. Keep an eye on #90 for progress. Thanks.

**Comment by laconi51** [comment]
Tanks you.

**Comment by jfrickson** [comment]
Looking into this, I found that a patch had been applied in August, 2015. That patch added `CONNECT` to the valid arguments to the `-j` option. The documentation states:
```
all these options are needed: -I <proxy> -p <proxy-port> -u <check-url> -S(sl) -j CONNECT -H <webserver>
```
