### ISSUE TITLE
check_cluster 

### ISSUE THREAD

**Issue by gvenka008c** [nagios-plugins/nagios-plugins#202]
Hi,

Is there any example on how to use check_cluster on icinga2? 

Thanks,
Govind

**Comment by jfrickson** [comment]
Check on Icinga's support forums.

**Comment by Thomas-Gelf** [comment]
@gvenka008c: should work like any other command. In case you're using Icinga Director you might want to check [this support issue](https://dev.icinga.com/issues/12928), scroll down to the last two screenshots, especially [this one](https://dev.icinga.com/attachments/download/3701/06__clustercheck_service_definition.png) - and then decide whether you want to read the rest of it ;-) The example doesn't use check_cluster but the Icinga 2 DSL, just because it's fancy. There is nothing wrong with parameterizing check_cluster the very same way.

**Comment by gvenka008c** [comment]
@Thomas-Gelf 

I configured the check_cluster to monitor the host states as show below. When I bring down one of the node, it is still showing OK status. Please suggest.

commands.conf

```
object CheckCommand "check_cluster" {
  import "plugin-check-command"

  command = [ "/usr/lib64/nagios/plugins/check_cluster" ]

  arguments = {
    "-l" = "$check_cluster_label$"
    "-w" = "$check_cluster_warning$"
    "-c" = "$check_cluster_critical$"
    "-d" = "$check_cluster_data$"
  }
}
```

services.conf

```
object Service "my-cluster-check" {
  host_name = NodeName
  check_command = "check_cluster"
  vars.check_cluster_label = "PING"
  vars.check_cluster_warning = 1
  vars.check_cluster_critical = 2
  vars.check_cluster_data = {{ get_service("host1.net", "PING").state_id + ", " + get_service("host2.net", "PING").state_id }}
}
```

**Comment by dnsmichi** [comment]
There's no such attribute named "state_id". You are rather looking for "state" which returns the current state as number.

That's the simple approach. If you prefer to just pass an array of object names, some more Icinga 2 DSL coding must be involved. 

Btw - check_cluster requires you to set `--host` and `--service` as well. So you'll need that inside your CheckCommand definition and then your Host or Service object.

Could look like this basically:

````
object CheckCommand "check_cluster" {
        import "plugin-check-command"

        command = [ PluginDir + "/check_cluster" ]

        arguments = {
                "--host" = {
                        set_if = "$check_cluster_host$"
                        description = "Check host cluster status"
                }
                "--service" = {
                        set_if = "$check_cluster_service$"
                        description = "Check service cluster status"
                }
                "--label" = {
                        value = "$check_cluster_label$"
                        description = "Optional prepended text output (i.e. \"Host cluster\")"
                }
                "--warning" = {
                        value = "$check_cluster_warning$"
                        description = "Specifies the range of hosts or services in cluster that must be in a non-OK state in order to return a WARNING status level"
                }
                "--critical" = {
                        value = "$check_cluster_critical$"
                        description = "Specifies the range of hosts or services in cluster that must be in a non-OK state in order to return a CRITICAL status level"
                }
                "--data" = {
                        value = "$check_cluster_data$"
                        description = "The status codes of the hosts or services in the cluster, separated by commas"
                }
        }
}
````

If you want to go deeper, enhance the CheckCommand e.g. by this logic at the end:

````
        //this hides the logic from the caller
        //define an array of full host/service object names in vars.check_cluster_objects
        //and set vars.check_cluster_service or vars.check_cluster_host accordingly
        vars.check_cluster_data = {{
                var cluster_objects = macro("$check_cluster_objects$")

                //type safety
                if (typeof(cluster_objects) != String && typeof(cluster_objects) != Array) {
                        return ""
                }

                var states = []

                for (obj in cluster_objects) {
                        if (macro("$check_cluster_service$")) {
                                states.add(get_object(Service, obj).state)
                        } else if (macro("$check_cluster_host$")) {
                                states.add(get_object(Host, obj).state)
                        } else {
                                return ""
                        }
                }

                return states.join(",")
        }}
````

Using a simple configuration for testing then defining two hosts and a ping4 service apply rule with some defined dummy states.

````
object Host "cluster-01" {
        check_command = "dummy"
        vars.dummy_state = 2
}

object Host "cluster-02" {
        check_command = "dummy"
        vars.dummy_state = 1
}

apply Service "ping4" {
        check_command = "dummy"

        if (match("*01", host.name)) {
                vars.dummy_state = 2
        } else {
                vars.dummy_state = 1//modify me
        }

        assign where match("cluster*", host.name)
}
````

In addition to that a cluster host and service which actually passes the cluster data to check_cluster then.

````
object Host "cluster-host" {
        check_command = "check_cluster"

        vars.check_cluster_host = true
        vars.check_cluster_label = "HOST"
        vars.check_cluster_warning = 1
        vars.check_cluster_critical = 2

        vars.check_cluster_objects = [ "cluster-01", "cluster-02" ]
}

apply Service "cluster-ping" {
        check_command = "check_cluster"

        vars.check_cluster_service = true
        vars.check_cluster_label = "PING"
        vars.check_cluster_warning = 1
        vars.check_cluster_critical = 2

        //the logic is hidden inside the CheckCommand in vars.check_cluster_data
        //vars.check_cluster_objects = [ "cluster-01!ping4", "cluster-02!ping4" ]

        //or the simple approach with manually setting vars.check_cluster_data
        vars.check_cluster_data = {{
                get_object(Service, "cluster-01!ping4").state + "," + get_object(Service, "cluster-02!ping4").state
        }}

        assign where host.name == "cluster-host"
}
````

Looks like this in Icinga Web 2 then:

Host check combining check_cluster:

<img width="692" alt="icingaweb2_check_cluster_host_check" src="https://cloud.githubusercontent.com/assets/382049/20938779/9c43919e-bbec-11e6-943a-c6d07084193d.png">

2 Services

<img width="268" alt="icingaweb2_check_cluster_service_check_cluster01" src="https://cloud.githubusercontent.com/assets/382049/20938781/9c6f7c32-bbec-11e6-8cea-dd8d9e4c1d33.png">
<img width="274" alt="icingaweb2_check_cluster_service_check_cluster02" src="https://cloud.githubusercontent.com/assets/382049/20938780/9c6ddd32-bbec-11e6-814b-c31a4e9300e7.png">

check_cluster Service

<img width="589" alt="icingaweb2_check_cluster_service_check_overall" src="https://cloud.githubusercontent.com/assets/382049/20938782/9c71e7f6-bbec-11e6-8279-e7c318557dd2.png">

Although check_cluster might be reasonable to call, I'd just go for [writing functions](https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/advanced-topics#access-object-attributes-at-runtime) and evaluating the state over there. We'll probably find a way to prevent the call to check_dummy at some point, for now it is up to you to choose ;-)
