### ISSUE TITLE
YUM output signature is larger than current known format - CentOS 7

### ISSUE THREAD

**Issue by Mies-bvd89** [nagios-plugins/nagios-plugins#209]
The following errors occurs on the check_yum plugin:
YUM output signature is larger than current known format, please make sure you have upgraded to the latest version of this plugin. If the problem persists, please contact the author for a fix 

OS: CentOS 7.X with latest updates installed.

Nagios Core: 4.2.4
Nagios Plugins: 2.14
Nagios Agent: NRPE 3.0.1

**Comment by jfrickson** [comment]
Looking into it.

**Comment by jfrickson** [comment]
Sorry it took so long. check_yum is a 3rd party plugin. Check for the most recent version on exchange.nagios.org and contact the author if the newest one still doesn't work.
