### ISSUE TITLE
How to calculate check_load plugin threshold?

### ISSUE THREAD

**Issue by bayupermadi** [nagios-plugins/nagios-plugins#211]
Hi, 

I have 4 CPUs in my VM and I want to monitor this using the check_load, but I can't find calculation in official pages of check_load plugin, [http://nagios-plugins.org/doc/man/check_load.html](url)

I want to monitor the CPU usage with threshold 
         
w = 75%, 70%, 65%
c = 85%, 80%, 75%

I've got from forum the calculation using formula: 
`y = c * p /100`

y = nagios value
c = core number
p = targeted percentages (etc : 75)

another answer said : 
1 min load avg:
w: <ncpu> * 8
c: <ncpu> * 10

5 min load avg:
w: <ncpu> * 5
c: <ncpu> * 8

15 min load avg:
w: <ncpu> * 2
c: <ncpu> * 3

I'm a bit confused what value that I need to set in check_load. 

Thank you

Bayu Permadi

**Comment by jfrickson** [comment]
First of all, `check_load` does not take percentages. It takes _load average_ numbers.

Here's a somewhat simplified explanation of _load average_. On a single CPU system, a load average of `1.0` means fully loaded. A l/a of `1.1` means a small number of processes spent some time waiting for their turn to run. If you have 4 cores, a fully loaded system would have a l/a of `4.0`.

So you might want to use the `-r` parameter, which means divide the load average by number of CPUs and deal with `1.0` as fully loaded. Then take into consideration that short-term spikes are pretty normal. For example, I just finished a `make all` on a project, and had a l/a of `2.18, 0.58, 0.29`. So you might want to raise your thresholds a bit.

Using your proposed percentages, your command line would look like this:
```
check_load -r -w 0.75, 0.7, 0.65 -c 0.85, 0.8, 0.75
```

The formula `y = c * p /100` is how you calculate the `-w` and `-c` numbers if you don't use the `-r` parameter. The other numbers (w: * 8 and c: * 10 and the others for example) were probably scaling factors. Essentially saying a 1 minute load average of `8.0` would trigger a warning, a 15 minute load average of `3.0` would trigger a critical, etc.
