### ISSUE TITLE
check_file_age is broken since the fix of #178

### ISSUE THREAD

**Issue by thesharp** [nagios-plugins/nagios-plugins#213]
# cat /etc/redhat-release
    Scientific Linux release 6.8 (Carbon)

    Updated nagios-plugins-file_age-2.0.3-3.el6.x86_64 @epel/6.7
    Update                          2.1.4-2.el6.x86_64 @epel 

    # /usr/lib64/nagios/plugins/check_file_age --version
    check_file_age v2.1.4 (nagios-plugins 2.1.4)
    The nagios plugins come with ABSOLUTELY NO WARRANTY. You may redistribute
    copies of the plugins under the terms of the GNU General Public License.
    For more information about these matters, see the file named COPYING.

After this update (and since the fix of #178) check_file_age is actually broken.

    # touch /tmp/file_age_test.txt
    # ls -l /tmp/file_age_test.txt
    -rw-r--r--. 1 root root 0 Jan  4 07:34 /tmp/file_age_test.txt
    # /usr/lib64/nagios/plugins/check_file_age -f /tmp/file_age_test.txt
    FILE_AGE CRITICAL: File not found - "/tmp/file_age_test.txt"

If we actually comment out that line, that https://github.com/nagios-plugins/nagios-plugins/commit/d8a41bb07740704ddc3682d6b6b12e09597edb20 added, we get this:

    # /usr/lib64/nagios/plugins/check_file_age -f /tmp/file_age_test.txt
    FILE_AGE OK: /tmp/file_age_test.txt is 90 seconds old and 0 bytes  | age=90s;240;600 size=0B;0;0;0

I didn't see any changes that would imply using different options to the plugin, so I'm guessing I'm still using it as intended.

**Comment by sircubbi** [comment]
check_file_age also broke badly for us on CentOS 6 this night.

Every file that is checked is surrounded by quotes, and therefore does not find the actual file any longer:

[root@genesis ~]# touch /tmp/test
[root@genesis ~]# /usr/lib64/nagios/plugins/check_file_age -f /tmp/test
FILE_AGE CRITICAL: File not found - "/tmp/test"
[root@genesis ~]# strace -f /usr/lib64/nagios/plugins/check_file_age -f /tmp/test
[...]
lstat("\"/tmp/test\"", 0x7ffd3c9c0f00)  = -1 ENOENT (No such file or directory)
stat("\"/tmp/test\"", 0xb25130)         = -1 ENOENT (No such file or directory)
write(1, "FILE_AGE CRITICAL: File not foun"..., 48FILE_AGE CRITICAL: File not found - "/tmp/test"

**Comment by jhrcz** [comment]
confirming @sircubbi 

quick fix is:

[root@anr ~]# diff check_file_age check_file_age.fixed
80c80
< #$opt_f = '"' . $opt_f . '"';
---
> $opt_f = '"' . $opt_f . '"';

**Comment by mrdun** [comment]
+1 the same behavior after latest update.
Removing double quotes in line 80 fixed the issue:
was: `$opt_f = '"' . $opt_f . '"';`
now: `$opt_f = '' . $opt_f . '';`

btw: in this case it works fine for files containing space in name if it taken into double quotes "" and space escaped with backslash, like:
`# /usr/lib64/nagios/plugins/check_file_age -w 0 -c 0 -f "/tmp/check\ file"
FILE_AGE OK: /tmp/check file is 4968 seconds old and 0 bytes  | age=4968s;0;0 size=0B;0;0;0`

**Comment by thesharp** [comment]
So, here I am sitting and wondering, how much time will take for devs to make another point-release and then for EPEL maintainers to push an update... My bet is we won't get it fixed in EPEL for at least a week.

**Comment by thesharp** [comment]
Also, I saw some unit-tests in the repository, so my question is: are they no longer in use?

I didn't check, if they break the build now, because I didn't want to install some Perl mumbo-jumbo for them to work, but seriously, that bug should absolutely break the build, so I'm kinda wondering how that all happened anyways.

**Comment by sircubbi** [comment]
I did a quick (and dirty) build of nagios_plugins for EPEL 6 and 7, to remove the double quotes. However, this breaks files with spaces in it once again. However, as I need the old functionality for now, it is at least good enough for me, till a final fix is available.

You can grab the builds from our internal copr at https://copr.fedorainfracloud.org/coprs/sklempert/relaix/build/495376/

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/367a44187db1c18a9fd4ba5fafe844f80cbb03c5

I'll try to get this released soon.
