### ISSUE TITLE
check_file_age always reports file not found due to new quoting behavior

### ISSUE THREAD

**Issue by pmkane** [nagios-plugins/nagios-plugins#214]
This commit to check_file_age:

  https://github.com/nagios-plugins/nagios-plugins/commit/d8a41bb07740704ddc3682d6b6b12e09597edb20

breaks the plugin entirely for filenames without spaces, because glob preserves the quotes, so the file exists check in the loop fails.  A small test case you can use to reproduce:

touch /tmp/test.txt
/usr/lib64/nagios/plugins/check_file_age /tmp/test.txt
"/tmp/test.txt"FILE_AGE CRITICAL: File not found - "/tmp/test.txt"

Pull request incoming with a fix.

**Comment by davidjb** [comment]
Hit this issue when the new Nagios plugin packages rolled out today via EPEL.  Pull request works for me, thanks @pmkane!

**Comment by pmkane** [comment]
No worries.  That's exactly how it bit us too!

**Comment by jfrickson** [comment]
This has been fixed and will be released next week. See issue #213. I'll leave this issue open for a while so others can find it.

**Comment by jfrickson** [comment]
2.2.0 is now released, so I'm closing this issue.
