### ISSUE TITLE
check_snmp 'can't create directory: /var/996' 

### ISSUE THREAD

**Issue by basg** [nagios-plugins/nagios-plugins#218]
Having just updated to nagios-plugins-2.1.4 (RPM from EPEL-stable),
checks using check_snmp now return: `UNKNOWN: can't create directory: /var/[uid]`. 
The error seems to point to the path used for writing rate-calculation files. In previous versions this defaulted to `/var/check_snmp`. This didn't occur using the 2.1.4 RPM from EPEL-testing. 

I have two requests: 
- It would be helpful if this path could be set by means of an argument to the script.
- The requirements for a valid rate data path aren't documented at all. It would clarify things if this could be fixed.

**Comment by jfrickson** [comment]
Looking into this.

**Comment by jfrickson** [comment]
Does this occur when you compile from source? Or only when you install via packages?

**Comment by basg** [comment]
Thanks for looking into this!
We haven't tried compiling from source, this happened when installing via packages.

**Comment by box293** [comment]
Here are some detailed instructions for installing from source:
https://support.nagios.com/kb/article.php?id=569

**Comment by jfrickson** [comment]
@basg did you ever try compiling from source?

**Comment by hedenface** [comment]
@basg I'm going to close the issue. If you compile from source and the issue persists, feel free to open this issue or create a new one.
