### ISSUE TITLE
check_file_age returns "FILE_AGE CRITICAL: File not found" for files that exist, on older versions of Perl (e.g. v5.10.1)

### ISSUE THREAD

**Issue by anthonykirby** [nagios-plugins/nagios-plugins#219]
I've just updated to nagios-plugins-2.1.4, and found that check_file_age is now returning "FILE_AGE CRITICAL: File not found" for files that do exist.

It looks like this regression is due to the change which adds quotes to the filename string (https://github.com/nagios-plugins/nagios-plugins/commit/d8a41bb07740704ddc3682d6b6b12e09597edb20).

This is OK on recent versions of Perl, where glob() subsequently strips the quotes, but older versions of Perl (in my case, v5.10.1 which I think is quite widespread still - CentOS 6) don't strip the quotes.  Then, a filename with quotes fails the "-e" test.

**Comment by anthonykirby** [comment]
thanks, sorry for the dupe

**Comment by jfrickson** [comment]
No problem. For a big issue like this, I should have left the other one open :-)

**Comment by jfrickson** [comment]
2.2.0 is now released, so I'm closing this issue.

**Comment by waseemabbaskhan** [comment]
@jfrickson 
Hi
I am also facing in check_file_age Plugging. I have opened a new thread with all details. 
Please let me know if you can please help with any solution. Please see the below link for the thread;
https://community.icinga.com/t/check-file-age-file-age-critical-file-not-found/10346/3?u=waseemabbaskhan

Also please let me know if further any details are required.

Thank You
