### ISSUE TITLE
check_mysql_query & mysql_query: extra-opts causes crash

### ISSUE THREAD

**Issue by sinuswave** [nagios-plugins/nagios-plugins#221]
Using --extra-opts causes a plugin crash of
- check_mysql_query
- mysql_query
- check_http

Example: 
`/usr/lib64/nagios/plugins/check_mysql_query --extra-opts
*** glibc detected *** /usr/lib64/nagios/plugins/check_mysql_query: free(): invalid pointer: 0x000000000040c892 ***`

Affected Version 2.1.4
Operating system: CentOS 6 and CentOS 7
Plugins.ini location: /etc/nagios/plugin.ini

[backtrace.txt](https://github.com/nagios-plugins/nagios-plugins/files/693847/backtrace.txt)
[plugins.ini.txt](https://github.com/nagios-plugins/nagios-plugins/files/693850/plugins.ini.txt)

**Comment by sinuswave** [comment]
Just compiled and checked version 2.2.0 on CentOS 7 -> Same behavior.

**Comment by jfrickson** [comment]
Looking into this.

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/nagios-plugins/nagios-plugins/commit/14207d0dbe0db19f4cddd7d4dea7669ffed81a5a

Will be in release 2.2.2
