### ISSUE TITLE
issue with check_dns

### ISSUE THREAD

**Issue by gardart** [nagios-plugins/nagios-plugins#223]
After updating nagios-plugins-dns (on Centos 6 using epel) we are now getting this output from check_dns plugin:

DNS CRITICAL - expected ‘{hostname}.’ but got 'name = {hostname}.'

Could this be a new bug?

**Comment by hakong** [comment]
Had this problem aswell on 3 machines. CentOS 7 after a yum update:
`Jan 04 03:19:42 Updated: nagios-plugins-dns-2.1.4-2.el6.x86_64
`

**Comment by gardart** [comment]
I created a new issue for this bug here:
https://github.com/nagios-plugins/nagios-plugins/issues/223

**Comment by smooge** [comment]
gardent I will see if I can patch the epel-6 version can you give me an example oh how you call check_dns to get this problem?

**Comment by smooge** [comment]
For a similar problem with MX the issue was with the IF_RECORD macro which tries to compare everything with a ' ' entry while the old MX used '=' for its call. I have added a generic comparison part to the macro and edited the calls to it. Patch included in the next comment

**Comment by smooge** [comment]
[check_dns_patch.txt](https://github.com/nagios-plugins/nagios-plugins/files/800549/check_dns_patch.txt)

**Comment by gardart** [comment]
thanks @smooge 
I will try this out

**Comment by smooge** [comment]
If you are using EPEL-6 you can try the build at https://koji.fedoraproject.org/koji/taskinfo?taskID=18040433

**Comment by smooge** [comment]
OK I broke TXT records with that patch because the TXT record can't use the macro as it needs to back up and remember the " it searches for. I am throwing out new builds https://koji.fedoraproject.org/koji/taskinfo?taskID=18061480
This build should show up in epel-testing in a while.

**Comment by smooge** [comment]
[check_dns.20170228.patch.txt](https://github.com/nagios-plugins/nagios-plugins/files/807603/check_dns.20170228.patch.txt)

**Comment by jfrickson** [comment]
Checking out the patch. Should incorporate it soon.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/779fcb13a6100170cb9cb1ca334b91d4bbfdb5eb

Thanks @smooge !

**Comment by jbg-uwaterloo** [comment]
I agree it is not working on 2.1.4, so downloaded 2.2.1, compiled and it is failing identically.  I checked and the patch listed above is applied.

$ grep PTR  check_dns.c  
    else IF_RECORD("name =", "-querytype=PTR", "Found PTR record\n", ' ') }
  /* No information (e.g. nameserver IP has two PTR records) */
$ ./check_dns -V
check_dns v2.2.1 (nagios-plugins 2.2.1)
$ ./check_dns -H XXXXXXX -s XXXXXXX -t 15 -a "cn-ipam-mc.uwaterloo.ca."
DNS CRITICAL - expected 'cn-ipam-mc.uwaterloo.ca.' but got 'name = cn-ipam-mc.uwaterloo.ca.'
