### ISSUE TITLE
Downstream reported bug with check_dns and reverse lookups

### ISSUE THREAD

**Issue by smooge** [nagios-plugins/nagios-plugins#225]
https://bugzilla.redhat.com/show_bug.cgi?id=1409932

Description of problem:

After updating to nagios-plugins-dns-2.1.4-2.el7.x86_64, check_dns returns an error when performing reverse lookups.

Version-Release number of selected component (if applicable):
nagios-plugins-dns-2.1.4-2.el7.x86_64

How reproducible:

Every time.

Steps to Reproduce:
1. /usr/lib64/nagios/plugins/check_dns -a "google-public-dns-a.google.com." -H 8.8.8.8

Actual results:

DNS CRITICAL - expected 'google-public-dns-a.google.com.' but got 'name = google-public-dns-a.google.com.'

Expected results:

DNS OK: 0.005 seconds response time. 8.8.8.8 returns google-public-dns-a.google.com.|time=0.004877s;;;0.000000

Additional info:

Was working as expected until the updated to the new version.  The 'name = ' part of what it's getting during lookup is obviously wrong.

**Comment by jfrickson** [comment]
Same problem as issue #223

**Comment by jfrickson** [comment]
This should also be fixed in branch 'maint' by commit https://github.com/nagios-plugins/nagios-plugins/commit/779fcb13a6100170cb9cb1ca334b91d4bbfdb5eb which was a fix for issue #223
