### ISSUE TITLE
Stripped-down CGI-bin that still triggers the SEGV in check_http

### ISSUE THREAD

**Issue by smooge** [nagios-plugins/nagios-plugins#226]
I am the new Fedora nagios-plugins packager and am reporting bugs from the Red Hat Bugzilla that are reported against 2.1.4 and later:

https://bugzilla.redhat.com/show_bug.cgi?id=1412016

Stripped-down CGI-bin that still triggers the SEGV in check_http

Description of problem:

check_http segfaults on a specific (CGI-bin generated) web page.

Version-Release number of selected component (if applicable):

nagios-plugins-http-2.1.4-2.el6.x86_64
(worked with previously installed nagios-plugins-http-2.0.3-3.el6.x86_64)
(page is served by thttpd-2.25b-23.el6.x86_64, also from EPEL, base OS is CentOS 6.8)

How reproducible:

Running check_http from shell to retrieve said page reliably causes SIGSEGV.

Steps to Reproduce:
1. Install nagios-plugins-http and thttpd
2. Configure thttpd to serve a CGI-bin (excerpt of config on our server:
$ grep '^[^#]' /etc/thttpd.conf
dir=/var/www/thttpd
pidfile=/var/run/thttpd.pid
port=9480
cgipat=/index.cgi|/minimal.cgi
)
3. Install CGI-bin (minimal version still triggering the problem attached; expanding the HTTP headers so as to resemble those thttpd generates for static pages did not change the results for me)
4. Run check_http as shown in the example results below

Actual results:

$ /usr/lib64/nagios/plugins/check_http -I 127.0.0.1 -H localhost -p 9480 -u /minimal.cgi -m 400:500 -w 1 -c 3 -v
GET /minimal.cgi HTTP/1.1
User-Agent: check_http/v2.1.4 (nagios-plugins 2.1.4)
Connection: close
Host: localhost:9480
Accept: */*

http://127.0.0.1:9480/minimal.cgi is 150 characters
STATUS: HTTP/1.0 200 OK
Segmentation fault
$ echo $?
139

Expected results:

(Textual page content redacted.)

$ /usr/lib64/nagios/plugins/check_http -I 127.0.0.1 -H localhost -p 9480 -u /index.html -m 400:500 -w 1 -c 3 -v
GET /index.html HTTP/1.1
User-Agent: check_http/v2.1.4 (nagios-plugins 2.1.4)
Connection: close
Host: localhost:9480
Accept: */*

http://127.0.0.1:9480/index.html is 554 characters
STATUS: HTTP/1.1 200 OK
**** HEADER ****
Server: thttpd
Content-Type: text/html; charset=iso-8859-1
Date: Wed, 11 Jan 2017 01:09:50 GMT
Last-Modified: Tue, 26 Nov 2013 12:22:24 GMT
Accept-Ranges: bytes
Connection: close
Content-Length: 329

**** CONTENT ****
&lt;HTML&gt;&lt;HEAD>&lt;TITLE>Redacted redacted redacted&lt;/TITLE&gt;
        &lt;META HTTP-EQUIV="refresh" CONTENT="3; URL=/index.cgi">&lt;/HEAD&gt;
&lt;BODY BGCOLOR="#FFFFFF" TEXT="#000000" LINK="#000077" VLINK="#000033" ALINK="#770033"&gt;
&lt;H1&gt;Redacted redacted redacted&lt;/H1&gt;
Redacted redacted redacted ...
&lt;/BODY&gt;&lt;/HTML&gt;

HTTP WARNING: HTTP/1.1 200 OK - page size 554 too large - 554 bytes in 0.009 second response time |time=0.008997s;1.000000;3.000000;0.000000 size=554B;400;0;0
$ echo $?
1

Additional info:

**Comment by jfrickson** [comment]
Getting to this soon.

**Comment by jfrickson** [comment]
I finally got this to fail with plugins 2.1.4. It works fine with plugins 2.2.1 which is due for release on Apr 19. I strongly suspect it also works with 2.2.0, but I didn't check.
