### ISSUE TITLE
Math-Calc-Units-1.07 license compatibility

### ISSUE THREAD

**Issue by lavinialav** [nagios-plugins/nagios-plugins#227]
I have a question regarding the licenses found in the Nagios-plugins packages. 
There is a subcomponent in the packages called Math-Calc-Units-1.07 that is licensed under dual license GPL V2.0 or Artistic License V1.0. I understand that starting with version 1.4.16 the global license was changed from GPL V2.0 to GPL V3.0. According to the information found on the following websites:
•	https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses
•	https://www.gnu.org/licenses/license-list.html#ArtisticLicense 
•	https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#GPL_Compatibility_Matrix 
GPL V3.0 is incompatible with both of them. Therefore, since version 1.4.16 of nagios-plugins, there seems to be a violation of the license conditions. 
I want to ask you if there’s something that I’m missing. Do you have a special permission from the authors of Math-Calc-Units to use the component in a GPL V3.0-licensed package? 
I would appreciate if someone could clarify the situation. Thank you!

**Comment by chicks-net** [comment]
This is why I stick with GPL2 for my own projects.

**Comment by jfrickson** [comment]
I'm pretty sure we're compatible, but we're looking into it.

**Comment by jfrickson** [comment]
It appears that the author's dual licensing actually does allow us to do this. If you feel that this is in error, please open a new issue. Thank you.
