### ISSUE TITLE
check_users not accepting zero as the threshold

### ISSUE THREAD

**Issue by TiZon** [nagios-plugins/nagios-plugins#228]
Hi

We have a few systems people should not be logging into. Our monitoring uses check_users for this with the following configuration:

`./check_users -w 0 -c 1`

Output:

    [bart@shared-01 plugins]# ./check_users -w 0 -c 1
    check_users: Warning threshold must be a positive integer
    Usage:
    check_users -w <users> -c <users>

Expected output:

    [bart@shared-01 plugins]# ./check_users -w 0 -c 1
    USERS WARNING - 1 users currently logged in |users=1;0;1;0

I think a bug was introduced in commit 972ee5bc7286b2ed7c7774e09f35bddeb1d05189, or did I miss something?

Version:

`check_users v2.1.4 (nagios-plugins 2.1.4)`

Result from other machine with older version:

    [bart@ftp-01 plugins]# ./check_users -V
    check_users v2.0.3 (nagios-plugins 2.0.3)
    [bart@ftp-01 plugins]# ./check_users -w 0 -c 1
    USERS WARNING - 1 users currently logged in |users=1;0;1;0

Thanks!

**Comment by TiZon** [comment]
Also see PR https://github.com/nagios-plugins/nagios-plugins/pull/224

**Comment by simvirus** [comment]
I can confirm it!

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/nagios-plugins/nagios-plugins/commit/2c510d45a48c4ff7848448891dba5dab36541c87
