### ISSUE TITLE
Building RPMs on Amazon Linux

### ISSUE THREAD

**Issue by danieljamesscott** [nagios-plugins/nagios-plugins#229]
I'm trying to build the plugin RPMs for Amazon Linux. The build errors with the following:

`RPM build errors:
    File not found: /var/lib/mysql/build/rpmbuild/BUILDROOT/nagios-plugins-2.1.4-1.x86_64/usr/lib/nagios/plugins/check_dhcp
    File not found: /var/lib/mysql/build/rpmbuild/BUILDROOT/nagios-plugins-2.1.4-1.x86_64/usr/lib/nagios/plugins/check_icmp
    File not found: /var/lib/mysql/build/rpmbuild/BUILDROOT/nagios-plugins-2.1.4-1.x86_64/usr/lib/nagios/plugins/check_ldaps`

Can anyone help me figure out what I need to do to fix these errors?

**Comment by danieljamesscott** [comment]
I've fixed the ldap issue by installing the openssl-devel package, although I'm not sure why it would be trying to install something which wasn't built.

I managed to fix the dhcp and icmp issue by adding 'install root' to the 'make' line 165:

`make AM_INSTALL_PROGRAM_FLAGS="" DESTDIR=${RPM_BUILD_ROOT} install install-root`


Is this a suitable fix?

**Comment by jfrickson** [comment]
I believe that's correct. But I'm looking into it, to be sure.

**Comment by jfrickson** [comment]
It would be nice to include the line you've specified in configure file commented out with some basic instructions alerting the next bystander of this issue. - Bryan

**Comment by danieljamesscott** [comment]
Not sure what you mean here. You want me to do a pull request?

**Comment by jfrickson** [comment]
Never mind. I figured it out. Should be fixed in branch `maint` via commit https://github.com/nagios-plugins/nagios-plugins/commit/412065376a6ca487a2efcb60819bcebc5c83e651
