### ISSUE TITLE
check_http reports warning where it should report ok with -e

### ISSUE THREAD

**Issue by sonologic** [nagios-plugins/nagios-plugins#236]
With 2.1.4, this http command would result in 'ok' status when the host reported a '404 NotFound':

check_http -H hostname -p 9000 -I 1.2.3.4 -e "404 NotFound"

With 2.2.0 this reports a 'warning':

HTTP WARNING: Status line output matched "404 NotFound" - HTTP/1.1 404 NotFound - 467 bytes in 0.099 second response time |time=0.099418s;;;0.000000 size=467B;;;0

A quick check reveals a bunch of changes in this plugin related to response processing, but I'm quite short on time at the moment (moving houses) so I have no time to dig in to this for at least a week.

**Comment by mat813** [comment]
This was broken in 657e3b6 while fixing #91

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/nagios-plugins/nagios-plugins/commit/7300528aca1da07b93cab52493552b445b1c276b
