### ISSUE TITLE
check_mailq Nullmailer Regex is not working for Ubuntu 16.04

### ISSUE THREAD

**Issue by JustKiddingCode** [nagios-plugins/nagios-plugins#237]
On ubuntu 16.04 the nullmailer regex is wrong:
```
\s{2} is now \s
282  bytes -> 282 bytes
```

**Comment by jfrickson** [comment]
I assume you mean the regex on line 537 of check_mailq? I don't think we want to replace it with just `\s`, maybe `\s{1,2}`?

**Comment by JustKiddingCode** [comment]
Think that is a good idea

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/4b1bc908d7aebdc4f27cb3843c2d844d61dab21b
