### ISSUE TITLE
check_snmp does not work with -6 --ipv6 flags

### ISSUE THREAD

**Issue by smooge** [nagios-plugins/nagios-plugins#239]
On building 2.1.4 for Fedora/EPEL I got a bug report https://bugzilla.redhat.com/show_bug.cgi?id=1422993 

I confirmed that the problem occurs on different build and it looks like the problem is that while the case statement has rules for ipv6 etc, the getopt line does not have  definitions for the missing types.

```
diff -up ./plugins/check_snmp.c.fixes_for_release_201702 ./plugins/check_snmp.c
--- ./plugins/check_snmp.c.fixes_for_release_201702     2017-02-16 14:51:36.746130335 -0500
+++ ./plugins/check_snmp.c      2017-02-16 14:52:27.381140385 -0500
@@ -724,7 +724,7 @@ process_arguments (int argc, char **argv
        }
 
        while (1) {
-               c = getopt_long (argc, argv, "nhvVOt:c:w:H:C:o:e:E:d:D:s:t:R:r:l:u:p:m:P:N:L:U:a:x:A:X:",
+               c = getopt_long (argc, argv, "nhvVO46t:c:w:H:C:o:e:E:d:D:s:t:R:r:l:u:p:m:P:N:L:U:a:x:A:X:",
                                                                         longopts, &option);
 
                if (c == -1 || c == EOF)
```

**Comment by jfrickson** [comment]
Thanks for spotting the problem!

Fixed in branch `maint` via commit https://github.com/nagios-plugins/nagios-plugins/commit/437cf92c3cffbd26016ad68d4a49d59eebd1fafd
