### ISSUE TITLE
check_http fails if Transfer-Encoding ends the header

### ISSUE THREAD

**Issue by mcapra** [nagios-plugins/nagios-plugins#240]
See here for info and patch:

https://support.nagios.com/forum/viewtopic.php?t=42615

**Comment by marcomusso** [comment]
In my case check_http fails also if the transfer-encodign header is correctly terminated. Tested v2.1.2 on Ubuntu is unaffected.

**Comment by danel1** [comment]
Bump - we have this problem in multiple cases, would be cool if it gets fixed in the next version.

**Comment by jfrickson** [comment]
I am looking into this and it should be fixed soon. Thanks for the interest and the patch!

**Comment by jfrickson** [comment]
I have a possible fix in branch `maint`. Could you all try it out and let me know if it works? Thanks!

**Comment by leres** [comment]
I can't find a good test case (none of the servers that were putting the Transfer-Encoding header last in February are doing  that today) but the check  still works and the new code looks correct to me.

**Comment by jfrickson** [comment]
I'm going to assume commit https://github.com/nagios-plugins/nagios-plugins/commit/bb6155bbbd40307bc6011f331e50d478ecfcd80b fixed the problem. If it shows up again, open another issue.
