### ISSUE TITLE
spelling mistake = configure: WARNING: Could not find qmail-qstat or "eqivalent"

### ISSUE THREAD

**Issue by box293** [nagios-plugins/nagios-plugins#247]
configure: WARNING: Could not find qmail-qstat or eqivalent

eqivalent should be equivalent

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/9d70d2462a5c17ea57e6166bb62902399fe0d9e1
