### ISSUE TITLE
check_sensors is compiled when sensors is not present

### ISSUE THREAD

**Issue by box293** [nagios-plugins/nagios-plugins#253]
```
/usr/local/nagios/libexec/check_sensors
SENSORS UNKNOWN - command not found (did you install lmsensors?)
```
There are no checks in configure to detect if the sensors binary exists. 

Installing lm_sensors allowed the plugin to work.

If the binary does not exist then the plugin should not be compiled.

**Comment by jfrickson** [comment]
There's not really a good way to deal with this.
