### ISSUE TITLE
check_mysql_query doesn't gracefully handle Japanese characters

### ISSUE THREAD

**Issue by mcapra** [nagios-plugins/nagios-plugins#256]
Ref:
https://support.nagios.com/forum/viewtopic.php?t=43053

 Japanese characters in a conditional don't return results from check_mysql_query, while they do using mysql from the CLI.

**Comment by jfrickson** [comment]
Looks like a problem. I'll be checking it out.

**Comment by jfrickson** [comment]
@mcapra Can you test again using version 2.2.1? I get the following:
```
# ./check_mysql_query -V
check_mysql_query v2.2.1.29.g6551a (nagios-plugins 2.2.1)
# ./check_mysql_query -q "SELECT * FROM oc_order WHERE payment_method = '銀行振込'" -H 127.0.0.1 -d test
QUERY OK: 'SELECT * FROM oc_order WHERE payment_method = '銀行振込'' returned 1.000000 | result=1.000000;;;
```
I didn't change anything in `check_mysql_query`, so I'm thinking it has something to do with the environment.

**Comment by mcapra** [comment]
`
[root@nagios libexec]# echo $LANG
en_US.UTF-8

[root@nagios libexec]# ./check_mysql_query -V
check_mysql_query v2.2.1.git (nagios-plugins 2.2.1)

[root@nagios libexec]# ./check_mysql_query -q "SELECT * FROM oc_order WHERE payment_method = '銀行振込'" -H 127.0.0.1 -d test -u root -p hunter2
QUERY WARNING: No rows returned

[root@nagios libexec]# ./check_mysql_query -q "SELECT * FROM oc_order WHERE 1" -H 127.0.0.1 -d test -u root -p hunter2
QUERY OK: 'SELECT * FROM oc_order WHERE 1' returned 1.000000 | result=1.000000;;;

[root@nagios libexec]# ./check_mysql_query -q "SELECT * FROM oc_order WHERE payment_method LIKE '%'" -H 127.0.0.1 -d test -u root -p hunter2 -v
QUERY OK: 'SELECT * FROM oc_order WHERE payment_method LIKE '%'' returned 1.000000 | result=1.000000;;;

[root@nagios libexec]# mysql -uroot -phunter2 test
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 19
Server version: 5.5.52-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [test]> SELECT * FROM oc_order WHERE payment_method = '銀行振込';
+----+----------------+
| id | payment_method |
+----+----------------+
|  1 | 銀行振込       |
+----+----------------+
1 row in set (0.00 sec)

MariaDB [test]> DESCRIBE oc_order;
+----------------+-------------+------+-----+---------+----------------+
| Field          | Type        | Null | Key | Default | Extra          |
+----------------+-------------+------+-----+---------+----------------+
| id             | int(11)     | NO   | PRI | NULL    | auto_increment |
| payment_method | varchar(50) | NO   |     | 0       |                |
+----------------+-------------+------+-----+---------+----------------+

MariaDB [test]> SELECT @@character_set_database;
+--------------------------+
| @@character_set_database |
+--------------------------+
| utf16                    |
+--------------------------+
1 row in set (0.00 sec)

`

Still seems to be failing despite the record existing. Matching the DB's charset with the system's charset doesn't seem to help:

`
[root@nagios libexec]# echo $LANG
en_US.UTF-8

[root@nagios libexec]# mysql -uroot -phunter2 test2
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 42
Server version: 5.5.52-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [test2]> SELECT * FROM oc_order;
+----+----------------+
| id | payment_method |
+----+----------------+
|  1 | 銀行振込       |
+----+----------------+
1 row in set (0.00 sec)

MariaDB [test2]> SELECT * FROM oc_order WHERE payment_method = '銀行振込';
+----+----------------+
| id | payment_method |
+----+----------------+
|  1 | 銀行振込       |
+----+----------------+
1 row in set (0.00 sec)

MariaDB [test2]> SELECT @@character_set_database;
+--------------------------+
| @@character_set_database |
+--------------------------+
| utf8                     |
+--------------------------+
1 row in set (0.00 sec)


[root@nagios libexec]# ./check_mysql_query -q "SELECT * FROM oc_order WHERE payment_method = '銀行振込';" -H 127.0.0.1 -d test2 -u root -p hunter2 -v
QUERY WARNING: No rows returned
`

**Comment by hedenface** [comment]
I was able to confirm this in 2.2.1. Unsure what the issue is as of right now, but I'm adding it to 2.2.2.

**Comment by Madlohe** [comment]
Issue seems to be that we never call [mysql_set_character_set()](https://dev.mysql.com/doc/refman/5.7/en/mysql-set-character-set.html) in the plugin. I've pushed a branch that fixes this by adding another option (-a or --character-set). Not sure if that technically makes this an "enhancement" or if we can still put it in 2.2.2.
