### ISSUE TITLE
check_log lost ability to use regexes for query (-q) in 2.1.4

### ISSUE THREAD

**Issue by waynewinchjr** [nagios-plugins/nagios-plugins#258]
The check_log plugin version 2.0.3 supported the use of complex regexes for the query option through the use of egrep; however, version 2.1.4 eschewed use of egrep for regular grep, which on RedHat/Centos 6.8 at least, does not accept full regexes.  As a result, queries more complex than direct pattern matches (e.g., something as simple as ERROR|WARNING) now incorrectly indicate as false negatives.  Needless to say, this is a very bad development when relying on Nagios to convey application problems through regular log mining.

As a fix, check_log should be modified in at least the following two places to restore the proper behavior (i.e., use the POSIXly-correct -E option to grep or egrep itself, though I am not sure why the change from egrep to grep within check_log in the first place):

```
# Count the number of matching log entries we have
count=`grep -E -c "$query" $tempdiff`

# Get the last matching entry in the diff file
lastentry=`grep -E "$query" $tempdiff | tail -1`

```
The line preceding these two lines uses grep but does not require -E to function correctly (i.e., no change is required):

`diff $logfile $oldlog | grep -v "^>" > $tempdiff
`

**Comment by jfrickson** [comment]
It looks like that was done in 2014 as part of a fairly large commit. I'll go through it and fix this, and also see if it broke anything else.

**Comment by jfrickson** [comment]
Fixed via commit https://github.com/nagios-plugins/nagios-plugins/commit/cd53a82944987cd8738fa95507086319530d6c91
