### ISSUE TITLE
check_uptime result is wrong

### ISSUE THREAD

**Issue by purplegrape** [nagios-plugins/nagios-plugins#260]
$./check_uptime -V
check_uptime v2.1.4 (nagios-plugins 2.1.4)
$./check_uptime -w 120 -c 60
Uptime CRITICAL: 0 day(s) 3 hour(s) 0 minute(s) | uptime=180.000000;120.000000;60.000000;

**Comment by purplegrape** [comment]
$./check_uptime -w 120 -c 60 -vvv
Verbose mode enabled
No unit of time measurement specified. Using default: "minutes"
Uptime in seconds returned from timespec struct: 10977.000000
Uptime CRITICAL: 0 day(s) 3 hour(s) 2 minute(s) | uptime=182.000000;120.000000;60.000000;

**Comment by purplegrape** [comment]
my server uptime is greater than 120 ,but got a CRITICAL result

**Comment by jfrickson** [comment]
The help message for check_uptime was actually backwards. check_uptime returns an error if the uptime is **more** than the thresholds.

The help message was fixed in the 'maint' branch a little over a week before you posted this.
