### ISSUE TITLE
check_ping doesn't auto configure to use the timeout (-t) flag on BSD unix.

### ISSUE THREAD

**Issue by Infiniverse** [nagios-plugins/nagios-plugins#261]
BSD unix ping has a '-t' timeout flag, but it doesn't look like the stock auto configure is detecting it (which is strange because it's a pretty standard flag). As a consequence BSD users get a timeout error when a ping times out and don't get the proper response from the ping command that would indicate why the timeout occurred.

     ping [-AaDdfnoQqRrv] [-c count] [-G sweepmaxsize] [-g sweepminsize]
          [-h sweepincrsize] [-i wait] [-l preload] [-M mask | time] [-m ttl]
          [-P policy] [-p pattern] [-S src_addr] [-s packetsize] [-t timeout]
          [-W waittime] [-z tos] host
     ping [-AaDdfLnoQqRrv] [-c count] [-I iface] [-i wait] [-l preload]
          [-M mask | time] [-m ttl] [-P policy] [-p pattern] [-S src_addr]
          [-s packetsize] [-T ttl] [-t timeout] [-W waittime] [-z tos]
          mcast-group

**Comment by jfrickson** [comment]
I'm looking into this

**Comment by Infiniverse** [comment]
Cool! Thanks :). We've changed the config for the FreeBSD pkgs - but the other BSD's will benefit from this change.

For ping6 the flag is -X:

     ping6 [-DdfHmnNoqrRtvwW] [-a addrtype] [-b bufsiz] [-c count]
           [-g gateway] [-h hoplimit] [-I interface] [-i wait] [-x waittime]
           [-X timeout] [-l preload] [-P policy] [-p pattern] [-S sourceaddr]
           [-s packetsize] [hops ...] host

**Comment by jfrickson** [comment]
I've been looking into this, finally. The `configure.ac` file has a whole long string of tests to figure out what parameters should be used on `ping` and `ping6` commands, and none of them are documented. And they have to be tested in a particular order. I know where I would put the check, but it's entirely possible that it would end up messing things up on some other system.

For example, a lot of systems use `-t` for TTL. Some use it for TOS. Linux uses `-W' for the timeout. AIX uses `-w`. HPUX uses `-m`. For Solaris, you just tack the timeout on at the very end of the command without a switch. Oh, and AIX, HPUX and Solaris all have multiple versions of `ping` with different command-line parameters.

It looks like the timeout parameter is only detected for Cygwin and Linux's `-W`. No other system does, at this point.

Unless you have any idea how to do the checks, I would suggest just using:
```
./configure --with-ping-command="-n -c %d -t %d %s" --with-ping6-command="-n -c %d -X %d %s"
```

**Comment by hedenface** [comment]
Should be fixed here: https://github.com/nagios-plugins/nagios-plugins/commit/0220bdad298064a1eee683cda5d79cc8984e5f7e

Please test and let me know!
