### ISSUE TITLE
check_pgsql output extra information

### ISSUE THREAD

**Issue by philipowen** [nagios-plugins/nagios-plugins#264]
check_pgsql would be more useful when running a custom query if extra information could be returned by the plugin. For example, currently a check looking at the result of `SELECT count(order_id) FROM ...` could find orders in an invalid state and alert when more than zero are found. In this scenario, being able to include the order IDs or other arbitrary information would be very helpful. A second result column could be used for this e.g. `SELECT count(order_id), string_agg('' || order_id, E'\n') FROM` so the second column contains the order IDs. This could be added to the plugin output.

It looks like a small addition after the exiting call to PQgetvalue could fetch this and output if a given argument was set and the column was present.

**Comment by jfrickson** [comment]
This looks doable. I'll look into it further.

**Comment by Madlohe** [comment]
Resolved by #464 (and not by the commit after, that was a typo).
