### ISSUE TITLE
check_http: sending extra CRLF after POST data

### ISSUE THREAD

**Issue by zarnovican** [nagios-plugins/nagios-plugins#266]
## Problem

We have noticed that `check_http` is sending an extra CRLF after post data. This is causing problems with http/1.1 server with strict validation (Python aiohttp server). It returns 400 as response.

```
/usr/lib64/nagios/plugins/check_http -H localhost -P foo -j POST -p 8000
```
```
$ nc -l 8000 | hexdump -C
00000000  50 4f 53 54 20 2f 20 48  54 54 50 2f 31 2e 31 0d  |POST / HTTP/1.1.|
00000010  0a 55 73 65 72 2d 41 67  65 6e 74 3a 20 63 68 65  |.User-Agent: che|
00000020  63 6b 5f 68 74 74 70 2f  76 32 2e 30 2e 33 20 28  |ck_http/v2.0.3 (|
00000030  6e 61 67 69 6f 73 2d 70  6c 75 67 69 6e 73 20 32  |nagios-plugins 2|
00000040  2e 30 2e 33 29 0d 0a 43  6f 6e 6e 65 63 74 69 6f  |.0.3)..Connectio|
00000050  6e 3a 20 63 6c 6f 73 65  0d 0a 48 6f 73 74 3a 20  |n: close..Host: |
00000060  6c 6f 63 61 6c 68 6f 73  74 3a 38 30 30 30 0d 0a  |localhost:8000..|
00000070  41 63 63 65 70 74 3a 20  2a 2f 2a 0d 0a 43 6f 6e  |Accept: */*..Con|
00000080  74 65 6e 74 2d 54 79 70  65 3a 20 61 70 70 6c 69  |tent-Type: appli|
00000090  63 61 74 69 6f 6e 2f 78  2d 77 77 77 2d 66 6f 72  |cation/x-www-for|
000000a0  6d 2d 75 72 6c 65 6e 63  6f 64 65 64 0d 0a 43 6f  |m-urlencoded..Co|
000000b0  6e 74 65 6e 74 2d 4c 65  6e 67 74 68 3a 20 33 0d  |ntent-Length: 3.|
000000c0  0a 0d 0a 66 6f 6f 0d 0a                           |...foo..|
```

The code to add CRLF has been there for years, if not decades.
https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_http.c#L1104-L1113

According to RFC
https://tools.ietf.org/html/rfc7230#section-3.5
>  Older HTTP/1.0 user agent implementations might send an extra CRLF
>   after a POST request as a workaround for some early server
>   applications that failed to read message body content that was not
>   terminated by a line-ending.  An HTTP/1.1 user agent MUST NOT preface
>   or follow a request with an extra CRLF.  If terminating the request
>   message body with a line-ending is desired, then the user agent MUST
>   count the terminating CRLF octets as part of the message body length.
>
>   In the interest of robustness, a server that is expecting to receive
>   and parse a request-line SHOULD ignore at least one empty line (CRLF)
>   received prior to the request-line.

I assume the CRLF was implemented, when `check_http` was a http/1.0 client. However, in http/1.1 "..agent MUST NOT ..follow a request with an extra CRLF"

On the other hand, I'm not sure if the server is not _too_ strict in request validation. There are many MAYs and SHOULDs in RFC.

## curl

Here is a dump from similar request from curl.

```
curl -X POST -d foo http://localhost:8000/
```
```
00000000  50 4f 53 54 20 2f 20 48  54 54 50 2f 31 2e 31 0d  |POST / HTTP/1.1.|
00000010  0a 48 6f 73 74 3a 20 6c  6f 63 61 6c 68 6f 73 74  |.Host: localhost|
00000020  3a 38 30 30 30 0d 0a 55  73 65 72 2d 41 67 65 6e  |:8000..User-Agen|
00000030  74 3a 20 63 75 72 6c 2f  37 2e 34 33 2e 30 0d 0a  |t: curl/7.43.0..|
00000040  41 63 63 65 70 74 3a 20  2a 2f 2a 0d 0a 43 6f 6e  |Accept: */*..Con|
00000050  74 65 6e 74 2d 4c 65 6e  67 74 68 3a 20 33 0d 0a  |tent-Length: 3..|
00000060  43 6f 6e 74 65 6e 74 2d  54 79 70 65 3a 20 61 70  |Content-Type: ap|
00000070  70 6c 69 63 61 74 69 6f  6e 2f 78 2d 77 77 77 2d  |plication/x-www-|
00000080  66 6f 72 6d 2d 75 72 6c  65 6e 63 6f 64 65 64 0d  |form-urlencoded.|
00000090  0a 0d 0a 66 6f 6f                                 |...foo|
```

As you can see, there is no CRLF after "foo".

## Steps to reproduce

1. install `aiohttp` and run server

```
mkvirtualenv --python=python3.5 aiotest
pip install aiohttp
```
2. create and run server
```
cat >main.py <<EOF
import asyncio
from aiohttp import web

loop = asyncio.get_event_loop()
app = web.Application(loop=loop)
web.run_app(app, host='127.0.0.1', port=8000)
EOF
```
```
$ python main.py 
======== Running on http://127.0.0.1:8000 ========
(Press CTRL+C to quit)
```
3. run `check_http` against the server
```
/usr/lib64/nagios/plugins/check_http -H localhost -P foo -j POST -p 8000
```

### Actual behavior

```
$ /usr/lib64/nagios/plugins/check_http -H localhost -P foo -j POST -p 8000
CRITICAL - Socket timeout after 10 seconds
```
```
Error handling request
Traceback (most recent call last):
  File "/home/zarnovic/venv/aiotest/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 276, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "/home/zarnovic/venv/aiotest/lib/python3.5/site-packages/aiohttp/http_parser.py", line 115, in feed_data
    msg = self.parse_message(self._lines)
  File "/home/zarnovic/venv/aiotest/lib/python3.5/site-packages/aiohttp/http_parser.py", line 331, in parse_message
    raise BadStatusLine(line) from None
aiohttp.http_exceptions.BadStatusLine: ''
```

### Expected behavior

```
$ /usr/lib64/nagios/plugins/check_http -H localhost -P foo -j POST -p 8000
HTTP WARNING: HTTP/1.1 404 Not Found - 192 bytes in 0.006 second response time |time=0.005834s;;;0.000000 size=192B;;;0
```

**Comment by jfrickson** [comment]
We'll get it fixed for version 2.2.2. Thanks!

**Comment by ggonzalez2** [comment]
Okay, fixed.  Decision is to go with HTTP 1.1 standard, strictly, forget about old browsers that don't meet the spec.

**Comment by hedenface** [comment]
@ggonzalez2 Which commit is it fixed in?

**Comment by hedenface** [comment]
Closed via PR #298 via commit https://github.com/nagios-plugins/nagios-plugins/commit/4c378f451457ae4b5e6594008f287663dc1205a3 ala @ggonzalez2

**Comment by waja** [comment]
@ggonzalez2 which if those hundred changed lines are the two one fixing it?

**Comment by waja** [comment]
> @ggonzalez2 which if those hundred changed lines are the two one fixing it?

@ggonzalez2 any chance to get an useful answer? Looking forward, thanks.
