### ISSUE TITLE
check_mailq in centos does not works

### ISSUE THREAD

**Issue by fedex29** [nagios-plugins/nagios-plugins#268]
I try the command in local and in external on Icinga web2 and the plugin output is:

ERROR: /usr/bin/mailq is not executable by (uid 498:gid(499 498 499))

The user detailing in values is the same as icinga, such as the group.

Probe to do it with the sudo user but neither.
This only happens to me in servers with centos 6.8

**Comment by jfrickson** [comment]
What are the permissions on /usr/bin/mailq?

**Comment by fedex29** [comment]
The permissions are:

```
[root@xxxxxxxxx]# ll /usr/bin/mailq.exim
lrwxrwxrwx 1 root root 12 Mar 30 11:39 /usr/bin/mailq.exim -> ../sbin/exim
```

**Comment by jfrickson** [comment]
Ok, What are the permission on /sbin/exim?

**Comment by fedex29** [comment]
Output:
```
[root@xxxxxxxxxx]# ll /sbin/exim
ls: cannot access /sbin/exim: No such file or directory
```

I use qmHandle to check the mail queue, does this have to do with the current problem?

**Comment by jfrickson** [comment]
Most likely. Try running (changing the path as appropriate)
```
./configure --with-mailq-command=/usr/bin/qmHandle
make all
```
Then run the check and see if it works.

**Comment by fedex29** [comment]
Where do I run the command? In wich path?

It is a Centos 6.8 server that uses Plesk

**Comment by jfrickson** [comment]
You might be better off posting to the forum at https://support.nagios.com/forum/viewforum.php?f=7 and the support folks will take care of you.

You can point them to this issue for background. Good luck!
