### ISSUE TITLE
check_snmp Plugin timed out while executing system call

### ISSUE THREAD

**Issue by gtyr** [nagios-plugins/nagios-plugins#269]
When a snmpget timeout occurs while running check_snmp plugin, the plugin returns "CRITICAL - Plugin timed out while executing system call". It should be returning "External command error: Timeout: No Response from 192.168.0.1:161." as an UNKNOWN exit status

Replication:
./check_snmp -H 192.168.0.1 -C public -o sysUpTime.0 -t 1 -e 5 -vvv
/usr/bin/snmpget -Le -t 1 -r 5 -m ALL -v 1 [context] [authpriv] 192.168.0.1:161 sysUpTime.0
CRITICAL - Plugin timed out while executing system call

Plugins version 1.4.16
./check_snmp -H 192.168.0.1 -C public -o sysUpTime.0 -vvv
/bin/snmpget -t 1 -r 5 -m ALL -v 1 [authpriv] 192.168.0.1:161 sysUpTime.0
External command error: Timeout: No Response from 192.168.0.1:161.

**Comment by jfrickson** [comment]
I'll take a look. Thanks.

**Comment by hedenface** [comment]
Added for 2.2.2

**Comment by hedenface** [comment]
This isn't a bug. It was a change.

You can adjust how it exits simply by adjusting your timeout setting.

Use the following:

```
./check_snmp -H 192.168.0.1 -C public -o sysUpTime.0 -t 1:3 -e 5 -vvv
```

or

```
./check_snmp -H 192.168.0.1 -C public -o sysUpTime.0 -t 1:UNKNOWN -e 5 -vvv
```
