### ISSUE TITLE
check_radius_adv mangling password

### ISSUE THREAD

**Issue by cdienger** [nagios-plugins/nagios-plugins#271]
NagiosXI version: 5.4.2
Linux version: Red Hat Enterprise Linux Server release 6.8 (Santiago) x64 VM

10.0.0.2 is the radius server, 10.0.0.3 is the nagiosxi server

$ ./check_radius_adv -r 10.0.0.2 -u nagios -s nagios -p nagios
CRITICAL: Access REJECT. (code = 3) | rtt=0.0055 rttms=5.4579 

Radius log:

Thu Apr 13 12:40:01 2017: 10.0.0.2 process=radiusd user=nagios realm= action=failure NAS_IP_Address= Uppercased_Tunnel= Calling_Station_Id= NAS_Port= clear-text-password=`???e?!?gy?????

Test with other radius tools work:

radpwtst -user nagios -password nagios -s 10.0.0.2 -secret nagios -auth_port 1812 -noacct

Radius log: 

Thu Apr 13 12:42:11 2017: 10.0.0.2 process=radiusd user=nagios realm= action=success NAS_IP_Address=10.0.0.3 Uppercased_Tunnel= Calling_Station_Id=987654321 NAS_Port=1234 clear-text-password=nagios

Appears to be a known issue with 64 bit machines:
https://support.nagios.com/forum/viewtopic.php?f=6&t=35305

**Comment by jfrickson** [comment]
`check_radius_adv` is not owned by us. I'm checking if we want to take ownership. If not, there's nothing I can do.

**Comment by SundanceRaphael** [comment]
Dir Mr. Frickson,

I got NagiosXi  out of the box with  check_radius_adv support. 
In the [in the forum entry  ‎from above ](https://support.nagios.com/forum/viewtopic.php?f=6&t=35305) is a  [replacement](https://exchange.nagios.org/directory/Plugins/Network-Protocols/RADIUS/Perl-check-radius/details ) is suggested to use. 

Some documentations speaks of a check_radius that should be there but there Maybe [this](https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_radius.) ?
But can't find it in installed source. 

Is it possible to put a known running plugin to the default install? Or at least remove the plugin from default install? It is very confusing to get a broken plugin from default.

Best regards
Sundance Raphael

//System
Nagios XI Version : 5.4.5
CentOS release 6.9 (Final)
Gnome is not installed

**Comment by hedenface** [comment]
@SundanceRaphael What John was saying is that **we** as in **this repository** are not the owners of that plugin. This all needs to be taken care of on the Nagios XI side of things. I'll filed an internal bug report regarding your situation (#12044), and we'll investigate it further in-house. In the meantime, you may want to post on the [Nagios Support Forum](https://support.nagios.com/forum/) as that is the proper place for all of the Enterprise products' support. Thanks!
