### ISSUE TITLE
check_http: OCSP revokation checking

### ISSUE THREAD

**Issue by ponchofiesta** [nagios-plugins/nagios-plugins#273]
I just had the problem, that a HTTPS certificate was accidentally revoked. Users were unable to view the website in the browser. But `check_http -S [...]` did not trigger on this fault. 

Support for OCSP checking would be great.

**Comment by jfrickson** [comment]
Checking for cert revocation should certainly be done! We'll get that implemented.

**Comment by hedenface** [comment]
We'll get this talked and approved about internally. Good idea!

**Comment by sawolf** [comment]
This was just added to `maint` as part of `check_ssl_validity.pl` - closing.

**Comment by ponchofiesta** [comment]
There are already plugins to check certificates separately. I think check_http should do this by default as this is the expected behavior like a web browser would do it too.
