### ISSUE TITLE
NRPE HPUX Disk check 

### ISSUE THREAD

**Issue by benhank** [nagios-plugins/nagios-plugins#276]
The NRPE disk checks do not display which mount point is critical.:
`https://support.nagios.com/forum/viewtopic.php?f=16&t=43826&p=220823#p220823`
Can Nagios indicate which mount point is in a warning/critical state, or just display the mount points that have issues?

**Comment by jfrickson** [comment]
Seems like a good idea. I'll look into it. Thanks!

**Comment by benhank** [comment]
Thank you thank you thank you!

**Comment by benhank** [comment]
I've never submitted an enhancement request before, so I am sorry if my question is a bad one. Is there any word on whether this is doable?

**Comment by jfrickson** [comment]
It's probably doable. I won't get to it for a while, though. Maybe a couple of weeks.

**Comment by benhank** [comment]
thanks man! This will make a HUGE benefit for my team!

**Comment by jfrickson** [comment]
Fixed via commit https://github.com/nagios-plugins/nagios-plugins/commit/a29a221f57622eac25bc71136bccce7bf59ebe88

If `-s` is added to the command-line, the status will be printed immediately before each path or partition. For example:
```
./check_disk -w 50% -c 20% -p / -p /home -p /tmp -n -s
DISK WARNING - free space:
W:/ 13844 MB (37.27% inode=77%);
O:/home 2465 MB (99.99% inode=100%);
O:/tmp 2477 MB (99.90% inode=100%);
| /=23294MB;19083;30532;0;38166 /home=0MB;1232;1972;0;2465 /tmp=2MB;1239;1983;0;2479
```

**Comment by benhank** [comment]
THANKS MAN!
