### ISSUE TITLE
check_http: Breaking change to -C: Certificate check should not check URL.

### ISSUE THREAD

**Issue by tomsommer** [nagios-plugins/nagios-plugins#280]
Regarding PR #201

This change makes no sense, `-C` is suppose to only check the certificate validity and expiration, but now it also checks the HTTP response?

From the docs: `(when this option is used the URL is not checked.)` which is not true anymore. 
I don't care if the URL works or not, I just want to make sure the certificate is valid, how do I do this now?

**Comment by jfrickson** [comment]
I had not noticed that in the docs, sorry. I'll do something about it.

**Comment by hedenface** [comment]
Added to the 2.2.2 release as bugfix.

**Comment by bluikko** [comment]
Duplicate at #299 .

**Comment by feld** [comment]
Just hit this on an upgrade. Would appreciate 2.2.2 release to fix this instead of having to custom patch this in the FreeBSD ports tree

**Comment by hedenface** [comment]
My attention will move from core, nrpe, and ndo to plugins this week. I can't give a time - but I don't think having a 2.2.2 release out within the next few weeks would be too hard.

**Comment by hedenface** [comment]
https://github.com/nagios-plugins/nagios-plugins/commit/80ec842a8942fb8c1d10cf68d3e34fe865e081ba
