### ISSUE TITLE
check_ntp_time behaving strange

### ISSUE THREAD

**Issue by ParthKolekar** [nagios-plugins/nagios-plugins#281]
$ check_ntp_time -H <TIME SERVER> -vvv

Found 1 peers to check
sending request to peer 0
response from peer 0: packet contents:
	flags: 0xe4
	  li=3 (0xc0)
	  vn=4 (0x20)
	  mode=4 (0x04)
	stratum = 3
	poll = 16
	precision = 1.19209e-07
	rtdelay = 0.1376800537109375
	rtdisp = 0.207977294921875
	refid = 4a203b8b
	refts = 1495089923.397519
	origts = 1495089956.364315
	rxts = 1495089956.545167
	txts = 1495089956.545308
offset 0.1807864904
sending request to peer 0
response from peer 0: packet contents:
	flags: 0xe4
	  li=3 (0xc0)
	  vn=4 (0x20)
	  mode=4 (0x04)
	stratum = 3
	poll = 16
	precision = 1.19209e-07
	rtdelay = 0.1376800537109375
	rtdisp = 0.207977294921875
	refid = 4a203b8b
	refts = 1495089923.397519
	origts = 1495089956.364673
	rxts = 1495089956.545527
	txts = 1495089956.545627
offset 0.1808004379
sending request to peer 0
response from peer 0: packet contents:
	flags: 0xe4
	  li=3 (0xc0)
	  vn=4 (0x20)
	  mode=4 (0x04)
	stratum = 3
	poll = 16
	precision = 1.19209e-07
	rtdelay = 0.1376800537109375
	rtdisp = 0.207977294921875
	refid = 4a203b8b
	refts = 1495089923.397519
	origts = 1495089956.364933
	rxts = 1495089956.545784
	txts = 1495089956.5459
offset 0.1807999611
sending request to peer 0
response from peer 0: packet contents:
	flags: 0xe4
	  li=3 (0xc0)
	  vn=4 (0x20)
	  mode=4 (0x04)
	stratum = 3
	poll = 16
	precision = 1.19209e-07
	rtdelay = 0.1376800537109375
	rtdisp = 0.207977294921875
	refid = 4a203b8b
	refts = 1495089923.397519
	origts = 1495089956.365203
	rxts = 1495089956.546055
	txts = 1495089956.546191
offset 0.180798769
discarding peer 0: flags=3
no peers meeting synchronization criteria :(
overall average offset: 0
NTP CRITICAL: Offset unknown|

I see that my host has LI_ALARM set because of which it is unwilling to sync with the host. Anything I can do to prevent it?

$ check_ntp_time -V
check_ntp_time v2.1.4 (nagios-plugins 2.1.4)

**Comment by jfrickson** [comment]
I think LI_ALARM means the server doesn't think it is correctly sync'd. If that happens only occasionally, try setting `first_notification_delay` to some value so notifications won't go out until it happens twice in a row.

**Comment by ParthKolekar** [comment]
Thanks for the suggestion.
