### ISSUE TITLE
check_dhcp: output request

### ISSUE THREAD

**Issue by pauljobb** [nagios-plugins/nagios-plugins#282]
I am using the check_dhcp plugin as follows

./check_dhcp -i ens224 -s 111.222.333.444 -s 555.666.777.888

when offers aren't received would it be possible to include the addresses of the servers in the output? currently it just returns the following

WARNING: Received 1 DHCPOFFER(s), only 1 of 2 requested servers responded, max lease time = 1800 sec.

**Comment by hedenface** [comment]
Can you provide an example of the output you think it should look like?

**Comment by pauljobb** [comment]
Thanks;

I guess if using the –s option if you could provide the address of the servers that did not respond i.e.:

WARNING: Received 1 DHCPOFFER(s), only 1 of 2 requested servers responded, max lease time = 1800 sec.
x.x.x.x did not respond.

**Comment by hedenface** [comment]
Fixed in https://github.com/nagios-plugins/nagios-plugins/pull/392
