### ISSUE TITLE
check_http: -N parameter causes false timeouts (version 2.2.1)

### ISSUE THREAD

**Issue by heaje** [nagios-plugins/nagios-plugins#283]
I could not find the bug report for the issue mentioned in https://support.nagios.com/forum/viewtopic.php?f=35&t=43799&sid=25dcb5aed7c89f17dc5037e681d873e9, so I figured I'd create it.

As described in that forum post, check_http returns timeouts when I use the "-N" parameter.  For instance, if I run this command below in 2.1.4 I get a HTTP 200 as expected:
```/home/nagios/libexec/check_http -p 443 -S -t 30 -N  -H my.host.ip```

If I run that exact same command in 2.2.1, I get a socket timeout after 30 seconds (per -t 30).  If I remove the "-N" in 2.2.1, I get the HTTP 200 that I expect.

**Comment by Jonnycake** [comment]
I ran into this issue as well, I have submitted a pull request with the fix. https://github.com/nagios-plugins/nagios-plugins/pull/289

**Comment by neingeist** [comment]
Ran in this as well.

**Comment by cobaugh** [comment]
I have several sites which only worked with -N (would result in socket timeouts while waiting for the body). They are now getting socket timeouts even with -N after the update to 2.2.1:
```
$ /usr/lib64/nagios/plugins/check_http -I myhost.com -S -u '/index.html' -v -N
SSL initialized
GET /index.html HTTP/1.0
User-Agent: check_http/v2.2.1 (nagios-plugins 2.2.1)
Connection: close
Accept: */*


https://myhost.com:443/index.html is 1186 characters
STATUS: HTTP/1.1 200 OK
CRITICAL - Socket timeout
```

**Comment by kovyrin** [comment]
Happening for us as well

**Comment by hedenface** [comment]
Resolved in #289 - Thanks @Jonnycake

**Comment by neingeist** [comment]
will there be a release with this bug fixed soon?

**Comment by hedenface** [comment]
It's on the priority list for after the Core 4.4 release.

**Comment by thegushi** [comment]
A year and a half later, could this please be pushed out?

**Comment by Madlohe** [comment]
Hi @thegushi,

There are a few other things we still want to resolve for the next nagios-plugins release. Our current goal is to have those done in 3-4 weeks. If for some reason we don't meet that target, I would expect another release to occur anyways by end of summer.
