### ISSUE TITLE
 Feature Request: option to disable perfdata

### ISSUE THREAD

**Issue by Tomszy** [nagios-plugins/nagios-plugins#285]
Dear Team,

We are using nagios-plugins with NRPE agent and we have many checks with check_disk plugin, but we dont need the perfdata from these checks and we would like to reduce the performance data, because we have more than 200 thousands checks in nagios(centreon) and the broker cannot handle sometimes the too much perfdata.

 Can you put an option to disable perfdata into check_disk plugin and after into the others plugins as well?

Thanks,

Tamas

**Comment by box293** [comment]
On those host and service definitions you can use the process_perf_data directive to disable it. I am unsure if centreon has this option however this is how it can be done in Nagios.

```
process_perf_data       0
```

**Comment by hedenface** [comment]
I like the idea of a flag to void the printing of perfdata, but I think a much easier solution would be to create a plugin that stripped the perfdata that would run on top. Something like:

    ./check_remove_perfdata /usr/local/nagios/libexec/check_disk -x /dev/sda

Where the output would look something like:

    DISK OK - free space: /dev 979 MB (100.00% inode=100%); /run 178 MB (89.40% inode=100%); / 4859 MB (25.71% inode=70%)

As opposed to:

    DISK OK - free space: /dev 979 MB (100.00% inode=100%); /run 178 MB (89.40% inode=100%); / 4859 MB (25.71% inode=70%) | /dev=0MB;;;0;979 /run=21MB;;;0;200 /=14041MB;;;0;19935

Any ideas or suggestions are welcome.

**Comment by hedenface** [comment]
Just as an update - I'm going to go with the `./check_remove_perfdata` option. It doesn't make sense (to me) to add it in as separate options to individual plugins, or even in the utils/base functionality.

**Comment by hedenface** [comment]
Added: a27bf2884ab3b2ec78776ad1efc5950296c2edbd
And makefile: 7a64eaefbf5eb54b41b0c920597499b4b30327a2

Won't be officially available until 2.3.0 - but you can use it now if you'd like :)
