### ISSUE TITLE
DISK UNKNOWN: Must set a threshold value before using -r/-R problem

### ISSUE THREAD

**Issue by DerPyro** [nagios-plugins/nagios-plugins#286]
Hello, i cant check_disk my Raspi. 
I have the problem that the check skips gvfs because it has the wrong permissions.
Can i skip only that one?
I tried it like this, but with returning an error: 

apply Service "disk" {
  import "generic-service"
  check_command = "by_ssh"

  vars.disk_w = 3 //3Parameter?
  vars.disk_c = 5 //5Parameter?
  vars.by_ssh_command = [PluginDir + "/check_disk"]
  vars.by_ssh_arguments = {
  "-w" = "$disk_w$"
  "-c" = "$disk_c$"
  "-i" = "/run/user/1000/gvfs"
  "-R" = ".*"
  }
  assign where match("true",host.vars.sshclient)
}

**Comment by hedenface** [comment]
Switch the order of the `-R` and the `-i` flag. That should resolve your issue.

**Comment by DerPyro** [comment]
Thanks for your answer, but I found yesterday an other solution:

apply Service "disk" {
  import "generic-service"
  check_command = "by_ssh"

  vars.by_ssh_command = [PluginDir + "/check_disk"]
  vars.by_ssh_arguments = {
    "-w" = {
      value = "10%",
      order = 0
    }
    "-c" = {
      value = "5%",
      order = 1
    }
    "-r" = {
      value = "$disk_paths$",
      order = 2
    }
  }
  assign where match("true",host.vars.sshclient)
}
