### ISSUE TITLE
check_snmp returns OK for missing OID

### ISSUE THREAD

**Issue by feld** [nagios-plugins/nagios-plugins#287]
If you request checking of a specific OID which is not implemented the check returns OK instead of CRITICAL.

    SNMP OK - No Such Instance currently exists at this OID

**Comment by hedenface** [comment]
I'm going to assign the label of bug until I can get in and take a look at it. Thanks!

**Comment by hedenface** [comment]
This is not the current functionality. Not sure what version you're using, but when I run a good case (against a Synology NAS):

```
$ ./check_snmp -H 192.168.1.1 -C public -o 1.3.6.1.4.1.2021.10.1.5.1 -l "Load1" -w 400 -c 500
SNMP CRITICAL - Load1 *2662* | Load1=2662;400;500; 
```

and when I run a bad OID against it:
```
$ ./check_snmp -H 192.168.1.1 -C public -o 1.3.6.1.4.1.2021.10.4.5.1 -l "Load1" -w 400 -c 500
External command error: Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: iso.3.6.1.4.1.2021.10.4.5.1

$ echo $?
3
```
