### ISSUE TITLE
check_snmp: better to have min/max values in the performance data "undefined" by default

### ISSUE THREAD

**Issue by Tontonitch** [nagios-plugins/nagios-plugins#292]
```
[root@xxxxxxxxx ~]# /usr/lib64/nagios/plugins/check_snmp -V
check_snmp v2.1.4 (nagios-plugins 2.1.4)
[root@xxxxxxxxx ~]#
```
Concerning the min/max values in the performance data, currently the default value seems to be 0.
```
SNMP RATE CRITICAL - *0.009795797207* *2.264746262* | MCAFEE-MWG-MIB::stConnectionsBlocked.0=0.009795797207;1:;10:;0;0; MCAFEE-MWG-MIB::stConnectionsLegitimate.0=2.264746262;100:;1000:;0;0;
```
it would be better to have them "undefined".
```
SNMP RATE CRITICAL - *0.009795797207* *2.264746262* | MCAFEE-MWG-MIB::stConnectionsBlocked.0=0.009795797207;1:;10:;;; MCAFEE-MWG-MIB::stConnectionsLegitimate.0=2.264746262;100:;1000:;;;
```

**Comment by hedenface** [comment]
How are you processing your perfdata? And I'd like to understand why "it would be better to have them 'undefined'"?

I don't disagree, I guess I just don't really understand. Thanks!

**Comment by Tontonitch** [comment]
For exemple, when perfdata are processed by pnp, min and max values are usually / could be used to:
 * set --upper-limit and --lower-limit values for the (rrd) graph generation
 * print a line with the max value for the (rrd) graph generation (usually a black line showing the max limit on the graph)

Having min and max to 0 could lead to some problems with the graph generation.

**Comment by hedenface** [comment]
Okay, fair enough. According to the guidelines:

> 8. value, min and max in class [-0-9.]. Must all be the same UOM. value may be a literal "U" instead, this would indicate that the actual value couldn't be determined

So what is actually undefined? I would think it would be a `U` instead of a blank section e.g.: `;;`. Thoughts?

**Comment by Tontonitch** [comment]
I have never seen the litteral "U" as min/max in perfdata. So, that's not something used commonly.

I always see empty values like:
```
MCAFEE-MWG-MIB::stConnectionsLegitimate.0=2.264746262;100:;1000:;;
```
or a short way (omitting completely the min/max) fields:
```
MCAFEE-MWG-MIB::stConnectionsLegitimate.0=2.264746262;100:;1000:
```

But going back to the guidelines:
> 'label'=value[UOM];[warn];[crit];[min];[max]

So it means that the min/max information are optional and may be null/empty.

So I would go to 
```
MCAFEE-MWG-MIB::stConnectionsLegitimate.0=2.264746262;100:;1000:;;
```

**Comment by hedenface** [comment]
I agree that that is what is most commonly seen, but it isn't what the spec says it should be :) Although there likely isn't a difference in the spec between having nothing and a `U`.

Regardless, I am a **lazy**, ***lazy*** man. I'll update it with blank values for the next bug fix.

**Comment by sni** [comment]
Unknown 'U' is only valid for the value, not for warn;crit;min;max

**Comment by Tontonitch** [comment]
Ok, great. Thanks ! :thumbsup:

**Comment by hedenface** [comment]
@sni I see where it says "***value*** may be a literal U instead"  - I was originally thinking it meant the value of the warn/crit/min/max not the actual value of the perfdata. I'll formally retract that thought/statement.

**Comment by hedenface** [comment]
This is actually been fixed. Noticed it while working on #293
