### ISSUE TITLE
check_snmp: unexpected extra extra ";" in there performance data

### ISSUE THREAD

**Issue by Tontonitch** [nagios-plugins/nagios-plugins#293]
```
[root@xxxxxxxxx ~]# /usr/lib64/nagios/plugins/check_snmp -V
check_snmp v2.1.4 (nagios-plugins 2.1.4)
[root@xxxxxxxxx ~]#
```

It seems that the performance data output doesn't follow the plugin development guidelines (https://nagios-plugins.org/doc/guidelines.html):

> 'label'=value[UOM];[warn];[crit];[min];[max]

So, currently there is one extra ";". 
```
SNMP RATE CRITICAL - *0.009795797207* *2.264746262* | MCAFEE-MWG-MIB::stConnectionsBlocked.0=0.009795797207;1:,100:;10:,1000:;0;0; MCAFEE-MWG-MIB::stConnectionsLegitimate.0=2.264746262;1:,100:;10:,1000:;0;0;
```

I would expect:
```
SNMP RATE CRITICAL - *0.009795797207* *2.264746262* | MCAFEE-MWG-MIB::stConnectionsBlocked.0=0.009795797207;1:;10:;0;0 MCAFEE-MWG-MIB::stConnectionsLegitimate.0=2.264746262;100:;1000:;0;0
```

**Comment by hedenface** [comment]
> 6. warn, crit, min or max may be null (for example, if the threshold is not defined or min and max do not apply). Trailing unfilled semicolons can be dropped

**Comment by hedenface** [comment]
Hmm. I had closed it preemptively I think. Okay. I'll identify this as a bug and get it fixed.

**Comment by hedenface** [comment]
Fixed: https://github.com/nagios-plugins/nagios-plugins/commit/0861cc1a2ea53d955e6d4d2463d95f14ea8b528e
