### ISSUE TITLE
check_snmp: change path where calculation files are generated when using --rate option

### ISSUE THREAD

**Issue by Tontonitch** [nagios-plugins/nagios-plugins#294]
When using the --rate option, the check_snmp plugin tries to create temporary calculation files in /var/. For exemple /var/993/check_snmp. Obviously, the user launching the check_snmp plugin is not allowed to create directories in /var.
Changing that temporary directory to /var/tmp instead of /var would avoid any directory creation issue.

Making this directory configurable via a plugin option would be even better, but at least the change above would be enough.

BR,
Yannick

**Comment by hedenface** [comment]
You can actually set the environment variable `NAGIOS_PLUGIN_STATE_DIRECTORY` before using the plugin to override this. Example:

```
NAGIOS_PLUGIN_STATE_DIRECTORY=/var/tmp ./check_snmp -H 192.168.1.1 -C public -o 1.3.6.1.4.1.2021.10.1.5.1 -l "oid" --rate
```
