### ISSUE TITLE
check_http: -C broken after update to 2.2.1

### ISSUE THREAD

**Issue by bluikko** [nagios-plugins/nagios-plugins#299]
From the manual of check_http:
" -C, --certificate=INTEGER[,INTEGER]
        Minimum number of days a certificate has to be valid. Port defaults to 443
        (when this option is used the URL is not checked.)"

After updating nagios-plugins to 2.2.1, check_http *does* check the URL even when -C switch is in use.

All the previously working checks that were supposed to just check certificate validity time now fail because of 403 Forbidden and similar errors when check_http additionally (and unexpectedly) now also checks the URL.

**Comment by bluikko** [comment]
After looking at check_http.c history, the bug was introduced in a sloppy "bugfix" in commit 155599c532cc19940b9263bf0b1033ba8d215758

As per the manual and how -C option should work, the connection must be closed regardless of "result" on line 1027. It looks like someone "fixed" this "bug" and did not know that -C option *is supposed to* close the connection after checking the certificate.

I suggest to rollback the whole commit since the behavior this commit tries to "fix" is not a bug but works as documented.

**Comment by hedenface** [comment]
It would be nice to rollback those particular changes, but keep the "fix" - where success isn't mentioned prematurely when checking the certificate. I'll get around to this, but I don't have a time frame. If you were able to fix it up and submit a PR, it would be merged an awful lot faster.

Thank you for the catch! :)

**Comment by cpfair** [comment]
As an alternative, it would be possible to restore the old behaviour but add a warning when additional check parameters are specified alongside -C. Even if it's documented, that doesn't mean people (like me, clearly) will actually read those docs closely enough to see that -C's behaviour is inconsistent with the bulk of check_http's options. The warning would (for the most part) eliminate the pitfall that prompted my initial PR, while maintaining identical behaviour for people who did fully understand -C's behavioris and did not specify any further check parameters knowing that they would be silently ignored.

**Comment by bluikko** [comment]
The only way I see is to restore the old behavior of -C. You can always make another check to test if the actual URL can be reached - by making another check without -C. But if -C always checks the URL, there is no way to test only the certificate in a case where the URL returns a 401 or 403 for example.

@cpfair -C combined with which parameters?

@hedenface I do not follow what you mean with the "fix". The check worked as intended and documented in the man page, there was nothing premature on the old behavior.

**Comment by cpfair** [comment]
-C combined with any parameters that will be silently ignored by its inclusion. And, I think you can use check_tcp -D to check only the TLS cert - but obviously that ship sailed as soon as people began to use check_http -C in its original form.

**Comment by bluikko** [comment]
@cpfair You are correct and check_tcp has the same functionality. I've updated my checks to use it. Perhaps if this change to -C is properly documented in release notes (and the man page patched) other users can do the same change.

**Comment by gerwim** [comment]
Yes, same issue here. Instead of reporting the following: 
`OK - Certificate 'domain' will expire on 2017-09-29 23:03 +0200/CEST.`, it was returning: 
`SSL OK - Certificate 'domain' will expire on 2017-09-29 23:03 +0200/CEST. HTTP WARNING: HTTP/1.1 403 Forbidden - 5199 bytes in 0,178 second response time |time=0,177591s;;;0,000000 size=5199B;;;0`.

Downgrading `nagios-plugins*` from 2.2.1-1.el7 to 2.1.4-2.el7 fixed the issue for me.

**Comment by hedenface** [comment]
Fixed: https://github.com/nagios-plugins/nagios-plugins/commit/80ec842a8942fb8c1d10cf68d3e34fe865e081ba
