### ISSUE TITLE
check_sensors RHEL 6  problem

### ISSUE THREAD

**Issue by smooge** [nagios-plugins/nagios-plugins#300]
I have gotten a couple of reports of check_sensors not working with some EL6 systems. The problem looks to be in this code:

    # diff my_check_sensors check_sensors
    56,57c56,58
    <               elif echo "${sensordata}" | egrep -q FAULT  > /dev/null ; then
    <                         if test "$1" != "-i" -a "$1" != "--ignore-fault" ; then
    ---
                  elif echo "${sensordata}" | egrep -q FAULT  > /dev/null -a; then
                          if [ "$(test "$1")" != "-i" -a \
                                  "$1" != "--ignore-fault" ] ; then
    70c71
    <               exit $exit
    ---
                  exit "$exit"
    
     The original sensor command output:

    ---

    # sensors
    fschds-i2c-6-73
    Adapter: SMBus I801 adapter at 1c00
    in0:        +11.93 V
    in1:         +5.04 V
    in2:         +3.04 V
    fan1:       1080 RPM  (div = 4)
    fan2:        780 RPM  (div = 4)
    fan3:        780 RPM  (div = 4)
    fan4:          FAULT  (div = 4)
    fan5:          FAULT  (div = 4)
    temp1:       +20.0°C  (high = +68.0°C)
    temp2:       +34.0°C  (high = +59.0°C)
    temp3:       +27.0°C  (high = +52.0°C)
    temp4:       +20.0°C  (high = +68.0°C)
    temp5:       +27.0°C  (high = +62.0°C)

    coretemp-isa-0000
    Adapter: ISA adapter
    Core 0:      +40.0°C  (high = +78.0°C, crit = +100.0°C)
    Core 1:      +40.0°C  (high = +78.0°C, crit = +100.0°C)

    ---

    Trying to ignore the FAULT part doesn't work in the original script, where I get

    # ./check_sensors
    SENSOR UNKNOWN - Sensor reported fault

    OK, but then

    # ./check_sensors -i
    SENSOR UNKNOWN - Sensor reported fault

Changing the code back to the other version 'fixes' it for them.

**Comment by smooge** [comment]
[nag-check_sensors.txt](https://github.com/nagios-plugins/nagios-plugins/files/1120687/nag-check_sensors.txt)

**Comment by hedenface** [comment]
Thanks @smooge. We'll get it taken care of!

**Comment by hedenface** [comment]
Fixed: https://github.com/nagios-plugins/nagios-plugins/commit/677904a6dd3853ab4a86396ff459d83b3d14dffa
