### ISSUE TITLE
check_http --no-body not working in 2.2.1

### ISSUE THREAD

**Issue by yesthatjwz** [nagios-plugins/nagios-plugins#301]
Symptom: it correctly skips reading the body, but then it goes into a loop and eventually times out. This seems to fix it:

```
--- check_http.c.~1~	2017-04-19 09:03:12.000000000 -0700
+++ check_http.c	2017-07-03 15:51:06.000000000 -0700
@@ -1206,7 +1206,8 @@
   /* find header info and null-terminate it */
   header = page;
 	for (;;) {
-		if (!strncmp(page, "\r\n\r\n", 4) || !strncmp(page, "\n\n", 2))
+		if (!strncmp(page, "\r\n\r\n", 4) || !strncmp(page, "\n\n", 2)
+                    || !*page)
 		 break;
 		while (*page == '\r' || *page == '\n') { ++page; }
     page += (size_t) strcspn (page, "\r\n");
```

**Comment by yesthatjwz** [comment]
Oops, I guess the patch got mangled in the comment. Anyway change line 1209 where it is trying to find \n\n to also match null.

**Comment by hedenface** [comment]
Thanks for the patch. I'll be digging into check_http pretty heavy soon, as there is quite a lot of attention around it.

**Comment by hedenface** [comment]
I think this was actually already fixed with some other recent changes made today in check_http, but it wasn't a bad idea for that check anyway. So I changed it a bit and added it here:

https://github.com/nagios-plugins/nagios-plugins/commit/16e255c9a8c7eb1f57cfc0439bf8062b3d9a4774

Thanks!
