### ISSUE TITLE
(how to) Add support for SMBv2 and newer to check_disk_smb

### ISSUE THREAD

**Issue by Penniman** [nagios-plugins/nagios-plugins#306]
The check_disk_smb plugin relies upon the smbclient utility which utilizes the SMBv1 protocol by default.  I have been systematically disabling SMBv1 on all of our machines which then caused havoc with these checks.  smbclient can be told to use newer SMB protocols via the -m maxprotocol argument but the current out-of-the-box check_disk_smb plugin does not.

So, would you like to fix check_disk_smb so that it too can support other SMB protocols?  Apply this diff patch:

```
25c25
< use vars qw($opt_P $opt_V $opt_h $opt_m $opt_H $opt_s $opt_W $opt_u $opt_p $opt_w $opt_c $opt_a $verbose);
---
> use vars qw($opt_P $opt_V $opt_h $opt_H $opt_s $opt_W $opt_u $opt_p $opt_w $opt_c $opt_a $verbose);
47d46
<        "m=s" => \$opt_m, "maxprotocol=s"  => \$opt_m,
85,87d83
< defined($opt_m) || ($opt_m = shift @ARGV) || ($opt_m = "");
< my $maxprotocol = $1 if ($opt_m =~ /(.*)/);
<
193d188
<       defined($maxprotocol) ? ("-m", $maxprotocol) : (),
```
With those changes in place the check_disk_smb plugin mimics the smblcient -m argument:

  `./check_disk_smb -H mySrvr2012R2Host -s someShare -m SMB3`
  `./check_disk_smb -H mySrvr2008Host -s someShare -m SMB2`

I don't have git available on my current machine so perhaps somebody else could check this change into the repo?

**Comment by hedenface** [comment]
Thanks! Pushed to `maint` https://github.com/nagios-plugins/nagios-plugins/commit/a34d87291db341535231702ffceb9052281f1dfe

**Comment by noonedeadpunk** [comment]
Could you please add description of this flag to the script help? It would be great to refer to the -h flag instead of looking through the source code or visiting this case.
