### ISSUE TITLE
check_disk fails with -C

### ISSUE THREAD

**Issue by peteeckel** [nagios-plugins/nagios-plugins#313]
check_disk in the latest EPEL release 2.2.1-4git (not sure which commit this relates to) fails with the -C/--clear option on CentOS 7:

    [root@master1 ~]# /usr/lib64/nagios/plugins/check_disk -V
    check_disk v2.2.1 (nagios-plugins 2.2.1)

    [root@master1 ~]# yum list installed | grep nagios-plugins-disk
    nagios-plugins-disk.x86_64     2.2.1-4git.el7          @stlg-epel-test          
    nagios-plugins-disk_smb.x86_64 2.2.1-4git.el7          @stlg-epel-test          

    [root@master1 ~]# /usr/lib64/nagios/plugins/check_disk -C
    DISK CRITICAL -  is not accessible: No such file or directory

The previous version 2.2.1-1 was OK:

    [root@master1 ~]# /usr/lib64/nagios/plugins/check_disk -V
    check_disk v2.2.1 (nagios-plugins 2.2.1)

    [root@master1 ~]# yum list installed | grep nagios-plugins-disk
    nagios-plugins-disk.x86_64     2.2.1-1.el7             @stlg-epel-test          
    nagios-plugins-disk_smb.x86_64 2.2.1-1.el7             @stlg-epel-test
          
    [root@master1 ~]# /usr/lib64/nagios/plugins/check_disk -C
    DISK OK - free space: / 28202 MB (74.48% inode=100%); /dev 1413 MB (100.00% inode=100%); /dev/shm 1423 MB (99.99% inode=100%); /run 1279 MB (89.86% inode=100%); /sys/fs/cgroup 1423 MB (100.00% inode=100%); /boot 875 MB (86.37% inode=100%); /vagrant 88040 MB (9.24% inode=100%); /run/user/1000 284 MB (100.00% inode=100%);| /=9658MB;;;0;37861 /dev=0MB;;;0;1413 /dev/shm=0MB;;;0;1423 /run=144MB;;;0;1423 /sys/fs/cgroup=0MB;;;0;1423 /boot=138MB;;;0;1014 /vagrant=864673MB;;;0;952713 /run/user/1000=0MB;;;0;284

OS version is CentOS 7/x86_64.

**Comment by peteeckel** [comment]
I just tried something and to my surprise it worked:

    [root@master1 ~]# /usr/lib64/nagios/plugins/check_disk -C 
    DISK CRITICAL - MESSAGES/nagios-plugins.mo is not accessible: No such file or directory

    [root@master1 ~]# /usr/lib64/nagios/plugins/check_disk -C /tmp/saved_stat 
    DISK OK - free space: / 35953 MB (94.96% inode=100%); /dev 485 MB (100.00% inode=100%); /dev/shm 496 MB (100.00% inode=100%); /run 446 MB (89.93% inode=100%); /sys/fs/cgroup 496 MB (100.00% inode=100%); /boot 875 MB (86.37% inode=100%); /vagrant 88016 MB (9.23% inode=100%); /data/repos 88016 MB (9.23% inode=100%); /data/mirrors 88016 MB (9.23% inode=100%); /run/user/1000 99 MB (100.00% inode=100%);| /=1908MB;;;0;37861 /dev=0MB;;;0;485 /dev/shm=0MB;;;0;496 /run=49MB;;;0;496 /sys/fs/cgroup=0MB;;;0;496 /boot=138MB;;;0;1014 /vagrant=864697MB;;;0;952713 /data/repos=864697MB;;;0;952713 /data/mirrors=864697MB;;;0;952713 /run/user/1000=0MB;;;0;99

So it seems that there is a problem with parsing the -C/--clear option, which no longer seems to be interpreted as a boolean option but as requiring a file name.

**Comment by scottwilkerson** [comment]
As this worked in 2.2.1-1 and didn't in 2.2.1-4git it is a problem with the packaging in EPEL as the code would not have changed.

Bugzilla report filed
https://bugzilla.redhat.com/show_bug.cgi?id=1484963

Closing issue on Github
