### ISSUE TITLE
check_http does not return number of days remaining for current certificate to expire

### ISSUE THREAD

**Issue by vikaskarandikar** [nagios-plugins/nagios-plugins#315]
If today's date is less than current certificate expiry date - WARNING days then OK message is returned. OK message does not contain number of days remaining for current certificate to expire.
e.g.
OK - Certificate &apos;x.y.com&apos; will expire on Mon 18 Sep 2017 08:47:00 PM PDT.

Instead change OK message to include number of days prior to expiration.
OK - Certificate &apos;x.ycom&apos; expires in 60 day(s) Mon 18 Nov 2017 08:47:00 PM PDT.

Thanks

**Comment by mcapra** [comment]
If this isn't approved, I believe it's a relatively small change that could be done by hand:
https://github.com/nagios-plugins/nagios-plugins/blob/6c544e5d5ae8f2d829c31b6594f4d9e52f96e9f6/plugins/sslutils.c#L307

`printf(_("OK - Certificate '%s' will expire in %u days on %s. "), cn, days_left, timestamp);`

**Comment by hedenface** [comment]
Thanks Matt! I'll add it in right meow.

**Comment by hedenface** [comment]
Approved and Added: 5c7eb5b9d5a7ed20ce27dcd81f23ecdb6720c2d6
