### ISSUE TITLE
check_proc ELAPSED time not OK

### ISSUE THREAD

**Issue by purplegrape** [nagios-plugins/nagios-plugins#318]
I wanna check if my nodejs process had been restart .

warning if <30 minutes
critical if < 60 minutes

./check_procs -w 1:1800 -c 1800:3600 --metric=ELAPSED -u nobody -C node

but result is always not OK

./check_procs -V
check_procs v2.2.1 (nagios-plugins 2.2.1)

**Comment by hedenface** [comment]
Your thresholds don't make sense.

When it's X:Y that means < X, > Y

So it'll be warning if less than 1 and greater than 1800

But critical if less than 1800 or greater than 3600

Which means you have all of infinity covered in your thresholds. Check out the guidelines here:

https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

If I specify this for an apache2 process, say:

```
$ ./plugins/check_procs -w @1:1800 -c @1800:3600 --metric=ELAPSED -C apache2
```

I get the inside of those ranges (> 1 && < 1800) and (> 1800 && < 3600) respectively:

```
ELAPSED OK: 6 processes with command name 'apache2' | procs=6;;;0; procs_warn=0;;;0; procs_crit=0;;;0;
```

**Comment by quixand** [comment]
I had the same problem. I had to add the @ symbol to the range for it to work. There is nothing in the -h help output of that plugin that specifies using that symbol on ranges.

**Comment by quixand** [comment]
created pull request https://github.com/nagios-plugins/nagios-plugins/pull/400
thanks
