### ISSUE TITLE
check_apt outputs APT WARNING for no reason when run through nrpe

### ISSUE THREAD

**Issue by ceribik** [nagios-plugins/nagios-plugins#321]
I'm running Debian 9 (just updated), with nagios-plugins 2.2-3.

For some reason, whenever the check_apt check is run on the localhost through nrpe, it gives a different output when the check is run manually:

> 
> $ /usr/lib/nagios/plugins/check_nrpe -H 127.0.0.1 -c check_apt         
> APT WARNING: 0 packages available for upgrade (0 critical updates).  warnings detected, errors detected.|available_upgrades=0;;;0 critical_updates=0;;;0
> 
> $ /usr/lib/nagios/plugins/check_apt                         
> APT OK: 0 packages available for upgrade (0 critical updates). |available_upgrades=0;;;0 critical_updates=0;;;0
> 
> $ apt-get update
> Hit:1 http://security.debian.org stretch/updates InRelease
> Ign:2 http://ftp.us.debian.org/debian stretch InRelease
> Hit:3 http://ftp.us.debian.org/debian stretch-updates InRelease
> Hit:4 http://ftp.us.debian.org/debian stretch Release
> Reading package lists... Done
> 
> 
> $ cat /etc/nagios/nrpe_local.cfg
> allowed_hosts=127.0.0.1
> command[check_apt]=/usr/lib/nagios/plugins/check_apt

**Comment by box293** [comment]
When you are running the `/usr/lib/nagios/plugins/check_apt` command to test, can you please `su nagios` first and then run the command. There might be a permissions issue.

**Comment by ceribik** [comment]
You were right. It was a permission issue with a rogue file in /etc/apt/sources.list.d/ that was not world-readable and causing an error during the apt-get upgrade simulation. 

Thanks.
