### ISSUE TITLE
check_ups: perfdata is invalid

### ISSUE THREAD

**Issue by gino0631** [nagios-plugins/nagios-plugins#345]
The check_ups plugin provides voltage data using "mV" units (e.g. `voltage=218800mV`) which is not an allowed UOM (https://www.monitoring-plugins.org/doc/guidelines.html#AEN201).

The same applies to the temperature units "degC" and "degF" (though our UPS does not provide temperature readings so we are not getting errors because of that).

Moreover, warning and critical values are always multiplied by 1000, which seems to be incorrect in case of percents and temperatures.

**Comment by Madlohe** [comment]
Resolved by #413.
