### ISSUE TITLE
plugin-scripts/check_mailq.pl

### ISSUE THREAD

**Issue by sreinhardt** [nagios-plugins/nagios-plugins#35]
|| is not supported on all perl versions, "or" is suggested instead. There was a previous issue here:
https://github.com/evgeni/monitoring-plugins/commit/c576d7af0b062f783bb1a1c36f985245e25d4734
The effected code is: https://github.com/nagios-plugins/nagios-plugins/commit/bc4113fba2d251b70f8d9dae80f1b18033cace40

**Comment by abrist** [comment]
The findbin branch was merged to 2.1.0-beta-RC1.
