### ISSUE TITLE
Utils not found in check_mailq

### ISSUE THREAD

**Issue by wambowams** [nagios-plugins/nagios-plugins#354]
Using check_mailq I get following message:

Can't locate utils.pm in @INC (you may need to install the utils module) (@INC contains: /usr/lib/nagios/plugins /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/lib/nagios/plugins/check_mailq line 36.
BEGIN failed--compilation aborted at /usr/lib/nagios/plugins/check_mailq line 36.

How can I fix this?

**Comment by box293** [comment]
What Operating System are you running on?
