### ISSUE TITLE
check_http: Add support for http/2

### ISSUE THREAD

**Issue by morremeyer** [nagios-plugins/nagios-plugins#356]
Hello everyone,

I just searched for `check_http`s capability of checking via http/2 but did notice that currently no version seems to have support of it.

I propose adding support for http/2 in `check_http` if that is possible.

If my search for open Issues and in the Changelogs missed any mention of that, feel free to link me to it, please.

**Comment by allanlewis** [comment]
At the moment it seems to use HTTP 1.0, not even 1.1 - it would be good to support that as well as HTTP/2

**Comment by mauricemeyer** [comment]
Please check out check_curl, which is the successor of check_http

**Comment by allanlewis** [comment]
Thanks, @mauricemeyer - which version do you mean? I get a lot of search results for "nagios check_curl"!

**Comment by morremeyer** [comment]
Back in 2018, we manually built the binary from the feature branch and distributed in our infrastructure.

I don't remember much else from 4 years ago ^^

Closing this as the feature request (HTTP2 support) is/will be fulfilled by check_curl, so it wouldn't make sense to amend check_http
