### ISSUE TITLE
IDEA: check_disk inode-check with inode-focus

### ISSUE THREAD

**Issue by schuessmaster** [nagios-plugins/nagios-plugins#378]
I really miss inode perfdata in check_disk with -W and/or -K. My idea (i can't code this myself, sorry):
make check_disk command either -w -c OR -W -K or implement a check_inode based on check_disk (like 80% identical: same logic, different return values). Whatever, the command should primarily return inode-specific results instead of MB-values and also inode perfdata, i.e.
```
df /home -iP
Filesystem                 Inodes IUsed IFree IUse% Mounted on
/dev/mapper/vglocal-lvhome  40960   630 40330    2% /home
```
check command either/or:
```
/usr/lib64/nagios/plugins/check_inode -W 5% -K 2% -p /home
/usr/lib64/nagios/plugins/check_disk -W 5% -K 2% -p /home
```
Check result:
```
DISK OK - free inodes: /home 40330  (inode=98%);| /home=630;;;0;40960
```

**Comment by hedenface** [comment]
```
#!/bin/bash

disk=$1
warn=$2
crit=$3

output=$(df $disk -iP | tail -1)

total=$(echo $output | awk '{print $2}')
used=$(echo $output | awk '{print $3}')
free=$(echo $output | awk '{print $4}')

percentfree=$(( $free / $total ))

if [ $percentfree -lt $warn ]; then
	status="OK"
	retcode=0
elif [ $percentfree -lt $crit ]; then
	status="WARNING"
	retcode=1
elif [ $percentfree -ge $crit ]; then
	status="CRITICAL"
	retcode=3
fi

echo "DISK $status - free inodes: $disk $free (inode=$percentfree);| $disk=$used;$warn;$crit;0;$total"
```

**Comment by Madlohe** [comment]
So if you want a separate plugin, there's the one @hedenface just provided.

Otherwise, I've just pushed #468 which adds an option (--inode-perfdata) that provides perfdata for free inode percentage, as well as the raw used/free-inode values.
