### ISSUE TITLE
check_disk human readable output [PR included]

### ISSUE THREAD

**Issue by dtu-compute** [nagios-plugins/nagios-plugins#380]
For those not collecting performance data, it would be very useful to have a human readable output such as

```
Critical: less than 30% is free on one or more file systems

Status     Free   Avail   Total   Type   Mount point
------------------------------------------------------------
CRITICAL    21%    1.2T    5.3T    nfs   /nas1/home1
CRITICAL    23%    1.4T    5.8T    nfs   /nas1/groups
CRITICAL    26%    3.0T     12T    nfs   /nas1/backups
WARNING     33%     16G     50G   ext4   /
OK          38%    1.2T    2.9T    nfs   /nas1/home2
OK          50%    2.5T    4.8T    nfs   /nas1/winhome
OK          60%    1.2T    2.0T    nfs   /nas1/esetools
OK          69%    313M    477M   ext4   /boot
OK          83%    2.4T    2.9T    nfs   /nas1/home3
OK          84%     80G     95G    nfs   /nas1/titanusrlocal
OK          84%    822G    973G    nfs   /nas1/home4
OK          99%     13G     14G   ext4   /home
```

* List sorted by free space acceding.
* The column widths are so there are 3 spaces to the next column (including title).
* Length of separator line is that of the longest list line
* The first line contains the worst state. In the example critical is 30% and warning 35%.
* If not critical or warning then first line should be `OK: All file systems have more than $warn% free space left`

Proposal for argument

```
 -H, --human
    Output basic disk statistics in human readable form (no performance data included)
```

If we can find an output format that the `check_disk` maintainer would accept, then I would be happy to submit a pull request for this.

**Comment by box293** [comment]
The format you've proposed above looks great. My only suggestion is that perhaps the list is sorted by CRITICAL, WARNING, OK and the "Critical: less than 30% is free on one or more filesystems" is the first line of output.

Please send through a pull request against the maint branch and we'll get it tested / approved.

**Comment by dtu-compute** [comment]
OP updated with your requests as well with an argument proposal.

Is there a date for when the next release it made?

**Comment by box293** [comment]
I am unsure when the next release is, we've been working on the Nagios Core 4.4 release which has taken our focus away from this. I've currently started looking at the oldest Nagios Plugins issues/requests and seeing which ones I can action so we can move forward. Sorry for the delays in releases.

**Comment by iainbryson** [comment]
@box293 Hi there. 

I'm investigating the implementation of this.  I'd like to use the GnuLib `human.c`.  The most ideal way to pick that up looks like running `gnulib-tool`, per the comments in the source. 

However, because it's evidently been some time (2013?) since this has been run, there are a LOT of diffs.  Many of them are innocuous header copyright changes.  Some are more invasive, e.g.

![image](https://user-images.githubusercontent.com/1531103/58563903-4045d100-822c-11e9-9de1-52f49b90e252.png)

I'm using the instructions from https://github.com/nagios-plugins/nagios-plugins/blob/master/gl/Makefile.am , i.e.:

```
# Generated by gnulib-tool.
# Reproduce by: gnulib-tool --import --dir=. --lib=libgnu --source-base=gl --m4-base=gl/m4 --doc-base=doc --tests-base=tests --aux-dir=build-aux --no-conditional-dependencies --no-libtool --macro-prefix=gl --no-vc-files base64 crypto/sha1 dirname environ floorf fsusage getaddrinfo gethostname getloadavg getopt-gnu gettext idpriv-droptemp mountlist regex setenv strcase strcasestr strsep timegm unsetenv vasprintf vsnprintf
```

So, the question: is this kind of thing a reasonable set of changes, or should I keep them as surgical as possible, even if that means not using a 'unified' gnulib?


FWIW, I'm trying precisely this:
```
../gnulib/gnulib-tool --dry-run --import --dir=. --lib=libgnu --source-base=gl --m4-base=gl/m4 --doc-base=doc --tests-base=tests --aux-dir=build-aux --no-conditional-dependencies --no-libtool --macro-prefix=gl --no-vc-files base64 crypto/sha1 dirname environ floorf fsusage getaddrinfo gethostname getloadavg getopt-gnu gettext idpriv-droptemp mountlist regex setenv strcase strcasestr strsep timegm unsetenv vasprintf vsnprintf human
```

**Comment by box293** [comment]
I'm going to get @Madlohe to chime in on this

**Comment by Madlohe** [comment]
Thanks for the ping, Troy!

There were a bunch of other changes there that make me even more nervous (I saw maybe ~100 new .c files, even without adding the new dependency). However, we should be able to add dependencies in the future, so I think we have to just bite the bullet there.

@iainbryson, just to make sure we're okay with regard to versioning issues with gnulib-tool itself, I've [added a branch to my own repository that should handle the dependency](https://github.com/Madlohe/nagios-plugins/tree/gnulib-update). Feel free to fork from that, or to wait until I get push access to this repository. Let me know if that doesn't work for you or if you need anything else to get started.

**Comment by iainbryson** [comment]
@Madlohe That's sweet!  Unfortunately when I pull down that revision, it fails to build for me (macOS):

```mv -f .deps/check_http.Tpo .deps/check_http.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -DNP_VERSION='"2.2.1.217.ga275"' -g -O2  -L. -o check_http check_http.o libnpcommon.a ../lib/libnagiosplug.a ../gl/libgnu.a libnpcommon.a ../lib/libnagiosplug.a ../gl/libgnu.a  -lresolv  -lpthread -ldl
libtool: link: gcc -DNP_VERSION=\"2.2.1.217.ga275\" -g -O2 -o check_http check_http.o  -L. libnpcommon.a ../lib/libnagiosplug.a ../gl/libgnu.a -lresolv -lpthread -ldl
Undefined symbols for architecture x86_64:
  "_check_hostname", referenced from:
      _process_arguments in check_http.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [check_http] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
(base)```

Note that when I fork the plugins master and update the glib, it works fine on the same machine.

**Comment by Madlohe** [comment]
Unfortunately I don't know of any Macs in our office. Would you be willing to push your updated glib? I'm curious as to whether it'd work on my (CentOS) machine.

**Comment by iainbryson** [comment]
@Madlohe yeah, I came to the same conclusion.  If you don't have SSL in the build you get that undefined symbol.  If you fix that, you get another issue with `check_ldap`.   I'm able to get it to build with
:
```
diff --git a/plugins/check_ldap.c b/plugins/check_ldap.c
index 85d3f830..143297b2 100644
--- a/plugins/check_ldap.c
+++ b/plugins/check_ldap.c
@@ -576,6 +576,8 @@ print_usage (void)
                        );
 }

+#ifdef HAVE_SSL
+
 int ldap_check_cert (LDAP *ld)
 {
        SSL *ssl;
@@ -588,3 +590,10 @@ int ldap_check_cert (LDAP *ld)
        }
        return np_net_ssl_check_cert_real(ssl, days_till_exp_warn, days_till_exp_crit);
 }
+
+#else
+int ldap_check_cert (LDAP *ld) {
+    return TRUE;
+}
+
+#endif
\ No newline at end of file
diff --git a/plugins/sslutils.c b/plugins/sslutils.c
index 19d3a789..e96fc7a3 100644
--- a/plugins/sslutils.c
+++ b/plugins/sslutils.c
@@ -30,12 +30,12 @@
 #include "common.h"
 #include "netutils.h"

+int check_hostname = 0;
 #ifdef HAVE_SSL
 static SSL_CTX *c=NULL;
 static SSL *s=NULL;
 static int initialized=0;

-int check_hostname = 0;

 int np_net_ssl_init(int sd) {
        return np_net_ssl_init_with_hostname(sd, NULL);
```

Basically defining `check_hostname` regardless of `HAS_SSL` and making `np_net_ssl_init` if there's no SSL.

I can use that branch with the fixes, or my fork of the master ( https://github.com/dtu-compute/nagios-plugins/commits/feature/human ), which also contains the changes to `check_disk` that's the OP of this issue -- those are almost complete.

**Comment by Madlohe** [comment]
Thanks for the patch!

I very slightly prefer if you use the branch with your fixes, but either way is fine.

**Comment by iainbryson** [comment]
To be @Madlohe , you want me to fork https://github.com/Madlohe/nagios-plugins/tree/gnulib-update, add the OP check_disk changes, then PR that to your branch.  Is that accurate?

**Comment by Madlohe** [comment]
Yes, that works for me

**Comment by Madlohe** [comment]
This is merged into maint now - closing.
