### ISSUE TITLE
check_dns no longer works with new nslookup and AAAA records

### ISSUE THREAD

**Issue by kohenkatz** [nagios-plugins/nagios-plugins#381]
BIND 9.11.0 (and newer) ship with changes to the output format when querying for `AAAA` (IPv6) records (see [RELEASE NOTES](https://ftp.isc.org/isc/bind/9.11.0/RELEASE-NOTES-bind-9.11.0.html) and [bug report](https://bugs.isc.org/Public/Bug/Display.html?id=40420#txn-398297)).

This breaks querying for `AAAA` records using `check_dns` with the `-q AAAA` argument as well as querying for `A` records **without** `-q A`.

Here are some examples that worked with `nslookup` 9.10.3 (Ubuntu 16.04 LTS) that no longer work with `nslookup` 9.11.0+ (Ubuntu 18.04 LTS):

(*NOTE: The IP addresses that I am using with the `-a` parameter here may be different than the ones you see since Google has a lot of servers. Just replace the addresses with the ones you get to see the difference between the versions.*)

 - No `-q` - `/usr/local/nagios/libexec/check_dns -H www.google.com -a 172.217.3.100`
    - 9.10.x **WORKS** - returns `DNS OK: 0.011 seconds response time. www.google.com returns 172.217.3.100|time=0.011181s;;;0.000000`
    - 9.11.x **FAILS** - returns `DNS CRITICAL - expected '172.217.3.100' but got '172.217.3.100,2607:f8b0:4005:805::2004'`

 - Force `-q A` - `/usr/local/nagios/libexec/check_dns -H www.google.com -q A -a 172.217.3.100`
    - 9.10.x **WORKS** - returns `DNS OK: 0.011 seconds response time. www.google.com returns 172.217.3.100|time=0.011181s;;;0.000000`
    - 9.11.x **WORKS** - returns `DNS OK: 0.009 seconds response time. www.google.com returns 172.217.3.100|time=0.008966s;;;0.000000`

 - Force `-q AAAA` - `/usr/local/nagios/libexec/check_dns -H www.google.com -q AAAAA -a 2607:f8b0:4005:805::2004`
    - 9.10.x **WORKS** - returns `DNS OK: 0.011 seconds response time. www.google.com returns 2607:f8b0:4005:805::2004|time=0.010541s;;;0.000000`
    - 9.11.x **FAILS** - returns **`DNS CRITICAL - query type of -querytype=AAAA was not found for www.google.com`**

The message in the last failure led me to find the following in the BIND issue that made this change:

> 2) Modified the format of printing an AAAA response to be the same like for a A response.
> 
> Original:
> > star.c10r.facebook.com  has AAAA address 2a03:2880:f01c:2:face:b00c:0:1
> 
> Patched:
> > Name:   star.c10r.facebook.com
> > Address: 2a03:2880:f01c:2:face:b00c:0:1

I would guess that the result parser in `check_dns` doesn't recognize this new format for explicit `AAAA` queries. I would also guess that this is why it thinks the `A` and `AAAA` results should be combined when no `-q` argument is given because the results for `A` and `AAAA` now look the same.

**Comment by kohenkatz** [comment]
I wonder if the best way to fix this is to switch from using `nslookup` to using `dig +short`, since `dig +short` returns the output of the query as its only output so no parsing is needed.

**Comment by box293** [comment]
Thats a good idea, thanks for posting it.

**Comment by box293** [comment]
I agree that the issue exists, I just wanted to point out that your last command example had 5 A's instead of 4.

> Force -q AAAA - /usr/local/nagios/libexec/check_dns -H www.google.com -q AAAAA -a 2607:f8b0:4005:805::2004

5 x A:
```
/usr/local/nagios/libexec/check_dns -H www.google.com -q AAAAA -a 2607:f8b0:4005:805::2004 -v
/usr/bin/nslookup -sil -querytype=AAAAA www.google.com 
unknown query type: AAAAA
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	www.google.com
Address: 172.217.25.36
Found A record
Name:	www.google.com
Address: 2404:6800:4006:808::2004
Found A record

DNS CRITICAL - expected '2607:f8b0:4005:805::2004' but got '172.217.25.36,2404:6800:4006:808::2004'
```

4 x A:
```
/usr/local/nagios/libexec/check_dns -H www.google.com -q AAAA -a 2607:f8b0:4005:805::2004 -v
/usr/bin/nslookup -sil -querytype=AAAA www.google.com 
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	www.google.com
Address: 2404:6800:4006:808::2004
Found A record

DNS CRITICAL - expected '2607:f8b0:4005:805::2004' but got '2404:6800:4006:808::2004'
```

**Comment by kohenkatz** [comment]
@box293 that's just a typing mistake in writing up the issue, since I couldn't copy-paste between two separate computers.
