### ISSUE TITLE
check_file_age: Multiline plugin output support?

### ISSUE THREAD

**Issue by XSven** [nagios-plugins/nagios-plugins#382]
Name        : nagios-plugins-file_age
Version     : 2.2.1

If as an example I am applying the **check_file_age** plugin to the bash related configuration files of my home directory I am getting one single line of output.
      
**FILE_AGE** CRITICAL: .bash_history is 5546566 seconds old and 4273 bytes **FILE_AGE** CRITICAL: .bash_logout is 5548868 seconds old and 18 bytes **FILE_AGE** CRITICAL: .bash_profile is 5548868 seconds old and 193 bytes **FILE_AGE** CRITICAL: .bashrc is 5548868 seconds old and 231 bytes  | **age**=5546566s;20;600 size=4273B;0;0;0 **age**=5548868s;20;600 size=18B;0;0;0 **age**=5548868s;20;600 size=193B;0;0;0 **age**=5548868s;20;600 size=231B;0;0;0

How is Nagios going to process/interpret this oneliner?

Kind regards
Sven

**Comment by box293** [comment]
Can you elaborate a bit more on exactly what your issue is or what you expect the output to be like please.

**Comment by box293** [comment]
OK great, thanks for the feedback. As soon as we get a chance we'll make these changes.

**Comment by hedenface** [comment]
The guidelines say "it can" not that "it must."

It is up to the person writing the plugin how it gets output - as long as it conforms to the guidelines.

That said, I do agree with you that it would look better as extended output - the downside of this is that isn't always shown in the interface. You have to specifically be looking for the long output - when you're looking at the status table for instance - you won't see it until you click on a specific service.

I'll take a look for 2.3.0 to see if I can clean it up (or get a summarized line on the first line and the rest in the long output). If you're able to make the changes yourself and submit them via a Pull Request, that would likely help speed up the development :)

**Comment by XSven** [comment]
I would like to give it a try and implement the changes by my own in a separate branch forked from **maint**. I have cloned the project and did run

./tools/setup
./configure --enable-libtap
make test

Some perl tests are running but the script tests (./plugins-scripts/t/*.t) are missing. Any hint how to trigger the script tests would be appreciated.

**Comment by Madlohe** [comment]
Resolved by #462.
