### ISSUE TITLE
check_mysql do not use opt file

### ISSUE THREAD

**Issue by benkeil** [nagios-plugins/nagios-plugins#383]
As mentioned here <https://community.librenms.org/t/nagios-check-mysql-and-storing-password/773/6>, I try to put my password in `db-production-master.cnf` file.

    [client]
    user=xxx
    password=yyy

but the check does not use it

`./check_mysql -H db-production-master -f db-production-master.cnf`

    Access denied for user 'root'@'10.2.90.85' (using password: NO)

Further the flag is not being checked:

`./check_mysql --file does-not.exist`

    Access denied for user 'root'@'localhost' (using password: NO)

**Comment by sawolf** [comment]
Hi @sdturne - thanks for the comment. It looks like the opening post had a different problem, so I've opened a new issue for you at #692. I'm also closing this because it looks like the original problem was solved.
