### ISSUE TITLE
check_http/v2.2.1 use '-N' cause CRITICAL - Socket timeout

### ISSUE THREAD

**Issue by 2005wind** [nagios-plugins/nagios-plugins#401]
Hello 
I found use '-N' can cause CRITICAL - Socket timeout:

`# ./check_http -H www.baidu.com --onredirect=sticky --verbose --ssl -N
SSL initialized
GET / HTTP/1.1
User-Agent: check_http/v2.2.1 (nagios-plugins 2.2.1)
Connection: close
Host: www.baidu.com
Accept: */*

https://www.baidu.com:443/ is 912 characters
STATUS: HTTP/1.1 200 OK
CRITICAL - Socket timeout`

`# ./check_http  -H www.baidu.com --onredirect=sticky --verbose --ssl
SSL initialized
GET / HTTP/1.1
User-Agent: check_http/v2.2.1 (nagios-plugins 2.2.1)
Connection: close
Host: www.baidu.com
Accept: */*

https://www.baidu.com:443/ is 912 characters
STATUS: HTTP/1.1 200 OK
**** HEADER ****
Accept-Ranges: bytes
Cache-Control: no-cache
Content-Length: 227
Content-Type: text/html
Date: Thu, 19 Jul 2018 03:10:51 GMT
Etag: "5b3c3650-e3"
Last-Modified: Wed, 04 Jul 2018 02:52:00 GMT
P3p: CP=" OTI DSP COR IVA OUR IND COM "
Pragma: no-cache
Server: BWS/1.1
Set-Cookie: BD_NOT_HTTPS=1; path=/; Max-Age=300
Set-Cookie: BIDUPSID=8644B0B1CCF5FCBDD45F7B235E4A90B6; expires=Thu, 31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; domain=.baidu.com
Set-Cookie: PSTM=1531969851; expires=Thu, 31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; domain=.baidu.com
Strict-Transport-Security: max-age=0
X-Ua-Compatible: IE=Edge,chrome=1
Connection: close
**** CONTENT ****
<html>
<head>
        <script>
                location.replace(location.href.replace("https://","http://"));
        </script>
</head>
<body>
        <noscript><meta http-equiv="refresh" content="0;url=http://www.baidu.com/"></noscript>
</body>
</html>
HTTP OK: HTTP/1.1 200 OK - 912 bytes in 0.766 second response time |time=0.766271s;;;0.000000 size=912B;;;0`

**Comment by Madlohe** [comment]
Merged associated PR - closing.
