### ISSUE TITLE
Check_disk default timeout not being honered

### ISSUE THREAD

**Issue by awkohr** [nagios-plugins/nagios-plugins#414]
We had a cifs server go down yesterday for a bit which was brought back up but ended up with over > 200 check_disk processes running against that specific smb mount that were still running up to 16 hours later, when I would think at worst there would only be one as they should have died after the default 10 seconds timeout value was reached, as I didn't specify a different timeout value. 

 It appears the code collects a  timeout value if it is set and passes that to parse_timeout_string but doesn't apear to do anything else with it. 
  Other tests apear to do more with the timeout interval like check_procs with  "(void) alarm ((unsigned) timeout_interval);" or check_http with " (void) alarm (timeout_interval.)"  

Also some of the other scripts like check_procs check to make sure timeout_interval is a positive integer which might be usefull in general, if it is not being done elsewhere, that I am not seeing.

I.e. 
nrpe       302     1  0 Aug29 ?        00:00:00 /usr/lib64/nagios/plugins/check_disk -w 10% -c 5% -p /reports
nrpe       434     1  0 Aug29 ?        00:00:00 /usr/lib64/nagios/plugins/check_disk -w 10% -c 5% -p /reports
...
nrpe      8473     1  0 00:03 ?        00:00:00 /usr/lib64/nagios/plugins/check_disk -w 10% -c 5% -p /reports
nrpe      8630     1  0 00:08 ?        00:00:00 /usr/lib64/nagios/plugins/check_disk -w 10% -c 5% -p /reports
nrpe      8747     1  0 00:13 ?        00:00:00 /usr/lib64/nagios/plugins/check_disk -w 10% -c 5% -p /reports
...
nrpe     21369     1  0 08:38 ?        00:00:00 /usr/lib64/nagios/plugins/check_disk -w 10% -c 5% -p /reports
nrpe     21490     1  0 08:43 ?        00:00:00 /usr/lib64/nagios/plugins/check_disk -w 10% -c 5% -p /reports

...

**Comment by Madlohe** [comment]
Hi @awkohr,

I've just merged a patch that should fix your issue. If you still experience issues compiling from maint, let me know and I'll re-open the issue.
