### ISSUE TITLE
Force check_snmp to match the exact OID (not next)

### ISSUE THREAD

**Issue by scottchiefbaker** [nagios-plugins/nagios-plugins#418]
I believe this may be a Cisco bug but I wanted to run it by you guys first. We're testing a failed fan in a Cisco Nexus switch. The OID in question is `.1.3.6.1.4.1.9.9.117.1.4.1.1.1.536` but when I try and fetch it with `snmpget` or `check_snmp` the switch returns **.537**

```
root@green(/etc/nagios/conf.d)
:snmpget -v 2c -c sekrit 10.37.200.252  .1.3.6.1.4.1.9.9.117.1.4.1.1.1.536 -On
.1.3.6.1.4.1.9.9.117.1.4.1.1.1.537 = INTEGER: 2

root@green(/etc/nagios/conf.d)
:check_snmp -H 10.37.200.252 -C sekrit -o .1.3.6.1.4.1.9.9.117.1.4.1.1.1.536 -n -c 2:2
SNMP OK - 2 | iso.3.6.1.4.1.9.9.117.1.4.1.1.1.537=2;;2:2 
```

This is causing my Nagios checks to come back OK instead of critical. I'm thinking the Cisco switch is sending back the next available OID because **.536** isn't in the tree? Either way I believe the Nagios check should ensure that the returning OID is the same as the requested one?

**Comment by scottchiefbaker** [comment]
Any update on this? I think a simple `--strict` or `--no-next` flag would allow me to work around this Cisco bug.

**Comment by Madlohe** [comment]
Hi @scottchiefbaker,

Sorry for the late response. I'll see what I can do.

**Comment by scottchiefbaker** [comment]
Thanks for updating... For what it's worth Cisco still has yet to provide a fix either :)

**Comment by Madlohe** [comment]
Check my branch at https://github.com/Madlohe/nagios-plugins/tree/check-snmp-strict. Hopefully you can compile from there and give it a shot.

check_snmp is modified to return UNKNOWN when:
1. --strict is specified, and
2. the OID returned by snmpget differs from the one specified in -o

In my own testing, I would get the UNKNOWN error from any raw numeric OID. The workaround there is to change the first `.1` to `iso` (i.e. your OID would be `iso.3.6.1.4.1.9.9.117.1.4.1.1.1.536`. Alternatively, you can specify a MIB and use the symbolic OID.

**Comment by scottchiefbaker** [comment]
This does indeed fix my problem!

**Comment by Madlohe** [comment]
I'm glad to hear that! Closing this now
