### ISSUE TITLE
check_http expects >0 response headers

### ISSUE THREAD

**Issue by PriceChild** [nagios-plugins/nagios-plugins#42]
I have a very simple server that responds
> HTTP/1.0 200 OK
> 
> OK!! 2014-06-19 14:20:01

When pointing check_http at it hoping to check the content for a string, bad things happen:

> []# /usr/lib64/nagios/plugins/check_http -I $ipaddress -p $port -u /somepath --authorization=test:test -s 'OK!!' -v
> GET /somepath HTTP/1.0
> User-Agent: check_http/v1.4.16 (nagios-plugins 1.4.16)
> Connection: close
> Authorization: Basic dGVzdDp0ZXN0
> 
> 
> http://u.v.w.x:y/somepath is 43 characters
> STATUS: HTTP/1.0 200 OK
> **** HEADER ****
> OK!! 2014-06-19 14:20:01
> **** CONTENT ****
> 
> HTTP CRITICAL: HTTP/1.0 200 OK - string 'OK!!' not found on 'http://u.v.w.x:y/somepath' - 43 bytes in 0.014 second response time |time=0.014170s;;;0.000000 size=43B;;;0

So what seems to be happening is that check_http expects at least one header after the http status line, ignores the blank line that separates headers from content and continues taking further lines as headers. I haven't tested but I assume a further blank line would then trigger the change of understanding from header to content.

I've had a quick skim of rfc1495 & rfc2616 and don't believe that at least one response header is required... either way I'll be adding one to my server as a workaround.

Pretty sure I've got the correct CRLF separation too...
> []# echo -e "GET /somepath HTTP/1.0\r\nAuthorization: Basic dGVzdDp0ZXN0\r\n\r\n" | nc u.v.x.y z | xxd
> 0000000: 4854 5450 2f31 2e30 2032 3030 204f 4b0d  HTTP/1.0 200 OK.
> 0000010: 0a0d 0a4f 4b21 2120 3230 3134 2d30 362d  ...OK!! 2014-06-
> 0000020: 3139 2031 353a 3233 3a31 36              19 15:23:16

**Comment by jfrickson** [comment]
Fixed in the main branch via commit https://github.com/nagios-plugins/nagios-plugins/commit/224b1e50e75e5739851cc8ba4a52f4f07926fa54
