### ISSUE TITLE
Feature request: support binary units (KiB, GiB, TiB, etc.) in check_disk

### ISSUE THREAD

**Issue by rogerniesten** [nagios-plugins/nagios-plugins#422]
Most of our infrastructure uses binary units like KiB, GiB, TiB, etc., but check_disk doesn't support binary units yet. In graphs (nagiosgraph) the units are abreviated to K, G, T, etc. and it's quite confusing to have them in kB, GB, TB instead of KiB, GiB, TiB. 
So I would like to request for check_disk the support of binary units.

It seems to be fairly easy to implement this requiest.

Following modification is based on 
In check_disk.c after line 583 insert the following code:
      } else if (! strcmp (optarg, "KiB")) {
        mult = (uintmax_t)1000;
        units = strdup ("KiB");
      } else if (! strcmp (optarg, "MiB")) {
        mult = (uintmax_t)1000 * 1000;
        units = strdup ("MiB");
      } else if (! strcmp (optarg, "GiB")) {
        mult = (uintmax_t)1000 * 1000 * 1000;
        units = strdup ("GiB");
      } else if (! strcmp (optarg, "TiB")) {
        mult = (uintmax_t)1000 * 1000 * 1000 * 1000;
        units = strdup ("TiB");

And to adapt the syntax line (954), change the following line:
  printf ("    %s\n", _("Choose bytes, kB, MB, GB, TB (default: MB)"));
into:
  printf ("    %s\n", _("Choose bytes, kB, MB, GB, TB, KiB, MiB, GiB, TiB (default: MB)"));

I'm pretty new to git, so don't know exactly how the procedures work to get this request implemented.
If anyone could do that for me or guide me how to do it, I would be very thankful!

**Comment by rogerniesten** [comment]
I've made the changes myself in the following way:

1. forked the repo to maastrichtuniversity/nagios-plugins
2. made changes as mentioned in issue (also found related translation for check_disk in po/)
3. build the plugins and tested them
4. committed and pushed the changes to my fork
5. made a pull request

Now awaiting your response.
If I didn't follow the correct procedure, please let me know.

**Comment by Madlohe** [comment]
Thanks for contributing! You got this mostly right. I've merged your changes into the maintenance branch and they should be present in the next release.
