### ISSUE TITLE
README - Where is INSTALL file?

### ISSUE THREAD

**Issue by marcio-pessoa** [nagios-plugins/nagios-plugins#427]
README file says:

> * For instructions on installing these plugins for use with Nagios,
  see below.  In addition, generic instructions for the GNU toolchain can be
  found in the `INSTALL` file.

But `INSTALL` file doesn't exist.

**Comment by Madlohe** [comment]
Hi @marcio-pessoa,

looking through the history, I don't see an `INSTALL` file. In nagios-plugins 1.4 there was an `INSTALLING` file, but this doesn't seem to contain much more information than the `README`.

Was there any specific information you were looking for?

**Comment by marcio-pessoa** [comment]
Thanks.
