### ISSUE TITLE
Feature Request: Option to fail on invalid certificate for check_http

### ISSUE THREAD

**Issue by pombaer** [nagios-plugins/nagios-plugins#433]
check_http does not take care of invalid certificates. I know there is the "-C" Option to be able to check validity of certificates, but i have to create a second check in Nagios/Icinga.
Commandline tools like curl or wget require an option to accept invalid certificates, please add an Option for a basic certificate check (for example valid runtime and CA).

**Comment by Madlohe** [comment]
If I'm understanding this correctly, you wanted an option to combine both a certificate check and the regular check within check_http. This was added/merged in #399 (allowing a `--continue-after-certificate` flag) and will be included in the next release.

If this isn't what you're looking for, let me know with another comment on this issue and I'll re-open it.
