### ISSUE TITLE
getopt_long can be fooled by a null HOSTADDRESS

### ISSUE THREAD

**Issue by gcoxmoz** [nagios-plugins/nagios-plugins#443]
STR:
```
$ /usr/lib64/nagios/plugins/check_ping -v -4 -H `echo -e '\0'` -w 3000.0,80% -c 5000.0,100% -p 1
<wpl> (3000.0,80%) must be an integer percentage
check_ping: Could not parse arguments
Usage:
check_ping -H <host_address> -w <wrta>,<wpl>% -c <crta>,<cpl>%
 [-p packets] [-t timeout] [-4|-6]
```

I uncovered this through a long series of mishaps in our nagios setup, and I finally got a repro, above.  The issue stems from getopt_long tripping over a bad address line (bad hostname -> empty address in host entry -> empty but nul-terminated string in $HOSTADDRESS$).

This leads to a case where getopt_long picks up -w (the next arg) as the optarg to -H. '-w' isn't null so it gets added to the addresses array.  -w's intended arg (here, '3000.0,80%') isn't parsed by getopt, but it instead comes out as a 'non-option' arg.  We finally, confusingly, fall out with a failure that wpl must be an integer percentage (because -w was never parsed in the option loop), which hides the core problem.

I don't have a patch to offer here, as I'm a really poor C programmer.  My thought here is that something should've caught that \0 isn't a real argument to -H, and the error should've been more clear that the problem was in -H.

**Comment by Madlohe** [comment]
After testing this on my own, I don't think there's a bug here.

If I modify the check_ping code to print each address name, I find that the command above shows an address of "-w". Basically, bash doesn't pass that empty string to the plugin, instead interpreting two spaces between "-H" and the next argument.

You mentioned you aren't comfortable with C, so here's the code snippet that does that (inserted in `process_arguments()` after the `addresses[0] == NULL` block:
```
	int i;
	for (i = 0; i < n_addresses; i++) {
		printf("address is %s\n", addresses[i]);
		if (!strcmp(addresses[i], "")) {
			printf("address above is empty \n");
		}
	}
```

If I change the command to
```
/usr/lib64/nagios/plugins/check_ping -v -4 -H "`echo -e '\0'`" -w 3000.0,80% -c 5000.0,100% -p 1
```
then I get the `check_ping: Invalid hostname/address -` as expected.

I'm going to close this for now, with the recommendation that you wrap your backquotes in standard double quotes. If you think I've made a mistake here, let me know with another comment on this issue and I'll re-open it.
