### ISSUE TITLE
check_http takes very long (2.2.1)

### ISSUE THREAD

**Issue by jalbstmeijer** [nagios-plugins/nagios-plugins#444]
Hi,

Since the beginning of march a check to instagram started timing out, just taking a bit longer than the default timeout. Any idea why?

Both curl and wget don't seem to have an issue;

check_http -t 30 -4 -H www.instagram.com -u / -S
HTTP OK: HTTP/1.1 200 OK - 32645 bytes in 10.538 second response time |time=10.538104s;;;0.000000 size=32645B;;;0

check_http -t 30 -4 -H www.instagram.com -u / -S
HTTP OK: HTTP/1.1 200 OK - 32811 bytes in 10.551 second response time |time=10.551390s;;;0.000000 size=32811B;;;0

check_http -t 30 -4 -H www.instagram.com -u / -S
HTTP OK: HTTP/1.1 200 OK - 32693 bytes in 10.542 second response time |time=10.541755s;;;0.000000 size=32693B;;;0

time wget -q  -4 https://www.instagram.com -O /dev/null
real	0m0.257s

wget -q  -4 https://www.instagram.com -O /dev/null
real	0m0.244s

time wget -q  -4 https://www.instagram.com -O /dev/null
real	0m0.238s

time curl -4 https://www.instagram.com > /dev/null
reaal	0m0.390s

time curl -4 https://www.instagram.com > /dev/null
real	0m0.834s

time curl -4 https://www.instagram.com > /dev/null
real	0m0.335s

Gr, J

**Comment by jalbstmeijer** [comment]
may related to? https://github.com/nagios-plugins/nagios-plugins/issues/420

**Comment by Madlohe** [comment]
Your message on #420 indicates that this isn't an issue anymore. If it resurfaces, either leave another message on this (so I get a notification and can reopen the issue) or create a new issue.
