### ISSUE TITLE
check_dns problem with case sensitive ptr records on win server 2016

### ISSUE THREAD

**Issue by obuidl** [nagios-plugins/nagios-plugins#445]
hello folks,

we have a little problem on the check_dns command for resolving dns ptr records.
since we started working with server 2016 dns our PTR records got totally mixed up by all possible case scenarios.

we are using lowercase host names on our monitoring system. So the lookups on ip-addresses do not match to the expected results.
here is a simple example:
DNS CRITICAL - expected 'ik-sql01.domain.de.' but got 'IK-SQL01.domain.de.'

is there any chance getting this check to be case insensitive? (Renaming all hosts on our system with lowercase names is no option - unfortunately)

I guess check_dns.c is using the output of nslookup form the OS. Maybe there is an opportunity to parse this output to lowercase before checking against expected value?

Many thanks in advance.

**Comment by Madlohe** [comment]
Hi @obuidl,

This seems like it should be fixed in #398. You can try this by checkout out the 'maint' branch and compiling from there.

If you find that this doesn't work for you, post another comment on this issue and I'll re-open it.
