### ISSUE TITLE
Fix for potential overflow in check_procs due to unexpected output in pst3

### ISSUE THREAD

**Issue by troll5501** [nagios-plugins/nagios-plugins#446]
I encountered an unusual case in which check_procs will crash on Solaris with a Bus Error each time a particular application script is running. It's occurring because of the way the arguments of the process are formatted (embedded newlines).

I can reproduce the issue like this (test2.sh just sleeps):

`CMD="ORACLE_HOME=/u01/app/oracle/product/12.1.0; export ORACLE_HOME`
`PATH=/u01/app/oracle/product/12.1.0/bin:/sbin:/usr/sbin:/usr/bin:/usr/sadm/install/bin; export PATH`
`./test2.sh"`
`su - myuser -c "$CMD"`

This results in pst3 showing more than one line for the process, like this:

`S     0   184   183  10544   7256  0.0 su  su - myuser -c ORACLE_HOME=/u01/app/oracle/product/12.1.0; export ORACLE_HOME`
`PATH=/u01/app/oracle/product/12.1.0/bin:/sbin:/usr/sbin:/usr/bin:/usr/sadm/install/bin; export PATH`
`./test2.sh`

Then, when check_procs parses this output, one of the extra lines overflows the "char procstat[8]" because sscanf() does not limit the length of the first field stored into procstat here:

`cols = sscanf (input_line, PS_FORMAT, PS_VARLIST);`

I checked in configure.ac and for Solaris and many other OS, the PS_FORMAT is like this:

`ac_cv_ps_format="%s %d %d %d %d %d %f %s %n"`

So I made two changes to fix this issue:

1) Changed PS_FORMAT to avoid the potential overflow, which fixed the crash:

`"%7s %d %d %d %d %d %f %s %n"`

2) Modified pst3 to remove newlines from the output of the argument string, which is consistent with the way Solaris ps shows the output in Solaris 11:

`-      printf(" %s", args);`
`+      printf(" ");`
`+      for(j=0;j<strlen(args);j++) {`
`+       if (args[j] != '\n') {`
`+         printf("%c",args[j]);`
`+       }`
`+      }`

Looking for feedback on this.  These changes seem to resolve the issue that I faced, and should avoid any potential overflows in check_procs when parsing the ps output.  But someone else may want to determine if the same output limit should be applied to PS_FORMAT for other OSes.

**Comment by sawolf** [comment]
Hi @troll5501,

Sorry about the wait. Looking at your changes, they seem reasonable, and I've pushed them into a PR just now.
As far as putting these changes in other OSes, it probably wouldn't hurt but I don't think it's necessary. It doesn't seem like anything else is using `pst3` and, as you said, `ps` already does what you've added in your second point.
