### ISSUE TITLE
check_apt does not support -w flag

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [nagios-plugins/nagios-plugins#448]
The check_apt command does not support the warning level flag `-w`. It does support `-c` flag though. Is this intentional or is it on the to-do list?

**Comment by Madlohe** [comment]
It looks like in nagios-plugins <= 2.2.1, check_apt will return warning if any packages are available for upgrade. There was recently a change for the next version which will have this value be configurable (so you can, e.g., alert WARNING only if there are 3+ packages available via `-w 3`)
