### ISSUE TITLE
Regression: IPv6 support broke bind option for check_icmp

### ISSUE THREAD

**Issue by polski-g** [nagios-plugins/nagios-plugins#451]
RedHat tracking bug is: https://bugzilla.redhat.com/show_bug.cgi?id=1698506

#385 broke the source-binding functionality of check_icmp (`-s` option).
Notably, the calls to `socket()` here: https://github.com/nagios-plugins/nagios-plugins/blob/f593c465c4c8385da8b73c48188ba7f9bbdef3c9/plugins-root/check_icmp.c#L403

RHEL is using commit `3429dad` which looks like is in the `maint` branch and that call was [removed](https://github.com/nagios-plugins/nagios-plugins/blob/3429dad68f97bc692a72623f46b3247e6bc62aba/plugins-root/check_icmp.c#L489) in #385 via @box293 .

Calling `check_icmp -s 10.10.10.1 8.8.8.8` now results in fatal error message `Socket operation on non-socket`

**Comment by sawolf** [comment]
I'm looking into this bug now. 

I agree that the regression was somewhere in https://github.com/nagios-plugins/nagios-plugins/pull/385/commits/f0cc54f925d46201db8df3e76d2295646fcad001, but I don't think the `socket()` call has anything to do with it. It seems like the error message shows up during argument parsing, in `set_source_ip()`.

Will update the issue again when I've found a solution.

**Comment by sawolf** [comment]
@polski-g, the changes made in #486 resolved the issue on my system. Would you be willing to verify that it works for you as well?
