### ISSUE TITLE
[BUG] check_http.c 

### ISSUE THREAD

**Issue by lucvorringa** [nagios-plugins/nagios-plugins#452]
Hey,
i want to check the SSL certificate and want to check for an keyword in one run.
When I try the following command:
`./check_http -H www.nytimes.com -S -p 443 -s EXAMPLE --sni`

The output is:
`HTTP CRITICAL: HTTP/1.1 200 OK - string 'EXAMPLE' not found on 'https://www.nytimes.com:443/' - 973061 bytes in 0.167 second response time |time=0.167223s;;;0.000000;10.000000 size=973061B;;;0`

When I check the SSL certificate in the same command:
` ./check_http -H www.nytimes.com -S -p 443 -s EXAMPLE -C 20 --sni`

The Output is:
`OK - Certificate 'nytimes.com' will expire on Sat 18 Jan 2020 11:59:59 PM GMT +0000.`

In my opinion the Output should notify, that the certificate is ok, but the keyword was not found.

I hope my problem is clear.

Regards
Luca

**Comment by Madlohe** [comment]
I don't remember exact issue/PR numbers, but this came up ~2 years ago. A patch for this exists somewhere and will be included in the next plugins release.

**Comment by lucvorringa** [comment]
Okay. Thank you

**Comment by Madlohe** [comment]
I'm going to keep this issue open until the patch is actually merged in
