### ISSUE TITLE
check_ntp.pl undefined $jitter

### ISSUE THREAD

**Issue by jbg-uwaterloo** [nagios-plugins/nagios-plugins#453]
Use of uninitialized value $jitter in division (/) at /usr/local/nagios-plugins/check_ntp line 431.

If $have_ntpq is false due to it "not being there or timing out" logic will fall through into the last statement, however there is still an error since $jitter is only ever defined at line 304, which never occured.

**Comment by sawolf** [comment]
Thanks for reporting this - fixed in `maint`
