### ISSUE TITLE
BUG: check_disk -L doesn't work properly, causes UNKNOWN

### ISSUE THREAD

**Issue by ssaxnagios** [nagios-plugins/nagios-plugins#455]
./check_disk -L -w 5% -p /mnt/nfsmount
DISK UNKNOWN - free space:|

This is because the -L options case statement is missing a break:

```
    case 'L':
        stat_remote_fs = 1;
```

Should be:

```
   case 'L':
       stat_remote_fs = 1;
       break;
```

**Comment by sawolf** [comment]
Forgot about this -- closing now.

**Comment by sawolf** [comment]
Not sure why I didn't notice this before: the `stat_remote_fs` flag is only checked inside of another check for `show_local_fs`:
https://github.com/nagios-plugins/nagios-plugins/blob/a725cb0b8ce9b90d9ce1a6353bd3e3360326f2a7/plugins/check_disk.c#L361-L368

So, if you get the desired output from only setting `stat_remote_fs`, you should get the same output without `-l`/`-L`
