### ISSUE TITLE
check_snmp "evaluation methods"

### ISSUE THREAD

**Issue by jimbobmcgee** [nagios-plugins/nagios-plugins#457]
The `man`/`--help` text for `check_snmp` has said, for a long time:

> Notes:...
> All evaluation methods other than PR, STR, and SUBSTR expect that the value returned from the SNMP query is an unsigned integer.

I *think* I understand how check_snmp works (it wraps a system call to `snmpget` and parses the output), so I'm fairly certain the *unsigned integer* text is saying that the output strings are parsed as positive whole numbers, when warn/crit or rate is calculated (although the code looks like it accepts negative integers and internally converts to double with `strtod`).

But the text about *evaluation methods* is lost on me, and *PR*, *STR* or *SUBSTR* don't appear anywhere else in the help text.

What is this note actually trying to say?

**Comment by Madlohe** [comment]
Interestingly, they don't appear anywhere else in the help text or code back in 2003, either (though that specific section does).

My guess is that PR stands for "perl regexp" (aka PCRE or extended regular expressions). If that's true, then it's basically saying that, aside from string-related tests (using -r, -R, or -s), the plugin expects to work against unsigned integers, and that it will test against -w/-c. As you said, some of the documentation might be inaccurate.

**Comment by jimbobmcgee** [comment]
Thanks, @Madlohe, that does seem like the most-likely interpretation.
Happy to close this from here.
