### ISSUE TITLE
check_snmp 2.2.1 output issues - semicolon printed after value

### ISSUE THREAD

**Issue by Bangaio65** [nagios-plugins/nagios-plugins#463]
A semicolon is appended after each value, which didn't happen in 1.4.16

For example,
`/usr/lib64/nagios/plugins/check_snmp -H 192.168.1.2 -P 2c -C vmware -o hrProcessorLoad.1,hrProcessorLoad.2,hrProcessorLoad.3,hrProcessorLoad.4 -u %,%,%,% -w 60,60,60,60 -c 80,80,80,80 -D '/'`

Output on 2.2.1:
`SNMP OK - 4; %/1; %/3; %/3 %` [...]

1.4.16:
`SNMP OK - 2 %/0 %/2 %/1 %` [...]

When viewing the status in the web interface (Services page) semicolons get turned into colons.

Mostly an aesthetic issue but is there any way to suppress the output of the semicolon?

**Comment by Madlohe** [comment]
Hi @Bangaio65,

It looks like this shouldn't happen currently if you compile from the master branch/latest release. The code to do that only exists in the maint branch.
That said, I think I am going to revert that change. It looks like the option should already exist for those who want it (using the -D option).

**Comment by Madlohe** [comment]
Resolved in https://github.com/nagios-plugins/nagios-plugins/commit/000dc69d09a1ef7367c452821deb082767eabae5
