### ISSUE TITLE
configure - incorrectly determining PING_COMMAND for IPv4

### ISSUE THREAD

**Issue by clmcavaney** [nagios-plugins/nagios-plugins#493]
G'day,

I have discovered that the `PING_COMMAND` that the configure script finds won't work any more for IPv4 as the ping command on Ubuntu (specifically 18.04 - but could also be on other Linux distributions) has combined IPv4 and IPv6 into the one ping command.
The default behaviour of the ping command now is to try either IPv4 or IPv6.

So, the effect of this with the `check_ping` plugin is that the `-4` parameter has no effect.

This can be fixed by specifying a ./configure with a parameter like:
`--with-ping-command="/bin/ping -4 -n -U -W %d -c %d %s"`

But, it would be better if the `./configure` script detected this itself.

For that matter it probably should be detecting:

> `PING_COMMAND "/bin/ping -4 -n -U -W %d -c %d %s`
> `PING6_COMMAND "/bin/ping -6 -n -U -W %d -c %d %s`

Thoughts?

Regards,
Christopher

**Comment by sawolf** [comment]
Thanks for reporting this - everything you've said here looks reasonable to me. If you'd like to send a PR to `maint`, I'm happy to review/merge. Otherwise, testing on newer debian/ubuntu is definitely on my list before the next release, and I'll try to take care of it then.

**Comment by sawolf** [comment]
After some testing, I haven't been able to reproduce this. I set up a target machine with ipv6 disabled:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:80:9b:32 brd ff:ff:ff:ff:ff:ff
    inet 192.168.152.8/16 brd 192.168.255.255 scope global noprefixroute ens33
       valid_lft forever preferred_lft forever
```
And then set up an Ubuntu 18.04.3 server using [Canonical's image](https://ubuntu.com/download/server) and installed nagios-plugins from this repository (with no special options). `check_ping`'s output looks reasonable to me:
```
root@bbbbbbbbb:~/nagios-plugins# ./plugins/check_ping -4 -H 192.168.152.8 -w 5,50% -c 6,60% -v
PING OK - Packet loss = 0%, RTA = 0.37 ms|rta=0.373000ms;5.000000;6.000000;0.000000 pl=0%;50;60;0
```
The output is the same in `master` and `maint`, so for now I'm chalking this up to weird configuration in your environment. Let me know if I made a mistake here or if there's something I've left out.
