### ISSUE TITLE
check_by_ssh: Remoet command execution failed

### ISSUE THREAD

**Issue by kopilim96** [nagios-plugins/nagios-plugins#497]
I was trying to install the Nagios plugin in my server and I followed the step from the link below: https://linuxtechlab.com/nagios-monitoring-using-ssh/

Somehow after I executed the command 
`/usr/local/nagios/libexec/check_by_ssh -H <CLIENT_IP> -C <COMMAND> -l nagios`

it showed the error as below: 
`Remote command execution failed: ########################`

After go through the code from https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_by_ssh.c 
and check the code from line 103 to 113, there is where the error occurred 

but after I tried execute the command `/usr/local/nagios/libexec/check_by_ssh -H <CLIENT_IP> -C <COMMAND> -l nagios -E`

and it worked, but I am not satisfied with the -E args because I believe there is a reason for executing the code (from the line 103 to 113) 

How can I execute the command perfectly without using -E args ?

**Comment by sawolf** [comment]
That failure condition will only occur if the command you're using writes to stderr. I can't say much more without knowing the command that you're using, but if your command will always write to stderr (even if the output is okay), then that's why the -E option exists.

**Comment by kopilim96** [comment]
Yes i understand but why is the command pass to `stderr` . Thats why i dont get it and post this issue. 

I was digging from Google and i cant find any solution except the -E command.

**Comment by sawolf** [comment]
Your issue is most likely related to the command you're running, not an issue with check_by_ssh. I can't give you a better solution unless I know the command and the actual output from the plugin.

**Comment by kopilim96** [comment]
I tried with the simple command which is `uptime` as below:

`/usr/local/nagios/libexec/check_by_ssh -H <CLIENT_IP> -C uptime -l nagios`

and I even tried `/usr/local/nagios/libexec/check_by_ssh -H <CLIENT_IP> -C "uptime" -l nagios`

but it did not work.

**Comment by sawolf** [comment]
When you say it produced the error 
```
Remote command execution failed: ########################
```
Is that the literal error message (just 24 # symbols)? I assumed you were obfuscating the output for privacy reasons, but if that's the actual error, there may be some sort of message which appears each time you SSH into the targeted machine.

**Comment by kopilim96** [comment]
Those `#` are the login banner in my machine. Check on the code of the `check_by_ssh` from line 105 to 113

     if (skip_stderr == -1) /* --skip-stderr specified without argument */

		skip_stderr = chld_err.lines;


     /* UNKNOWN or worse if (non-skipped) output found on stderr */

	if(chld_err.lines > skip_stderr) {

		printf (_("Remote command execution failed: %s\n"),

		        chld_err.line[skip_stderr]);

		return max_state_alt(result, STATE_UNKNOWN);

	}

Check on the `if-statement` . I feel curios why it always execute this `if-statement`. When the `if-statement` is true then it will continued to execute the `printf`. 

I just wondering why it will execute this `if-statement` and may be I not understanding well the logic behind of this `check_by_ssh` code. Some explanations and solutions would be appreciated.

**Comment by sawolf** [comment]
As mentioned in that first comment, you can pass a number to `--skip-stderr` (or equivalently, `-E`) to skip only a certain number of lines. 

For instance, if you ran `./check_by_ssh -E 5 <other args>`, you would only skip the first five lines to appear in stderr. If you then saw a 6th line, that line would be printed after the "Remote command execution failed: " message.

If a number isn't specified, we want to skip all of stderr. To do this, the implementor decided to set the number of skipped lines to the number of lines in stderr. Thus, the second block would always be skipped.

Going back to your original concern (suppressing the banner but not any "real" error messages), your ideal solution is probably to figure out how many lines that banner is, and to supply that number to the `-E` option.

**Comment by ls440** [comment]
Hi I am facing the same issue though I am able to connect via ssh -i to the remote host 

icinga@server: ssh -i /home/icinga/.ssh/id_rsa root@clienthost ——-works 

only when I want my own script to run via check by ssh then remote execution failed.
