### ISSUE TITLE
error installing plugins

### ISSUE THREAD

**Issue by z3r0l1nk** [nagios-plugins/nagios-plugins#505]
error while installing Nagios-Plugins found in Module-Build-0.4007\Makefile.PL at line 11, easy fixed:
change 
BEGIN { do 'inc/bootstrap.pl' or die defined($@) ? $@ : $! }
to
BEGIN { do './inc/bootstrap.pl' or die defined($@) ? $@ : $! }

Error gone and successful install.

**Comment by sawolf** [comment]
Hi @z3r0l1nk,
I don't see a line like that in this repository. Are you referring to a downstream package?

**Comment by z3r0l1nk** [comment]
> 
> 
> Hi @z3r0l1nk,
> I don't see a line like that in this repository. Are you referring to a downstream package?

Hello,
It's inside perlmods/Module-Build-0.4007.tar.gz

**Makefile.PL**
BEGIN { do 'inc/bootstrap.pl' or die defined($@) ? $@ : $! }
to
BEGIN { do './inc/bootstrap.pl' or die defined($@) ? $@ : $! }

and 

**Build.PL**
BEGIN { do 'inc/bootstrap.pl' }
to
BEGIN { do './inc/bootstrap.pl' }

----------------------------------------------------------------
I tested on Debian 10 and after modifications to the files, everything worked perfectly .

**Comment by sawolf** [comment]
Thank you. I'll make sure this is included in the next bugfix release.

**Comment by sawolf** [comment]
fixed in `master`
