### ISSUE TITLE
check_icmp 'loses' perfdata labels on DOWN/CRITICAL

### ISSUE THREAD

**Issue by log1-c** [nagios-plugins/nagios-plugins#510]
When using check_icmp for checks on hosts/services the checks perfdata output changes based on the state, which is a problem for the old pnp4nagios graphing tool.

Check that reports ok/up:
![image](https://user-images.githubusercontent.com/24474580/72330674-35568880-36b7-11ea-94bf-ab9e9a188c66.png)

Check that reports critical/down:
![image](https://user-images.githubusercontent.com/24474580/72330709-44d5d180-36b7-11ea-8812-4c198cabddb4.png)

This results in the graph for packets lost containing rta ms values instead of the pl % ones:
![image](https://user-images.githubusercontent.com/24474580/72331289-3b993480-36b8-11ea-99ee-d1d24ccb4ff7.png)

pnp4nagios is not set up to have multiple files for the perfdata, as this is not suitable for the setup.

I would like to propose that check_icmp retains the other perfdata labels in the critical/down output and fills them with the warning/critical values (like check_ping does) or just zero..

system is CentOS 7, Plugin Version is check_icmp v2.2.1.git (nagios-plugins 2.2.1)

The check_icmp plugin (on Ubuntu) for the monitoring-plugins project does not have this problem

**Comment by sawolf** [comment]
Good catch - you're right that the performance data tags shouldn't change based on plugin status. I've added this for the next bugfix release

**Comment by sawolf** [comment]
The fix turned out to be relatively simple, so if you're willing to compile the plugin manually, check the branch linked in the pull request above.

**Comment by log1-c** [comment]
Tried it out, works.
Thanks for the quick fix!
