### ISSUE TITLE
typo in help message https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_procs.c#L858

### ISSUE THREAD

**Issue by fraff** [nagios-plugins/nagios-plugins#512]
Hi, there is a typo https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_procs.c#L858 it should be '-X' instead of '-C'.

**Comment by sawolf** [comment]
Thanks for reporting this - fixed in e4a6e32,
