### ISSUE TITLE
check_disk units problem

### ISSUE THREAD

**Issue by kogaba** [nagios-plugins/nagios-plugins#518]
I think this is maybe some backward compatibility issue, but the documentation doesn't mention this, and this is confusing:

help:  
> -m, --megabytes
>     Same as '--units MB'

First a minimal check:
```
# check_disk -c 15000 -w 30000 -p /storage
DISK WARNING - free space: /storage 29500 MiB (12.34% inode=100%);| /storage=209536MiB;221852;236852;0;251852
```
Reports MiB counts in MiB 

Adding the -m switch
```
# check_disk -c 15000 -w 30000 -p /storage -m
DISK WARNING - free space: /storage 29500 MB (12.34% inode=100%);| /storage=209536MB;221852;236852;0;251852
```
Reports MB still counts in MiB !!

Adding --units MB
```
# check_disk -c 15000 -w 30000 -p /storage --units MB
DISK OK - free space: /storage 30933 MB (12.34% inode=100%);| /storage=219714MB;234086;249086;0;264086
```
Reports MB counts in MB 

```
# check_disk -V
check_disk v2.2.1.git (nagios-plugins 2.2.1)
```
My icinga config default was to add -m switch, and after I removed that, because I wanted MiB I realized I already was on MiB (reported as MB), but my graphite db stopped working because of the unit change, so I added -m back and won't touch it in the future. 
So if you change this behavior it can result many broken db, but you should change the help page/doc.

So the help page should say something like:
> -m, --megabytes  Counts in MiB reports MB (backward compatibility)

Thank you

**Comment by kogaba** [comment]
I went to an older server to test this further.
check_disk v2.2 (monitoring-plugins 2.2) 
As I see you already broke the backward compatibility with --units MB GB TB which earlier was counted with 1024 and now with 1000.
Maybe I'am wrong with this, but as I understand in the feature if somebody updates this script and use the --units switch they data will go from MiB to MB and so on.
It doesn't affects me, but maybe further switches for GB and TB working like -m for MB, would help people after the update, because change the unit from MB to MiB can broke they performance db.

**Comment by sawolf** [comment]
That's a good point. I'll see about reverting the defaults to MB/GB/TB and requiring opt-in for MiB/GiB/TiB.

**Comment by Napsty** [comment]
@sawolf Unfortunately this regression is still happening in 2.3.3:

```
# ./check_disk -V
check_disk v2.3.3 (nagios-plugins 2.3.3)

# ./check_disk / 
DISK OK - free space: / 8447 MiB (89.03% inode=95%);| /=1040MiB;;;0;10015

# ./check_disk -w 15% -c 5% -W 10% -K 5% -p / 
DISK OK - free space: / 8447 MiB (89.03% inode=95%);| /=1040MiB;8512;9514;0;10015
```

The output still shows MiB instead of MB by default.

**Comment by log1-c** [comment]
any update on the wrong UOM in the output?
