### ISSUE TITLE
check_disk performance data problem

### ISSUE THREAD

**Issue by kogaba** [nagios-plugins/nagios-plugins#519]
I know the root reserved blocks causes this, but the performance data is confusing. And the service goes to Warning even if the used space doesn't reach the warning level on the generated graph.
```
# check_disk -c 15000 -w 30000 -p /storage
DISK WARNING - free space: /storage 29500 MiB (12.34% inode=100%);| /storage=209536MiB;221852;236852;0;251852
# check_disk -V
check_disk v2.2.1.git (nagios-plugins 2.2.1)
```
Extracted performance data:
Used: 209536
Warning level: 221852
Critical level: 236852
Min: 0
Max (Size): 251852

So the used doesn't reach the warning level, but the state is warning.

Warning level currently: Size - Warning parameter,
but I think it should be: Size - Warning parameter - Reserved
because the state respects to this equation.
( I think state rely on available space which is right. And in this case if Available != Size - Used - Reserved, it could indicate some filesystem issue when state goes to warning before reach the level.)

Same with the critical level.

With the -f switch the performance data looks fine, but I want to see the real size of the disk, and -f subtracts the reserved from the size as well.

**Comment by kogaba** [comment]
Further investigate the script, it seems with the -f option it's just sums up the used+available to determine the size. So it can indicate filesystem issues if the size value drops.

I tried to write a wrapper script to report real reserved blocks, then I realized I can't get the reserved blocks without root permission. Right?

**Comment by sawolf** [comment]
That's most likely true. However, unless you're configuring that reserved space, it should always be 5% of the total size. You could have your wrapper script do that calculation instead of looking for the true values.

You can also simply configure your plugin to run as root - see `check_dhcp` and `check_icmp` for examples of that.

**Comment by kogaba** [comment]
Thank you for your reply. I write my solution if somebody faces this, it may help.

My problem was, that many server has an extra 4T disk needed to set that 5% down to at last 1% and some XFS without this problem. I wanted to see this in the monitoring. I don't want to run script as root if it's avoidable, so I ended up with a wrapper script which is call the check_disk with -f and add a realsize performance parameter.
It was a bit tricky, to draw the graph in grafana, but while I use separate checks for every partition I managed to do it. At last resort I could have "hack" this realsize value into the place of min (which is always zero), but it was not necessary.
Now my warning level is below the actual level, and also get the real size.
```
# check_disk2.sh -c 15000 -w 30000 -m -p /storage
DISK WARNING - free space: /storage 29500 MB (12.34% inode=100%);| /storage=209536MB;209036;224036;0;239036 realsize=251853MB

```

**Comment by sawolf** [comment]
Thanks for documenting that - closing the issue.
