### ISSUE TITLE
check_icmp: Multiple hosts not working

### ISSUE THREAD

**Issue by lx183** [nagios-plugins/nagios-plugins#520]
Hi,

I am running the check from icinga on a rhel machine.  There are two hostnames configured with min_hosts_alive set to 1. One host is down (passive cluster node) and one is up. Updated to version from nagios-plugins-icmp-2.2.2-2 to nagios-plugins-icmp-2.3.1-1.el7.x86_64. Check result changed from OK to CRITICAL with no changes in host state. I would except it to still return Ok.

 /usr/lib64/nagios/plugins/check_icmp -H ip_of_node_down ip_of_node_up -m 1

Was there any change in the configuration of the check?         

Best regards,
Alexander

**Comment by sawolf** [comment]
Hi @lx183,

I was able to reproduce the issue as described. Can you try compiling from the pull request above to see if that fixes your problem?

**Comment by lx183** [comment]
Hi @sawolf,

as far as I can tell, your branch version works fine now.

Thank you for the quick fix.

BR\

Alexander
