### ISSUE TITLE
Mailq issue with Nullmailer on Gentoo

### ISSUE THREAD

**Issue by speikyi** [nagios-plugins/nagios-plugins#522]
>= mail-mta/nullmailer-2.0 uses new layout for mailq on gentoo.
Now it is:  2020-02-02 07:49:20 2131 bytes from <mail@mail.de>

So i had to change check_mailq.pl this line:
   if (/^[1-9][0-9]*-[01][0-9]-[0-3][0-9]\s[0-2][0-9]\:[0-2][0-9]\:[0-2][0-9]\s{2}[0-9]+\sbytes$/) {

to:
if (/^[1-9][0-9]*-[01][0-9]-[0-3][0-9]\s[0-2][0-9]\:[0-2][0-9]\:[0-2][0-9]\s[0-9]+\sbytes.+$/) {

Now it works fine.

**Comment by sawolf** [comment]
Hi @speikyi, thanks for letting me know about this.

What version of nagios-plugins are you using? I believe this issue was fixed in https://github.com/nagios-plugins/nagios-plugins/commit/4b1bc908d7aebdc4f27cb3843c2d844d61dab21b, which was part of v2.2.1.

**Comment by speikyi** [comment]
Hi,
i test it with net-analyzer/nagios-plugins-2.3.1-r1.

In 4b1bc90 its
`if (/^[1-9][0-9]*-[01][0-9]-[0-3][0-9]\s[0-2][0-9]:[0-2][0-9]:[0-2][0-9]\s{2}[0-9]+\sbytes$/) {`
for this layout: 2006-06-22 16:00:00  282 bytes

But now it is with mailadress behind: 2020-02-02 07:49:20 2131 bytes from mail@mail.de 
And the regex didn't match, so i had to add ".+"
`if (/^[1-9][0-9]*-[01][0-9]-[0-3][0-9]\s[0-2][0-9]:[0-2][0-9]:[0-2][0-9]\s[0-9]+\sbytes.+$/) {`


at this moment i found another bug.... the minutes are limited to [0-2][0-9].

so this must be the right line, isn't it?
`if (/^[1-9][0-9]*-[01][0-9]-[0-3][0-9]\s[0-2][0-9]:[0-5][0-9]:[0-2][0-9]\s[0-9]+\sbytes.+$/) {`

**Comment by sawolf** [comment]
in 4b1bc90 the regexp is `/^[1-9][0-9]*-[01][0-9]-[0-3][0-9]\s[0-2][0-9]\:[0-2][0-9]\:[0-2][0-9]\s{1,2}[0-9]+\sbytes$/`, which allows 1 or 2 whitespace characters (maintaining backward compatibility with the previous format).

I agree that the minutes and seconds are incorrect. I think the fixed regexp should probably look like

`/^[1-9][0-9]*-[01][0-9]-[0-3][0-9]\s[0-2][0-9]\:[0-5][0-9]\:[0-5][0-9]\s{1,2}[0-9]+\sbytes$/`

I don't know anything about the gentoo environment, so I haven't tried to retrieve the package and inspect that code. However, looking at [this](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-analyzer/nagios-plugins) I don't see anything to indicate an older revision or extra patch to check_mailq.pl. @orlitzky do you know about this?

**Comment by orlitzky** [comment]
https://xkcd.com/1171/

Our nagios-plugins package is not patched, except to fix the definition of `MYSQL_PORT`. You can see the [entire build process in the ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-analyzer/nagios-plugins/nagios-plugins-2.3.1-r1.ebuild). Is that the question?

**Comment by sawolf** [comment]
Yes, thanks for confirming.

@speikyi, I'm not sure why your original issue occurred, but I'm planning to merge the pull request above into the next release. If you'd like, you can compile from there and verify that it works for your system(s).
