### ISSUE TITLE
check_procs.c lists -C as option for both Command and Exclude

### ISSUE THREAD

**Issue by cherdt** [nagios-plugins/nagios-plugins#523]
I believe this line:

    printf (" %s\n", "-C, --exclude-process");

Should instead show `-X`:

    printf (" %s\n", "-X, --exclude-process");

Based on this line in `print_usage()`:

    printf (" [-C command] [-X process_to_exclude] [-k] [-t timeout] [-v]\n");

**Comment by sawolf** [comment]
I agree. Good catch.
