### ISSUE TITLE
ntp_time performance data decimal separator

### ISSUE THREAD

**Issue by kogaba** [nagios-plugins/nagios-plugins#526]
One of my servers has Hungarian language settings where the decimal separator is comma.
Unfortunately the ntp_time command performance data respects to this, but it shouldn't.

```
$ ./check_ntp_time -H 0.debian.pool.ntp.org -c 1 -w 0.5
NTP WARNING: Offset -0,0820441246 secs|offset=-0,082044s;0,000000;1,000000;
$ export LC_NUMERIC=en_US.UTF-8
$ ./check_ntp_time -H 0.debian.pool.ntp.org -c 1 -w 0.5
NTP OK: Offset -0.07921752334 secs|offset=-0.079218s;0.500000;1.000000;
$ ./check_ntp_time -V
check_ntp_time v2.2 (monitoring-plugins 2.2)
```
version 2.2.1 has the same issue.
I have tried adding `env.LC_NUMERIC="en_US.UTF-8"` to the CheckCommand definition, but no luck, and my performance db doesn't accept this format. EDIT: and just noticed even the status is wrong.

**Comment by kogaba** [comment]
This is an ubuntu linux. A workaround which is working is adding `LC_NUMERIC="en_US.UTF-8"` to /etc/default/icinga2

**Comment by sawolf** [comment]
I was able to reproduce this.

It looks like a couple of other plugins already set LC_NUMERIC to "C" explicitly. The pull request above adds that to the check_ntp plugins. 

However, you may want to post a new issue to https://github.com/monitoring-plugins/monitoring-plugins, since they seem to be your upstream repository.

**Comment by kogaba** [comment]
@sawolf thanks I didn't realized yet that this is two different project :o
Could you please tell me what is the difference?

**Comment by sawolf** [comment]
In terms of the features/capabilities of the two projects there isn't a huge difference - the project was relatively mature by 2009 when the community split. The main thing is that this repository is maintained by the same company that handles Nagios Core/Nagios XI, while monitoring-plugins is maintained by a different community that are responsible for other open-source projects (icinga2, naemon, plus others that I'm forgetting at the moment).

Also, the default packages for DEB-based distributions as well as the BSDs use monitoring-plugins, whereas RPM-based distributions as well as Gentoo tend to use this project.

**Comment by kogaba** [comment]
I have to monitor both rpm and deb based servers now I know these a bit different. Thank you for clarifying this.
