### ISSUE TITLE
check_icmp v2.3.2 works only correct with -v -v  (debug > 1)

### ISSUE THREAD

**Issue by feisenko** [nagios-plugins/nagios-plugins#530]
Hello,
in check_icmp.c line 1022, variable "ip" is set to a value, only if debug > 1 :
    if (debug > 1) {
      ip = (union ip_hdr *)buf;
but variable "ip" is also needed later (outside debug) in line 1035 :
      hlen = ip->ip.ip_hl << 2;
this may result in a hlen of 0, which maybe by luck is the correct value on some systems, but let mine (openSUSE Leap 15.1) run into handle_random_icmp, and become CRITICAL on every test.
I have recompiled check_icmp.c with:
    ip = (union ip_hdr *)buf;
    if (debug > 1) {
and now it works as expected.
Best regards,
Franz

**Comment by sawolf** [comment]
Thanks for reporting this.
