### ISSUE TITLE
check_http v2.3.2 does not read expected Content-Length

### ISSUE THREAD

**Issue by feisenko** [nagios-plugins/nagios-plugins#535]
I had the strange behavior, that check_http sometimes finds the string given by -s parameter, sometimes not. 
I see now that there is already a commit 365a15c to solve the primary problem 'check_http: fixed missing parens...' , but I think, there is a second problem in this code block of check_http.c:
`       /* Continue receiving the body until content-length is met */`
`        while (seen_length < content_length`
`            && (i = my_recv(buffer, MAX_INPUT_BUFFER-1) > 0)) {`
` `
`            buffer[i] = '\0';`
` `
`            if ((full_page_new = realloc(full_page, pagesize + i + 1)) == NULL)`
`                die (STATE_UNKNOWN, _("HTTP UNKNOWN - Could not allocate memory for full_page\n"));`
`            memmove(&full_page_new[pagesize], buffer, i);`

Beside setting the () around my_recv, I think, also in line 1229 memmove needs i + 1 or the ending '\0' will not be added explicitly (realloc does not need to set added mem to zero by definition).

`       /* Continue receiving the body until content-length is met */`
`        while (seen_length < content_length`
`            && ((i = my_recv(buffer, MAX_INPUT_BUFFER-1)) > 0)) {`
` `
`            buffer[i] = '\0';`
` `
`            if ((full_page_new = realloc(full_page, pagesize + i + 1)) == NULL)`
`                die (STATE_UNKNOWN, _("HTTP UNKNOWN - Could not allocate memory for full_page\n"));`
`            memmove(&full_page_new[pagesize], buffer, i + 1);`

The same problem is maybe also in line 1198 with the memmove of the primary my_recv loop.

Best regards,
Franz

**Comment by sawolf** [comment]
Good catch. Weirdly, the `realloc()` statement already accounts for the null byte. I've added this on to #533.

**Comment by sawolf** [comment]
Hey, looks like I forgot to close this for the 2.3.3 release. If `check_http` is working well for you know, just ignore this. If you're still having problems related to Content-Length handling, let me know and we'll re-open this issue.
