### ISSUE TITLE
check_log always with an error message in first line (./check_log: 218: [[: not found)

### ISSUE THREAD

**Issue by loebelch** [nagios-plugins/nagios-plugins#539]
```
# ./check_log --version
check_log v2.3.3 (nagios-plugins 2.3.3)
```

OS: tested with Debian 9 and Ubuntu 19.10
Plugins compiled from sources.

When calling check_log it always shows an error message in the first line:
```
# ./check_log -F /var/log/syslog -O /tmp/test -q systemd
./check_log: 218: [[: not found
Log check ok - 0 pattern matches found|match=0;;;0
```
When using an older version (f.e. 2.2.1) no error message is shown.

**Comment by sawolf** [comment]
Thanks for reporting this - looks like someone used a bash-ism in an sh script. Should be fixed in the master branch now.
