### ISSUE TITLE
Inconsistent and incorrect behaviour for check_by_ssh when failing to execute command

### ISSUE THREAD

**Issue by guillomovitch** [nagios-plugins/nagios-plugins#618]
When failing to execute a command on a remote host, check_by_ssh behavior depends of the usage of the --skip-stderr option.

Without --skip-stderr option:
$> /path/to/plugins/check_by_ssh -H host  -C  "/no/such/command"  -o StrictHostKeyChecking=no
Remote command execution failed: sh: /no/such/command: No such file or directory
$> echo $?
3

With --skip-stderr option:
 $> /path/to/plugins/check_by_ssh -H host  -C  "/no/such/command"  -o StrictHostKeyChecking=no --skip-stderr
UNKNOWN - check_by_ssh: Remote command '/no/such/command' returned status 127
$> echo $?
127

The first error message lacks the 'UNKNOWN - check_by_ssh: ' prefix, which is a minor issue. The real problems comes from the assumption than the remote exit status always come from the remote command, following standard nagios plugin conventions, whereas it may as well comes from the remote shell, such as in the previous example, or from ssh itself, if there was a connection error. In those last case, it should not be used directly as exit status, but remapped to either STATE_UNKNOWN or STATE_CRITICAL. Otherwise, it result in the following error from nagios:
Return code of 127 for service YYY on host XXX was out of bounds

I'm using the latest version of nagios-plugins, ie 2.3.3

**Comment by sawolf** [comment]
Fixed in 2.4.0 - closing
