### ISSUE TITLE
check_http - Don't include default Accept header if one is provided

### ISSUE THREAD

**Issue by alexbarnsley** [nagios-plugins/nagios-plugins#62]
This can cause problems with some servers who only look for 1 Accept header so sending **Accept: */\**\* can cause problems when checking these using a difference Accept.

The line in question is [plugins/check_http.c:919](https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_http.c#L919)

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/ed305f09bbd9b6adb131d22afcb2d2c83fc273f3
