### ISSUE TITLE
OpenSSL error

### ISSUE THREAD

**Issue by rmuhamedgaliev** [nagios-plugins/nagios-plugins#63]
When i compile plugins

```bash
./configure --with-nagios-user=nagios --with-nagios-group=nagios --with-openssl=/usr/bin/openssl --enable-perl-modules --enable-libtap
```
I have follow error:

__/usr/local/src/nagios4/nagios-plugins-2.0.3/plugins/sslutils.c:65: undefined reference to `SSLv2_client_method'__

OpenSSL version __OpenSSL 1.0.1j 15 Oct 2014__ Ubuntu.

**Comment by zerOnepal** [comment]
@sreinhardt is it fixed ?? similar error  while doing make: :disappointed: 

```bash
Making all in plugins
make[2]: Entering directory `/tmp/hello5fukfZLv/nagios-plugins-release-2.0.3/plugins'
2.0.3.git
/bin/bash ../libtool --tag=CC   --mode=link gcc -DNP_VERSION='"2.0.3.git"' -g -O2  -L. -L/usr/local/ssl/lib -o check_http check_http.o libnpcommon.a ../lib/libnagiosplug.a ../gl/libgnu.a libnpcommon.a ../lib/libnagiosplug.a ../gl/libgnu.a  -lnsl -lresolv -lssl -lcrypto -lpthread -ldl 
libtool: link: gcc -DNP_VERSION=\"2.0.3.git\" -g -O2 -o check_http check_http.o  -L. -L/usr/local/ssl/lib libnpcommon.a ../lib/libnagiosplug.a ../gl/libgnu.a -lnsl -lresolv -lssl -lcrypto -lpthread -ldl
libnpcommon.a(sslutils.o): In function `np_net_ssl_init_with_hostname_version_and_cert':
/tmp/hello5fukfZLv/nagios-plugins-release-2.0.3/plugins/sslutils.c:65: undefined reference to `SSLv2_client_method'
collect2: ld returned 1 exit status
make[2]: *** [check_http] Error 1
make[2]: Leaving directory `/tmp/hello5fukfZLv/nagios-plugins-release-2.0.3/plugins'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/hello5fukfZLv/nagios-plugins-release-2.0.3'
make: *** [all] Error 2
```

**Comment by abrist** [comment]
It looks like is the method was removed:
"SSLv2_client_method, SSLv2_server_method and SSLv2_method where removed in OpenSSL 1.1.0."
See the history section:
https://www.openssl.org/docs/ssl/ssl.html

There is a check for this in sslutils.c:

        case 2: /* SSLv2 protocol */
#if defined(USE_GNUTLS) || defined(OPENSSL_NO_SSL2)
                printf(("%s\n", _("CRITICAL - SSL protocol version 2 is not supported by your SSL library.")));
                return STATE_CRITICAL;
#else
                method = SSLv2_client_method();
                ssl_options = SSL_OP_NO_SSLv3 | SSL_OP_NO_TLSv1;
#endif

And there were a few different changes to disable SSLv2:

https://github.com/nagios-plugins/nagios-plugins/commits/2.1.0-beta-RC1/plugins/sslutils.c

Are you still having this issue?

**Comment by jfrickson** [comment]
I have a complete and backward-compatible update for SSL/TLS in https://github.com/NagiosEnterprises/nrpe/tree/nrpe-2-16-RC2 that should also include the fix for this issue.

Please read the README.SSL.md file.

**Comment by jfrickson** [comment]
My last comment above on Nov 10, 2015 should have been posted to an NRPE issue.
That notwithstanding, looking at the code, and having no response to abrist's comment on Jul 28, 2015, I'm assuming this issue is fixed. Closing.
