### ISSUE TITLE
check_procs on Solaris fails sometimes

### ISSUE THREAD

**Issue by jwinkle01** [nagios-plugins/nagios-plugins#64]
On Solaris, check_procs uses pst3 instead of /bin/ps (see http://nagios-plugins.org/doc/faq/ps-on-solaris.html for background). There's a small bug in pst3 which causes it to NOT report some processes that are at the end of the process table, at least on very busy systems (we noticed this on a CoolThreads T5240 with load averages up to 90).

The bug is that a filehandle is not properly closed. See http://tracker.nagios.org/view.php?id=658 for the patch.

**Comment by abrist** [comment]
Fixed in commit: https://github.com/nagios-plugins/nagios-plugins/commit/1ba49583b8b52d44e66d15b0a9c4fd85f35f0d86

Thanks!
