### ISSUE TITLE
cant able to login in to Nagios for  configuring VMware devices. 

### ISSUE THREAD

**Issue by chokkamsanjeev** [nagios-plugins/nagios-plugins#646]
Hi Team,

i am trying to configure VMWARE hosts in NagiosXI. but its throwing the below error.

Error: It appears as though you have not installed the VMware SDK or ESX plugins on your Nagios XI server. You must have these components properly installed on your system before using this wizard.

Could you please kindly provide the best solution to resolve this issue.

![VMWARE error](https://user-images.githubusercontent.com/101616573/158304625-dedcf87f-cb05-44fe-b897-a9675f67196f.GIF)

**Comment by sawolf** [comment]
Hi @chokkamsanjeev, thanks for reaching out. This issue list is for the open-source project nagios-plugins, not for Nagios XI. If you want to get your issue resolved, you should reach out to the Nagios XI Support Team, as they'll be able to diagnose your issue faster.

You may also be able to resolve the issue by clicking the blue link under the error, and following the directions there. Best of luck!
