### ISSUE TITLE
can prometheus blackbox exporter has the same function with check_smtp

### ISSUE THREAD

**Issue by gnnx0425** [nagios-plugins/nagios-plugins#660]
Hi,

May I ask if module TCP of blackbox exporter on Prometheus has the same ability with check_smtp?

That is using module TCP to monitor the port of the SMTP host.

**Comment by sawolf** [comment]
Hi @gnnx0425, thanks for reaching out. It sounds like you're wondering about the capabilities of a module in the Prometheus project. If so, we don't have any affiliation with that project - I would reach out to them for specifics about what their software is capable of.
