### ISSUE TITLE
check_mailq delivers bad output ('$' characters) upon a failed postfix unit on CentOS/RHEL7

### ISSUE THREAD

**Issue by Decstasy** [nagios-plugins/nagios-plugins#663]
Hello,

as soon as postfix is dead on a CentOS/RHEL7, I'm getting a bad plugin output with $ characters in it. Therefore my Icinga2 is trying to interpret it as a macro which lets (in my case) the whole notification process fail. I can imagine, that others have similar problems with this behaviour.

### Plugin
check_mailq v2.3.3 (nagios-plugins 2.3.3)
```bash
[root@REDACTED ~]# '/usr/lib64/nagios/plugins/check_mailq' '-c' '100' '-t' '60' '-w' '50'
postqueue: warning: Mail system is down -- accessing queue directly
OK: postfix mailq reports queue is empty|unsent=0;50;100;0
[root@REDACTED ~]# sudo -u nagios '/usr/lib64/nagios/plugins/check_mailq' '-c' '100' '-t' '60' '-w' '50'
postqueue: fatal: Queue report unavailable - mail system is down
Use of uninitialized value $lines[0] in pattern match (m//) at /usr/lib64/nagios/plugins/check_mailq line 355.
Use of uninitialized value $lines[0] in pattern match (m//) at /usr/lib64/nagios/plugins/check_mailq line 357.
Couldn't match /usr/bin/mailq output
```

### mailq as root and nagios
```bash
[root@REDACTED ~]# mailq
postqueue: warning: Mail system is down -- accessing queue directly
Mail queue is empty
[root@REDACTED ~]# sudo -u nagios mailq
postqueue: fatal: Queue report unavailable - mail system is down
```
I thought giving the nagios user the "mail" group would help to have a direct access, but I was wrong.

### Server itself
CentOS Linux release 7.9.2009 (Core)
Postfix version 2.10.1
perl 5, version 16, subversion 3 (v5.16.3)
```bash
[root@REDACTED ~]# systemctl status postfix.service
● postfix.service - Postfix Mail Transport Agent
   Loaded: loaded (/usr/lib/systemd/system/postfix.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
```

## My emergency notification
Emergency because it's not able to create a "normal" ticket. This reached me via a central logging monitoring on a master which was responsible for creating the ticket.
```bash
CRITICAL - (1 errors in check_logfiles_notifications.protocol-2022-07-28-16-57-15) - [2022-07-28 16:55:11 +0200] warning/PluginNotificationTask: Notification command for object 'REDACTED!Mail Queue Size' (PID: -1, arguments: 'sh' '-c' '') terminated with exit code 3, output: Error: Non-optional macro 'lines[0] in pattern match (m//) at /usr/lib64/nagios/plugins/check_mailq line 355.\Use of uninitialized value ' used in argument '--description' is missing.
```

# Possible solution
I wish to have a clean output, that my postfix is r.i.p. and some better error handling for this kind of case. E.g. just print the advice "Use of uninitialized value..." only if verbose is set? Could you please help @evgeni ?

Thanks in advance and best regards,
Dennis

**Comment by evgeni** [comment]
I'm sorry, but the last time I touched this was in 2014, I have neither any memory of the code, nor any way to test this anymore (no Nagios, no Postfix on CentOS).

**Comment by evgeni** [comment]
Aparently I still can write Perl (I never could read it…): https://github.com/nagios-plugins/nagios-plugins/pull/664
