### ISSUE TITLE
check_ntp.c violates strict aliasing rules

### ISSUE THREAD

**Issue by orlitzky** [nagios-plugins/nagios-plugins#665]
(Reported to us downstream at https://bugs.gentoo.org/861200)

A few places in `check_ntp.c` use pointer casts and then dereference the result, which is undefined behavior in C. While I guess it is usually OK, it becomes especially dangerous when link-time optimization is used. To pick one example,

```
check_ntp.c:164:32: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wstrict-aliasing]]
  164 | #define L32(x) (((uint32_t*)&x)[0])
      |                                ^
check_ntp.c:175:33: note: in expansion of macro ‘L32’
  175 |                          (ntohl(L32(n))-EPOCHDIFF) + \
      |                                 ^~~
check_ntp.c:215:21: note: in expansion of macro ‘NTP64asDOUBLE’
  215 |         client_tx = NTP64asDOUBLE(m->origts);
      |                     ^~~~~~~~~~~~~
```

I think the tl;dr is that compilation should succeed with `-fstrict-aliasing and -Werror=strict-aliasing`  in `CFLAGS`. Note that `-fstrict-aliasing` is already included in `-O2`.

**Comment by sawolf** [comment]
Thanks for reaching out. We can probably fix that.

(For myself: [this gist](https://gist.github.com/shafik/848ae25ee209f698763cffee272a58f8) gives two different approaches that achieve the same result while complying with language standards.)

**Comment by sawolf** [comment]
The above patch should resolve the issue - if you still have issues building with `-Werror=strict-aliasing` or if you think any of the changes aren't right, feel free to reopen this issue.
