### ISSUE TITLE
check_nt does not correctly report a DNS entry it cannot resolve

### ISSUE THREAD

**Issue by box293** [nagios-plugins/nagios-plugins#67]
I was doing some testing with check_nt and I mis-spelt the dns name of the client I was targeting:

<pre>./check_nt -H in2008r2-01.box293.local -s password -p 12489 -v UPTIME
Name or service not known
could not fetch information from server</pre>

The correct DNS name is win2008r2-01.box293.local, here you can see it working:
<pre>./check_nt -H win2008r2-01.box293.local -s password -p 12489 -v UPTIME
System Uptime - 0 day(s) 1 hour(s) 51 minute(s) |uptime=111</pre>

The plugin should report something like:
<pre>Cannot resolve in2008r2-01.box293.local to a valid address</pre>

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit referenced above
