### ISSUE TITLE
check_disk.c: build failure with upcoming clang-16

### ISSUE THREAD

**Issue by orlitzky** [nagios-plugins/nagios-plugins#670]
clang-15 tried to enable the following by default:

* `-Werror=implicit-function-declaration`
* `-Werror=implicit-int`
* `-Werror=strict-prototypes`

This caused some breakage, so they're delaying it until clang-16. But it's still coming. With those flags, nagios-plugins fails to build:

```
check_disk.c:392:219: warning: format specifies type 'unsigned long long' but
      the argument has type 'uintmax_t' (aka 'unsigned long') [-Wformat]
  ...path->dfree_inodes_percent, fsp.fsu_blocksize, mult);
```
```                                                    ^~~~
check_disk.c:413:23: error: call to undeclared function 'min_state'; ISO C99 and
      later do not support implicit function declarations
      [-Werror,-Wimplicit-function-declaration]
```

**Comment by sawolf** [comment]
Patch is available in master - I only tested the changes using the above flags in GCC, so if you have issues with clang, feel free to reopen this issue.

**Comment by orlitzky** [comment]
Great, thank you!
