### ISSUE TITLE
Dell EMC OpenManage Plug-in for Nagios Core - Rollup status not available

### ISSUE THREAD

**Issue by Donvito777** [nagios-plugins/nagios-plugins#678]
As in the subject line: 
I installed ell EMC OpenManage Plug-in for Nagios Core 3.2 and I have few services UNKNOWN and "Rollup status not available"

Hardware: PowerEdge R540
iDRAC Firmware Version | 6.00.02.00

Any idea, why some of the check so not work?

**Comment by sawolf** [comment]
Hi @Donvito777, thanks for reaching out.

Unfortunately, we don't directly support the Dell EMC OpenManage code - that's written and maintained by Dell. If I were you, I would look for an enterprise contact within that organization.
