### ISSUE TITLE
check_snmp returns OK for missing OID - reopen

### ISSUE THREAD

**Issue by meni2029** [nagios-plugins/nagios-plugins#679]
I'm opening a new issue of #287 

The check_snmp returns OK and exit code 0 when OID is missing. But the issue happens only if we don't give threshold parameters (and maybe only with snmpv2?). You can try without the thresholds:

```
$ ./check_snmp -H 192.168.1.1 -C public -P 2c -o 1.3.6.1.4.1.2021.10.4.5.1 -l "Load1"
```

I get:

```
SNMP OK - Load1 No Such Object available on this agent at this OID |
```

If I add thresholds parameters, then I get UNKNOWN as I would expect.

I think it would make sense to return "UNKNOWN" even when no threshold is given.
What do you think ?

**Comment by sawolf** [comment]
Hi @meni2029, thanks for reaching out. I agree that this is a bug (and it looks like the previous maintainer did too - just couldn't reproduce it).

Thanks for looking into this, I'll see what I can do about it.

**Comment by phil-or** [comment]
Any news about this bug?
