### ISSUE TITLE
[bug] nagios-plugins-check-updates

### ISSUE THREAD

**Issue by beinbliss** [nagios-plugins/nagios-plugins#68]
OS: centos 7
nagios-plugins-check-updates

check_updates script does not work properly when --security-only is used.
Though there are no security updates it still prints CRITICAL.

CHECK_UPDATES CRITICAL - 76 updates available | total_updates=76;0;0

While on Centos 6 

CHECK_UPDATES OK - 8 non-critical updates available | total_updates=8;0;0 security_updates=0;0;0

Centos7:
nagios-plugins-check-updates-1.6.7-1.el7.x86_64
Centos6:
nagios-plugins-check-updates-1.6.3-1.el6.x86_64

**Comment by abrist** [comment]
This plugin is not included in this package.  Please contact the package maintainer: https://admin.fedoraproject.org/pkgdb/package/nagios-plugins-check-updates/
Or the upstream source:
https://trac.id.ethz.ch/projects/nagios_plugins/wiki/check_updates
