### ISSUE TITLE
check_sensors uses egrep and probably does not need to

### ISSUE THREAD

**Issue by mhjacks** [nagios-plugins/nagios-plugins#698]
I am running Fedora 38, which will be released soon.

Fedora 38 contains the grep package grep-3.8-3.fc38.x86_64.

In this version, egrep exits 2 when called - and check_sensors calls egrep. However, it seems that it only uses the -q argument, and just calling "grep" should be sufficient.

I've proposed #697 to address this.

**Comment by sawolf** [comment]
Hi Martin, thanks for reaching out about this - I'm surprised that I didn't leave a response here earlier, but I'm closing this since #697 was merged in nagios-plugins 2.4.5

**Comment by mhjacks** [comment]
Perfectly understandable! I'm glad to see the PR merged; that's the important thing. Thanks for closing the loop all the same!
