### ISSUE TITLE
segfaults in check_mrtg

### ISSUE THREAD

**Issue by jodiecunningham** [nagios-plugins/nagios-plugins#71]
Version tested: Nagios plugins 2.0.3

Files:
https://www.dropbox.com/s/yk4bb71xjf42ezw/check_mrtg_0c56eade?dl=0
https://www.dropbox.com/s/fjwd7ef4zx8d9gq/check_mrtg_5ccad87d?dl=0
https://www.dropbox.com/s/gbj81o5hrvfhohc/check_mrtg_ebcf293c?dl=0

To reproduce ($i as reproducer file):
    check_mrtg -F $i -a AVG -v 1 -w 60000 -c 80000

Output:
    Aborted 

Sample BT:
```
[New LWP 5313]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/jodicun/opt/nagios-plugins-2.0.3/plugins/check_mrtg -F check_mrtg_0c56ead'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI_____strtoul_l_internal (nptr=0x0, endptr=endptr@entry=0x0, base=base@entry=0xa, group=group@entry=0x0, loc=0x7ffff7bb6060 <_nl_global_locale>)
 at ../stdlib/strtol_l.c:298
298     ../stdlib/strtol_l.c: No such file or directory.
#0  __GI_____strtoul_l_internal (nptr=0x0, endptr=endptr@entry=0x0, base=base@entry=0xa, group=group@entry=0x0, loc=0x7ffff7bb6060 <_nl_global_locale>)
 at ../stdlib/strtol_l.c:298
#1  0x00007ffff78333c2 in __GI_strtoul (nptr=<optimized out>, endptr=endptr@entry=0x0, base=base@entry=0xa) at ../stdlib/strtol.c:108
#2  0x000000000040262f in main (argc=0xb, argv=<optimized out>) at check_mrtg.c:104
#3  0x00007ffff7817ec5 in __libc_start_main (main=0x401d80 <main>, argc=0xb, argv=0x7fffffffe008, init=<optimized out>, fini=<optimized out>, rtld_fini
=<optimized out>, stack_end=0x7fffffffdff8) at libc-start.c:287
#4  0x0000000000402992 in _start ()
exe = '/home/jodicun/opt/nagios-plugins-2.0.3/plugins/check_mrtg -F check_mrtg_0c56ead'
```

System Details:
AMD64
Distributor ID: Ubuntu
Description: Ubuntu 14.04.1 LTS
Release: 14.04
Codename: trusty

Found with the fuzzer American Fuzzy Lop ( http://lcamtuf.coredump.cx/afl/ )

**Comment by abrist** [comment]
We have added a few fixes for segfaults in c plugins.  Can you check to see if this is recurring on the 2.1.0-beta-RC1 branch?

**Comment by jfrickson** [comment]
No response for almost a year. Assuming this has been fixed.

**Comment by box293** [comment]
I'm still seeing the problem, can kind of re-produce it.
```
/usr/local/nagios/libexec/check_mrtg -F /var/lib/mrtg/10.25.13.15_2.rrd -a AVG -v 1 -w 5 -c 10
Segmentation fault

/usr/local/nagios/libexec/check_mrtg -F /var/log/messages -a AVG -v 1 -w 5 -c 10
Avg. value = 12 |value=12;5;10;
```
I suspect that the **rrd** file I've pointed to is not a valid mrtg log file (_and neither is /var/log/messages_). However there should be a better error message instead of a segfault.
