### ISSUE TITLE
Version 2.4.3 bundles very old check_http

### ISSUE THREAD

**Issue by ltning** [nagios-plugins/nagios-plugins#713]
The check_http in the .tar.gz for 2.4.3 is much older (says it's version 2.3.3) than the one in 2.4.0 or 2.4.4. Some package sources are stuck on 2.4.3, and upgrading from 2.4.0 to 2.4.3 breaks, among other things, the -o option to check_http.

Not sure what you can do about this, but it might be worth noting as a change in 2.4.4 so others who stumble across this don't start questioning their own sanity and skills.

**Comment by mhalden** [comment]
It looks to me like the 2.4.3 tarball may actually contain the contents from the 2.3.3 release.

**Comment by sawolf** [comment]
Hi, thanks for reaching out and sorry for causing that issue. That sounds extremely frustrating to deal with.

I've updated the [release tarball for release 2.4.3](https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.4.3/nagios-plugins-2.4.3.tar.gz) and confirmed that it and the 2.4.4 release have the correct code now. 

By "some package sources" I assume you mean EPEL - I will be leaving a similar note [here](https://bugzilla.redhat.com/show_bug.cgi?id=2190027) shortly.

**Comment by ltning** [comment]
It caused a bit of "what am I doing wrong here" :) Thanks for updating the tarball.

The source I meant was FreeBSD ports - we've patched the port in-house to 2.4.4 and have or will be submitting a patch to the port maintainer. Interestingly, all builds will fail now until the port itself is updated since the source tarball has changed sha256 checksum :-D
