### ISSUE TITLE
New plugin to perform SSL certificate checks

### ISSUE THREAD

**Issue by anordby** [nagios-plugins/nagios-plugins#72]
Hi,
I wrote a new SSL certificate checker plugin that I find more complete than what I could see elsewhere. It checks expiration, revokation, CRL list update status, and whether hostname is present in the certificate. Feel free to include it in contrib in nagios-plugins. It can be downloaded from:
https://github.com/anordby/plugins/blob/master/nagios/check_ssl_validity

Open to suggestions is anything needs to be improved before it can be included.

Usage:
```
# ./check_ssl_validity

check_ssl_validity -H &lt;cert hostname&gt; [-I &lt;IP/host&gt;] [-p &lt;port&gt;]
[-t &lt;timeout&gt;] [-w &lt;expire warning (days)&gt;] [-c &lt;expire critical (dats)&gt;]
[-C &lt;CRL update frequency (seconds)&gt;]
```
Will look for hostname provided with -H in the certificate, but will contact
server with host/IP provided by -I (optional)

**Comment by abrist** [comment]
Thank you for the potential contribution, though we do not have time to review this for the current 2.1.0 release cycle, we will try to consider it for a potential addition in the future.

**Comment by hedenface** [comment]
Looking at Issue #273 this looks like it would be helpful. I will either review the plugin and add it for inclusion or use it as a starting point to accomplish a few other things we're looking for. Thanks!

**Comment by sawolf** [comment]
@anordby - Thanks again for your contribution. I've merged your plugin (with some changes) into the `maint` branch (in plugins-scripts/check_ssl_validity.pl). I'm not the most experienced perl programmer, so if you wanted to review/suggest changes to anything I've done there, I'd appreciate it (though if not, no worries).

**Comment by anordby** [comment]
Hey that's cool @sawolf. If any user brings up any issues I will look at it. I'm using the plugin myself.
