### ISSUE TITLE
check_oracle.sh: tnsping counting OK causes errors

### ISSUE THREAD

**Issue by paulbruedgam** [nagios-plugins/nagios-plugins#722]
The check for OK causes an error if there is an OK in the connection string.
https://github.com/nagios-plugins/nagios-plugins/blob/b9d3e249e61e5c6a2c134a104fcb296208d5310e/plugins-scripts/check_oracle.sh#L140

Here is an example that causes the problem.
```bash
TNS Ping Utility for Linux: Version 19.0.0.0.0 - Production on 29-JUN-2023 15:35:34
Copyright (c) 1997, 2019, Oracle.  All rights reserved.
Used parameter files:
./sqlnet.ora

Used TNSNAMES adapter to resolve the alias
Attempting to contact (DESCRIPTION=(ENABLE=BROKEN)(ADDRESS_LIST=(FAILOVER=ON)(LOAD_BALANCE=OFF)(ADDRESS=(PROTOCOL=TCP)(HOST=host1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=host2)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=service)))
OK (0 msec)
```
The parameter ENABLE=BROKEN contains also an OK, so that tnschk2 will be set to 2.

I suggest to use an other check like

```bash
grep -Ec "^OK \([[:digit:]]+ msec\)"
```

**Comment by sawolf** [comment]
I missed that this should have been closed with #723 - thanks again for the patch!
