### ISSUE TITLE
nagios-plugins/plugins/check_dns.c

### ISSUE THREAD

**Issue by asepready** [nagios-plugins/nagios-plugins#725]
Not compile with make/gcc

**Comment by sawolf** [comment]
Hi @asepready, thanks for reaching out. The latest release of `nagios-plugins` does compile on my test systems, including `check_dns`. Can you tell me a bit about your build environment?

Specifically, I'd like to know 1) what distribution of linux/unix you're using, including version number (e.g. CentOS Stream 9), and 2) what the output is from `make all`

**Comment by asepready** [comment]
terima kasih @sawolf,
saya menggunakan distribusi linux yang digunakan adalah CentOS 7

**Comment by sawolf** [comment]
Okay, I see the issue now - there are no errors shown in the output of `make all`, but `check_dns` doesn't exist at the end of the process.

I was able to fix this by installing `nslookup` first:

```
yum install nslookup -y
./tools/setup
./configure
make all
make install
```

Afterwards, it looks like `check_dns` is properly compiled.

I'll update our documentation. Let me know if this works for you or if you run into further trouble. Thank you!
