### ISSUE TITLE
check_snmp issue on release-2.4.7: No valid data returned 

### ISSUE THREAD

**Issue by kurgans0** [nagios-plugins/nagios-plugins#743]
I just installed Nagios 4.5.0 with nagios-plugins 2.4.7.
I have an issue using check_snmp.

```
# My command:
./check_snmp -H 10.1.2.3  -C MyCommunity -o sysUpTime.0 -m RFC1213-MIB

# The return:
No valid data returned (20455651) 2 days, 8:49:16.51) 
```

My command worked fine with 2.4.5 (under Nagios 4.4.14).
I installed 2.4.6 under Nagios 4.5.0 > no issue.

**Comment by kristofejro** [comment]
I have the same issue with 2.4.7.
With previous version 2.4.6 it works fine.

**Comment by kurgans0** [comment]
I created my ticket on the same time of another person.
See issue #742

**Comment by sawolf** [comment]
Thanks for reporting this - we'll make sure this is handled properly for release 2.4.8.

**Comment by janreimen** [comment]
Idem on my side, upgraded from 2.3.3 to 2.4.8 and run in the same bug. Downgraded to 2.4.6 and OK

**Comment by tronyx** [comment]
Same issue with another MIB:

`root@d18804b49809:/opt/nagios/libexec# ./check_snmp -H 192.168.1.38 -o READYNASOS-MIB::volumeFreeSpace.1 -C public -P 2c -w 250000:100000 -c 99999:0
No valid data returned (12668901)`

**Comment by kevin-j-morse** [comment]
I am still seeing this issue with the large majority of my OID while running `Nagios 4.5.0` with `nagios-plugins 2.4.8`

In all cases, status goes `Unknown` while the Status Information saying `No valid data returned (#####)`

Downgrading to `2.4.6` solves the issue for me.

I am running `Rocky Linux 8.9` and I've done all the updates to SNMP related packages that I can find.

**Comment by sawolf** [comment]
I forgot to leave a note here yesterday - thanks for the follow-up! The developer who was assigned to this is figuring out whether they can robustly fix the original issue while keeping the plugin working for all of the cases that broke. If we're not able to get to a good solution quickly, we'll revert this change for the next bugfix release.

**Comment by nagiosgwesterman** [comment]
For those still getting the issue, if you're willing to share, what is the format of the return value for the OIDs that aren't working right? For example, `INTEGER: notForwarding(100)`, `Timeticks: (0)`, etc.

**Comment by kevin-j-morse** [comment]
@nagiosgwesterman I tested PR 749 by patching 2.4.8 and recompiling. It seems to have solved the problem.

All of the OID that weren't working were integers. They were from APC UPSs and Supermicro BMC.

My only comment is that it looks like a string you may have changed for testing is still part of the PR so I only made the changes from line 507 onwards.

**Comment by tronyx** [comment]
If you're not planning to release 2.4.9 anytime soon, is it possible for you to release a 2.4.8.1 to get this out to the masses?

**Comment by daavery** [comment]
check_snmp!-m IF-MIB -o ifSpeed.10102 -c @0:110000000 -v

command issued is :: /usr/bin/snmpget -Le -t 3 -r 5 -m IF-MIB -v 1 -c public 172.31.8.21:161 ifSpeed.10102

result is ::  IF-MIB::ifSpeed.10102 = Gauge32: 1000000000

output is :: No valid data returned (1000000000)

**Comment by nagiosgwesterman** [comment]
@daavery - On what version is this occurring? Have you tried the patch that is currently in `master`?

**Comment by nagiosgwesterman** [comment]
@tronyx - The release is not up to me, but I have sent a message up the chain on your behalf!

**Comment by nagiosgwesterman** [comment]
UPDATE: Plugins 2.4.9 has been released with this fix in it! (@tronyx and all)

**Comment by tronyx** [comment]
Thank you @nagiosgwesterman! Building a new Docker image now and will report back.

**Comment by tronyx** [comment]
Everything looks good to me! Thanks again!

**Comment by apollo13** [comment]
Can confirm that 2.4.9 fixes this.

**Comment by sawolf** [comment]
Thanks for the feedback, everyone! I'm going to close this issue. 

@daavery I'm assuming that you were reporting that you ran into the same issue on nagios-plugins 2.4.7 or 2.4.8 - if that's not true or if you're still seeing your issue on the latest release, please feel free to post a new issue.
