### ISSUE TITLE
check_snmp - warning and critical does not work for integer values of 0

### ISSUE THREAD

**Issue by box293** [nagios-plugins/nagios-plugins#75]
When the value returned is 0, the warning and critical arguments are ignored and the status is OK.

For these tests, the value of "1" is OK.

Here's when the returned value is 1:
```
check_snmp -H 10.25.4.1 -C public -o iso.3.6.1.4.1.4526.11.1.2.1.5.5.0 -w 1
SNMP OK - 1 | SNMPv2-SMI::enterprises.4526.11.1.2.1.5.5.0=1;1;; 

or

check_snmp -H 10.25.4.1 -C public -o iso.3.6.1.4.1.4526.11.1.2.1.5.5.0 -c 1
SNMP OK - 1 | SNMPv2-SMI::enterprises.4526.11.1.2.1.5.5.0=1;;1; 
```
It has a an OK state which is what I want.

Here's when the returned value is 2:
```
check_snmp -H 10.25.4.1 -C public -o iso.3.6.1.4.1.4526.11.1.2.1.5.4.0 -w 1
SNMP WARNING - *2* | SNMPv2-SMI::enterprises.4526.11.1.2.1.5.4.0=2;1;; 

or

check_snmp -H 10.25.4.1 -C public -o iso.3.6.1.4.1.4526.11.1.2.1.5.4.0 -c 1
SNMP CRITICAL - *2* | SNMPv2-SMI::enterprises.4526.11.1.2.1.5.4.0=2;;1; 
```
And it is returning the correct warning or critical state which is what I want.

Here's when the returned value is 0:
```
check_snmp -H 10.25.4.1 -C public -o iso.3.6.1.4.1.4526.11.1.2.1.6.2.0 -w 1
SNMP OK - 0 | SNMPv2-SMI::enterprises.4526.11.1.2.1.6.2.0=0;1;; 

or

check_snmp -H 10.25.4.1 -C public -o iso.3.6.1.4.1.4526.11.1.2.1.6.2.0 -c 1
SNMP OK - 0 | SNMPv2-SMI::enterprises.4526.11.1.2.1.6.2.0=0;;1; 
```
This time it's returning an OK status when it should be returning a warning or critical status.

**Comment by sreinhardt** [comment]
In agreement with the check_users bug, thresholds are greater-than checks unless otherwise denoted so 0 <= 1 should result in OK -w 1: should cause a warning as you were expecting.

**Comment by box293** [comment]
Yes I agree the threshold standards, I needed to relearn them lol.

Here's the correct usage as you've kindly demonstrated:
````
check_snmp -H 10.25.4.1 -C public -o iso.3.6.1.4.1.4526.11.1.2.1.6.2.0 -w 1:
SNMP WARNING - *0* | SNMPv2-SMI::enterprises.4526.11.1.2.1.6.2.0=0;1:;0;;
```
