### ISSUE TITLE
Inconsistent release archive url under GitHub release page

### ISSUE THREAD

**Issue by guessi** [nagios-plugins/nagios-plugins#751]
Similar with the issue for [NagiosEnterprises/nagioscore](https://github.com/NagiosEnterprises/nagioscore)
* https://github.com/NagiosEnterprises/nagioscore/issues/339
* https://github.com/NagiosEnterprises/nagioscore/issues/935
* https://github.com/NagiosEnterprises/nagioscore/issues/937

Not sure why v2.4.8 changed it's tag name? from `release-X.Y.Z` to `X.Y.Z`?
* https://github.com/nagios-plugins/nagios-plugins/tags

Which causing inconsistent release archive path

* https://github.com/nagios-plugins/nagios-plugins/releases/download/2.4.8/nagios-plugins-2.4.8.tar.gz # <---- path changed, due to the tag changed.
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.4.7/nagios-plugins-2.4.7.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.4.6/nagios-plugins-2.4.6.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.4.5/nagios-plugins-2.4.5.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.4.4/nagios-plugins-2.4.4.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.4.3/nagios-plugins-2.4.3.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.4.2/nagios-plugins-2.4.2.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.4.1/nagios-plugins-2.4.1.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.4.0/nagios-plugins-2.4.0.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.3.3/nagios-plugins-2.3.3.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.3.2/nagios-plugins-2.3.2.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.3.1/nagios-plugins-2.3.1.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.3.0/nagios-plugins-2.3.0.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.2.1/nagios-plugins-2.2.1.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.2.0/nagios-plugins-2.2.0.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.1.4/nagios-plugins-2.1.4.tar.gz
* https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.1.3/nagios-plugins-2.1.3.tar.gz

**Comment by sawolf** [comment]
Hi @guessi - thanks for the heads-up. I'll get this resolved today.
