### ISSUE TITLE
check_snmp issue on release-2.4.8: No valid data returned (28)

### ISSUE THREAD

**Issue by syrus1006** [nagios-plugins/nagios-plugins#752]
Hi! I had an old version of Nagios and its plugins installed, and everything worked fine with it. Now I have the latest version of Nagios (4.5.0) and plugins (2.4.8), and there are few issues. One of the main issue is that if I run a check_snmp command and add tresholds to it (-w and -c), I receive a message: no valid data returned (28). Without threshold it shows the correct data.
I there anything I can do on my side, or I need to roll back to an older version, because this is a bug?

**Comment by sawolf** [comment]
Hi @syrus1006, check the discussion on https://github.com/nagios-plugins/nagios-plugins/issues/743 - there's a patch for this that may go out in 2.4.9, and I'd be interested to know if that works for your setup.
