### ISSUE TITLE
check_http breaks with --nobody option in 2.1.0-beta-RC1

### ISSUE THREAD

**Issue by koenwtje** [nagios-plugins/nagios-plugins#77]
At line 720 of `check_http.c`, in `decode_chunked_page()` there is the following code:

```c
  if (*dst_pos) *dst_pos = '\0';
  else {
    die (STATE_UNKNOWN, _("HTTP UNKNOWN - Memory allocation error\n"));
  }
```

It fails when the --no-body option is used (probably because there is no page, and thus no pointer into the page if there is no body).

**Comment by abrist** [comment]
Fixed in 2.1.0-beta-RC1 with commit:  https://github.com/nagios-plugins/nagios-plugins/commit/5a6cf50ab58722d4ff752ca1c19f1a4cadb0cc87
