### ISSUE TITLE
wrong message "Socket timeout after n seconds"

### ISSUE THREAD

**Issue by fbretel** [nagios-plugins/nagios-plugins#80]
Hi, I find the message _Socket timeout after n seconds_ confusing: it leads to think that the _connection_ fails whereas it is the _request_ that is failing.
In other words the server fails to reply within a certain amount of time although the connection is actually established.
I suggest to:
1. change the message to _Request timeout after n seconds_
2. rename all mentions of `socket_` to `request_`
I can provide a patch.

**Comment by sreinhardt** [comment]
Can you provide a specific plugin example? If I recall correctly, there are mixed cases where socket is in fact correct and several others where your example would be correct.

**Comment by fbretel** [comment]
Sure — forgot to mention that: `check_http`
The problem I see is that [`check_http` uses `socket_timeout_alarm_handler`](/nagios-plugins/nagios-plugins/blob/master/plugins/check_http.c#L175) as a general timeout handler, without distinguishing between an actual socket or request timeout, which can be misleading for diagnosis.

**Comment by abrist** [comment]
You are correct.  Currently check_http does not distinguish between the two.

**Comment by jfrickson** [comment]
Both are "socket" timeouts, just at different stages. And we can't have separate timeouts for connect vs read vs write, especially since check_http can follow redirects.
