### ISSUE TITLE
check_http: year 2038 issue when checking ssl certificates

### ISSUE THREAD

**Issue by stefan-walluhn** [nagios-plugins/nagios-plugins#83]
We are getting CRITICAL warnings for all certs that are valid longer than 2038. It seems that check_http has some Y2K38 issues.

I assume this happens because of difftime() or some timegm() internals.
https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/sslutils.c#L211

**Comment by abrist** [comment]
This looks like an issue with time_t in time.h.  

$ grep difftime /usr/include/time.h
 extern double difftime (time_t __time1, time_t __time0)

See:
https://en.wikipedia.org/wiki/Year_2038_problem

I am not sure what the best route for resolution is as we have to make sure 32 bit systems are still supported through the change.

**Comment by jfrickson** [comment]
@stefan-walluhn Is this happening on a 32-bit system?

**Comment by stefan-walluhn** [comment]
Yes, it happened on a 32-bit VM those days.

**Comment by jfrickson** [comment]
I thought so. It is a problem with `time_t` as @abrist suggested. I did some research and it looks like to 2038 problem is not easily solvable on a 32-bit system. By your response, I assume you no longer have a 32-bit VM, and they are getting quite rare. All things considered, I'm going to close this issue. If I run across a reasonable fix, I'll put it in.
