### ISSUE TITLE
check_snmp does not work with IPv6

### ISSUE THREAD

**Issue by DrydenK** [nagios-plugins/nagios-plugins#84]
Hi,

I´ve tried to use the check_snmp plugins with IPv6, but it didn't work. A quick check into the code of a few of them revealed the issue quite quickly. They all use snmpwalk to make the actual communication. The problem is that to use IPv6, snmpwalk requires that the string "udp6:" must be added to the beginning of the hostname or IPv6 address. For example (in check_snmp_cpu):
...
for NUMERO in `$CMD_SNMPWALK -t 2 -r 2 -v 1 -c $COMMUNITY $HOSTNAME $OID_PROCESSID | $CMD_AWK '{ print $1 }' | $CMD_AWK -F "." '{print $NF}'`
do
....

For the IPv6 case would have to be something like
..
$HOSTNAME="udp6:${HOSTNAME}"
for NUMERO in `$CMD_SNMPWALK -t 2 -r 2 -v 1 -c $COMMUNITY $HOSTNAME $OID_PROCESSID | $CMD_AWK '{ print $1 }' | $CMD_AWK -F "." '{print $NF}'`
do
....

A quick checking logic on the format of the address could add this to the address if IPv6 is detected. 

Also, I've tried to install and test nagios_plugins 2.1.0RC1, but I'm unable to compile it, having the same issue reported in this tread:http://support.nagios.com/forum/viewtopic.php?f=35&t=30546. Namely, compilation stops after reporting "mv: cannot stat `t-fr.gmo': No such file or directory". Due to this, I'm unable to say if 2.1.0 does fix the problem or not.

Thank you,

Roberto Greiner

**Comment by abrist** [comment]
Well, check_snmp using snmpget, and the syntax is a bit different than expected:
From:  http://www.net-snmp.org/wiki/index.php/FAQ:Applications_28

"for IPv6 this causes a problem because IPv6 addresses also use a colon to separate addressing parts. Thus you need to enclose the address in square brackets ( [ and ] ). Because most shells use these brackets too, you also likely need to quote it:

    snmpget 'udp6:[::1]:161' sysUpTime.0

We probably need to add the -6 optarg (setting a Boolean) and then check for the Boolean from the optarg after the hostname optarg is set, and then finally alter the hostname to resemble the syntax above (escaping the quotes as necessary).

**Comment by tmcnag** [comment]
We can use something similar to the following from check_http.c to parse out the IPv6 portion:  https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_http.c#L381-L387

**Comment by tmcnag** [comment]
As for the "cannot stat" error you are receiving, that is referring to language files.  You are likely missing gettext-devel:

http://support.nagios.com/forum/viewtopic.php?f=35&t=30546&start=10#p129281

In our README:

https://github.com/nagios-plugins/nagios-plugins/blob/master/README

we mention the need for "m4, gettext, automake, and autoconf".

**Comment by DrydenK** [comment]
Hi, after installing gettext-devel, I've managed to compile and install the RC1 plugins.

A test did show that the new version behaves exactly like the old one. Putting the IPv6 address directly fails, prepending it with "udp6:" makes it work.

Just a curiosity: I've tried ./check_snmp -V, and it returns 
   check_snmp v2.0.3.121.g8077.dirty (nagios-plugins 2.0.3)
Is that expected? Shouldn´t it show 2.1RC1 or something like that?


thank you,

Roberto Greiner

**Comment by abrist** [comment]
I just pushed a new commit that should add ipv6 support to check_snmp.  
Commit:
https://github.com/nagios-plugins/nagios-plugins/commit/bf9aa4d647281425ba77b287ecf48501aeac9e7d
Branch:
https://github.com/nagios-plugins/nagios-plugins/tree/2.1.0-beta-RC1

Note:  We have not pushed any real beta tags as of yet, so you may get some dirty notes on the beta version.

**Comment by abrist** [comment]
No follow up from OP.  Tested fine on my side.
