### ISSUE TITLE
check_disk : mount does not exists

### ISSUE THREAD

**Issue by rpelissi** [nagios-plugins/nagios-plugins#86]
Hi,
I have a strange issue with check_disk v2.0.3 (nagios-plugins 2.0.3).
I have created a check using a ssh connection. This check looks for the mount /opt/data which looks like this:
/dev/sdb1             7.8T  4.3T  3.6T  54% /opt/data

mount
/dev/sdb1 on /opt/data type xfs (rw,inode64)

On the nagios server, running as the nagios user, the check return this the disk is ok:
check_by_ssh -H server -C "/usr/bin/sudo /home/nagios/libexec/check_disk -w 10% -c 5%  -u GB -p /opt/data " -l nagios -i /home/nagios/.ssh/nagios_id_dsa -E
DISK OK - free space: /opt/data 3671 GB (46% inode=99%);| /opt/data=4309GB;7182;7581;0;7981

But in the web interface of nagios, it says:
DISK CRITICAL - /opt/data does not exist 

Here is the service definition:
define service{
        host_name               server
        service_description     disk /opt/data
        check_command           check_by_ssh_t30!"/usr/bin/sudo /home/nagios/libexec/check_disk -w 10% -c 5%  -u GB -p /opt/data"!nagios!/home/nagios/.ssh/nagios_id_dsa!
        max_check_attempts      5
        normal_check_interval   5
        retry_check_interval    3
        check_period            24x7
        notification_interval   120
       notification_period     24x7
        notification_options    w,c,r
        contact_groups          test_grp
        }
I really can't find why the web interface says this...

Can you help?
Thanks

**Comment by scottwilkerson** [comment]
Can you show your command definition for check_command check_by_ssh_t30 so we can verify that it is running the same command you are running from the command line

**Comment by rpelissi** [comment]
Thanks!
Here it is:
define command{
        command_name    check_by_ssh_t30
        command_line    $USER1$/check_by_ssh -H $HOSTADDRESS$ -C $ARG1$ -l $ARG2$ -i $ARG3$ -t 30 -E
        }

Note that my nagios server is not the latest, it's 3.3.1.

**Comment by scottwilkerson** [comment]
looking at the commands they are close, but not exactly the same, but can you run the following which is what your command should expand to (assuming $USER1$ = /usr/local/nagios/libexec )

su nagios -c '/usr/local/nagios/libexec/check_by_ssh -H server -C "/usr/bin/sudo /home/nagios/libexec/check_disk -w 10% -c 5% -u GB -p /opt/data" -l nagios -i /home/nagios/.ssh/nagios_id_dsa -t 30 -E'

Also, I would try it without the -E

**Comment by rpelissi** [comment]
Hi,
Here are the results:

# sudo su -
# su nagios -c '/usr/local/nagios/libexec/check_by_ssh -H server -C
"/usr/bin/sudo /home/nagios/libexec/check_disk -w 10% -c 5% -u GB -p
/opt/data" -l nagios -i /home/nagios/.ssh/nagios_id_dsa -t 30'
DISK OK - free space: /opt/data 3671 GB (46% inode=99%);|
/opt/data=4309GB;7182;7581;0;7981
# su nagios -c '/usr/local/nagios/libexec/check_by_ssh -H server-C
"/usr/bin/sudo /home/nagios/libexec/check_disk -w 10% -c 5% -u GB -p
/opt/data" -l nagios -i /home/nagios/.ssh/nagios_id_dsa -t 30 -E'
DISK OK - free space: /opt/data 3671 GB (46% inode=99%);|
/opt/data=4309GB;7182;7581;0;7981

So it's seems to work.
Romain.


2015-05-20 15:41 GMT-04:00 Scott Wilkerson <notifications@github.com>:

**Comment by rpelissi** [comment]
Hi,
I have also upgrade Nagios core to the lastest stable and still have the
same issue.
Romain

2015-05-20 15:41 GMT-04:00 Scott Wilkerson <notifications@github.com>:

**Comment by rpelissi** [comment]
Oh God... I feel soooooo stupid now that I have the cause of my issue :)
In fact, the root cause of the issue is because I have not defined my host
properly..

In my host.cfg file, I had this:

#server
define host{
        host_name                       server
        check_command                   check_ssh_host
        alias                           server test
        address                         server
        contact_groups                  test_grp
        use                             genhost
        }

The probleme is that the host_name is only the display name and NOT the
real hostname of the server/system you are trying to momitor.
In my case, in the address section with the value "server" refer in the
hosts file (/etc/hosts)
 to a system that was not the system I am trying to monitor, so, some check
could not work at all because they do not exist in the server set in the
"address" section, or, they failed because the value does not exist (like a
mount in my case).
So, be sure that the "address" setting point to the right hostname or the
right IP :)


Thanks!
Romain

2015-05-20 15:41 GMT-04:00 Scott Wilkerson <notifications@github.com>:

**Comment by sreinhardt** [comment]
Glad you got it all figured out. I'll close this up.
