### ISSUE TITLE
check_disk v1.5

### ISSUE THREAD

**Issue by iakonk** [nagios-plugins/nagios-plugins#88]
Hello,
We are using check_disk v1.5 (nagios-plugins 1.5),
Our disk geometry:
  /dev/md127 on /EBS type ext3 (rw,noatime,nodiratime,_netdev)
  /EBS on /opt type none (rw,bind)

check executes with options:
  ./check_disk --warning=10% --critical=5% --iwarning=10% --icritical=5% --all --include-type=ext3 --include-type=ext4 --include-type=xfs -X tmpfs
and check ignores mount point /EBS because of "include-type" file system option.

We could use check with options:
  ./check_disk --warning=10% --critical=5% --iwarning=10% --icritical=5% --all --ignore-ereg-path=/run -X tmpfs -u GB
But it than could report errors like:
   /home/user/.gvs - Permission denied

We believe it is not correct to skip check of mount point that is mounted as bind.
Is it possible to fix that behavior ? 

We already checked log changes for plugin of newer version.
Thank you in advance!

**Comment by abrist** [comment]
You most likely are experiencing permission issues.  Does the latter check work if you run it as root?

**Comment by Rocco83** [comment]
Hi,

I have hitted the bug as well, and i have other workarounds.

It is not about permission problem, meaning that i am running that from root.
I have a just installed debian jessie with X and xfce. unfortunately something bringed in gnome thing as well (on another box i do not have this issue).

See also:
http://unix.stackexchange.com/questions/77453/why-cannot-find-read-run-user-1000-gvfs-even-though-it-is-running-as-root

Here the log:

root@kes:~#  /usr/lib/nagios/plugins/check_disk -w 20% -c 10% 
DISK CRITICAL - /run/user/1000/gvfs is not accessible: Permission denied
root@kes:~# 

See that this is from root.

root@kes:~# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,relatime)
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=187398,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,relatime,size=310288k,mode=755)
/dev/xvda1 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=22,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
mqueue on /dev/mqueue type mqueue (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/xvdb1 on /boot type ext4 (rw,relatime,data=ordered)
/dev/xvda5 on /var type ext4 (rw,relatime,data=ordered)
tmpfs on /run/user/120 type tmpfs (rw,nosuid,nodev,relatime,size=155144k,mode=700,uid=120,gid=129)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=155144k,mode=700,uid=1000,gid=513)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=513)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=155144k,mode=700)
root@kes:~# 

You can see that:
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=155144k,mode=700,uid=1000,gid=513)
And this is something we can reach, but then:
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=513)

Also adding -l (from the help:  -l, --local    Only check local filesystems) will not help
root@kes:~# /usr/lib/nagios/plugins/check_disk -w 20% -c 10% -l
DISK CRITICAL - /run/user/1000/gvfs is not accessible: Permission denied
root@kes:~# 

The difference between the 2 box:

Server with "gvfs-fuse" installed (dependacies of gnome and gnome-core in debian)
root@kes:~# dpkg -l gvfs-fuse
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  gvfs-fuse      1.22.2-1     amd64        userspace virtual filesystem - fu
root@kes:~# mount |grep gvfs
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=513)
root@kes:~# ls -la /run/user/1000/gvfs    
ls: cannot access /run/user/1000/gvfs: Permission denied
root@kes:~# 
Server without it
root@orions:~# dpkg -l gvfs-fuse
dpkg-query: no packages found matching gvfs-fuse
root@orions:~# mount|grep gvfs
root@orions:~# ls -la /run/user/1000/gvfs    
total 0
drwx------ 2 daniele ldapusers  40 Dec 31 13:08 .
drwx------ 9 daniele ldapusers 180 Jan  7 21:25 ..
root@orions:~# 

So, adding exclusion for fuse.gvfsd-fuse will help
root@kes:~#  /usr/lib/nagios/plugins/check_disk -w 20% -c 10%  -X fuse.gvfsd-fuse
DISK WARNING - free space: / 575 MB (12% inode=49%); /dev 10 MB (100% inode=99%); /run 298 MB (98% inode=99%); /dev/shm 757 MB (99% inode=99%); /run/lock 5 MB (100% inode=99%); /sys/fs/cgroup 757 MB (100% inode=99%); /boot 51 MB (60% inode=98%); /var 3242 MB (69% inode=96%); /run/user/120 151 MB (99% inode=99%); /run/user/1000 151 MB (99% inode=99%); /run/user/0 151 MB (100% inode=99%);| /=4063MB;3928;4419;0;4911 /dev=0MB;8;9;0;10 /run=4MB;242;272;0;303 /dev/shm=0MB;605;681;0;757 /run/lock=0MB;4;4;0;5 /sys/fs/cgroup=0MB;605;681;0;757 /boot=33MB;72;81;0;91 /var=1396MB;3928;4419;0;4911 /run/user/120=0MB;120;135;0;151 /run/user/1000=0MB;120;135;0;151 /run/user/0=0MB;120;135;0;151
root@kes:~# 

This is less general than in the first approach, but will work as well.

My conclusion, even this is "not so common" to have "items" with graphic things monitored, this is a bug, and "-l" flag (or something else) should exclude all pseudo filesystem (maybe there is a better flag, but i have not found it)

My 2 cents,
Daniele

**Comment by jfrickson** [comment]
The program was set up to always exclude an fs type of "iso9660". I added an exclude for fs type "fuse.gvfsd-fuse". Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/a4d7343fc9879fb2679f4c461b839747e4b04f4a
