### ISSUE TITLE
check_http: add the -j CONNECT option to support SSL sites through a proxy.

### ISSUE THREAD

**Issue by ssaxnagios** [nagios-plugins/nagios-plugins#90]
```
./check_http -I 192.168.4.124 -p 3128 -u "https://www.google.com/" -S
CRITICAL - Cannot make SSL connection.
140625270634344:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:769:
```

Looks like we need the -j CONNECT option to support monitoring SSL sites through a proxy.

See here for more information (he has made code modifications to an older version):

http://nagios.fm4dd.com/howto/monitor-ssl-websites-through-proxy.htm

**Comment by abrist** [comment]
Alright, I created a patch from the modified 1.4.14 version from the fm4dd site.  

Commit is here:
https://github.com/nagios-plugins/nagios-plugins/commit/96778dc5cd0f0c91febfbd1b17457697bc883a06

On the check_http_ssl_proxy branch:
https://github.com/nagios-plugins/nagios-plugins/commits/check_http_ssl_proxy

I would prefer to leave this open for additional testing and code cleanup for the time being.

**Comment by abrist** [comment]
Crap, looks like there is also a very old branch with some CONNECT changes:
https://github.com/nagios-plugins/nagios-plugins/commits/hw/http-connect

Commit:
https://github.com/nagios-plugins/nagios-plugins/commit/6b28ae739b1ca9f20519f7522b52d055ce3a0902

We will need to evaluate both of these methods and alter one of them to fit with the current state of the plugin.  Much has changed to check_http recently, so there is definitely some work to be done here.

**Comment by jfrickson** [comment]
This was fixed in Aug 2015 via commit https://github.com/nagios-plugins/nagios-plugins/commit/2fcd56a2f47b81b0fbeaf836a988babf916ee583
