### ISSUE TITLE
check_procs Segfaulting in 2.1.0

### ISSUE THREAD

**Issue by abrist** [nagios-plugins/nagios-plugins#93]
From: https://nagios-plugins.org/nagios-plugins-2-1-0-released/#comment-106649

We’re getting a segmentation fault with check_procs in this release.

The gdb trace unfortunately doesn’t look too helpful:
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-64.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law. Type “show copying”
and “show warranty” for details.
This GDB was configured as “x86_64-redhat-linux-gnu”.
For bug reporting instructions, please see:
…
Reading symbols from /opt/inworks64/nagios/libexec/check_procs…Reading symbols from /usr/lib/debug/opt/inworks64/nagios/libexec/check_procs.debug…done.
done.
(gdb) run
Starting program: /opt/inworks64/nagios/libexec/check_procs
[Thread debugging using libthread_db enabled]
Using host libthread_db library “/lib64/libthread_db.so.1″.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff767a58c in __GI___libc_free (mem=0x6172a6) at malloc.c:2919
2919 ar_ptr = arena_for_chunk(p);
(gdb) quit

**Comment by abrist** [comment]
It is faulting at line 200 :
result = cmd_run( PS_COMMAND, &chld_out, &chld_err, 0);

**Comment by abrist** [comment]
Commenting out free() on line 370 in lib/utils_cmd.c seems to act as a shim:
                if (cmd && strlen (cmd) == strspn (cmd, " \t\r\n")) {
                        //free(cmd);
                        cmd = NULL;
                }

**Comment by tmcnag** [comment]
This feels like a bit like a double-free, doesn't it?

**Comment by abrist** [comment]
Indeed the whole while block:
        while (cmd) {
                str = cmd;
                str += strspn (str, " \t\r\n"); /* trim any leading whitespace */

                if (strstr (str, "'") == str) { /* handle SIMPLE quoted strings */
                        str++;
                        if (!strstr (str, "'")) { /* balanced? */
                                free(cmd);
                                free(argv);
                                return -1;
                        }
                        cmd = 1 + strstr (str, "'");
                        str[strcspn (str, "'")] = 0;
                }
                else {
                        if (strpbrk (str, " \t\r\n")) {
                                cmd = 1 + strpbrk (str, " \t\r\n");
                                str[strcspn (str, " \t\r\n")] = 0;
                        }
                        else {
                                free(cmd);
                                cmd = NULL;
                        }
                }

                if (cmd && strlen (cmd) == strspn (cmd, " \t\r\n")) {
                        //free(cmd);
                        cmd = NULL;
                }

                argv[i++] = str;
        }

        rst = cmd_run_array (argv, out, err, flags);
        free(cmd);
        free(argv);
        return rst;

**Comment by abrist** [comment]
Blame is here:
https://github.com/nagios-plugins/nagios-plugins/commit/14e76a2a1b378e0853811b7d4a4761ccf9e16c00
Spenser!  :P

**Comment by jfrickson** [comment]
Working on a fix...

**Comment by jfrickson** [comment]
Fix is in commit: https://github.com/nagios-plugins/nagios-plugins/commit/bee00616cb055436ec9ec6c9f02f4a81eee1d8a0

we'll be releasing 2.1.1 shortly with the fix.

**Comment by abrist** [comment]
reverted:
https://github.com/nagios-plugins/nagios-plugins/commit/09654f6b7afc3941e4b495643502cf3887df9fa5
And:
https://github.com/nagios-plugins/nagios-plugins/commit/4c97453cd65234d0f8c699600d189576ee38b79e
Build from master.

**Comment by jfrickson** [comment]
@abrist Finally getting back to this. Do you remember the reason for reverting?

**Comment by jfrickson** [comment]
Ok, both the problem commit and my fix commit were reverted. So this is not a problem any longer.
