### ISSUE TITLE
check_nagios - could not locate a running nagios process

### ISSUE THREAD

**Issue by box293** [nagios-plugins/nagios-plugins#94]
Originally reported here on Debian 7.8:
https://support.nagios.com/forum/viewtopic.php?f=35&t=34331

I've confirmed the same behaviour on CentOS 6.5.

With check_nagios it gives the error that it could not located a nagios process.

Nagios Plugins v 2.1.1
```
Command:
./check_nagios -t 20 -e 5 -F /usr/local/nagios/var/status.dat -C /usr/local/nagios/bin/nagios

Output:
NAGIOS CRITICAL: Could not locate a running Nagios process!
```

Nagios Plugins v 2.0.3
```
Command:
./check_nagios -t 20 -e 5 -F /usr/local/nagios/var/status.dat -C /usr/local/nagios/bin/nagios

Output:
NAGIOS OK: 6 processes, status log updated 3 seconds ago
```

Also, I tired using the -v flag to produce verbose troubleshooting output but it did not show anything, it wasn't until I tried -vv that I go info. This is the same in 2.0.3 and 2.0.1. This verbosity level feels broken in my opinion.
```
Command with -v
./check_nagios -t 20 -e 5 -F /usr/local/nagios/var/status.dat -C /usr/local/nagios/bin/nagios -v

Output:
NAGIOS CRITICAL: Could not locate a running Nagios process!

Command with -vv
./check_nagios -t 20 -e 5 -F /usr/local/nagios/var/status.dat -C /usr/local/nagios/bin/nagios -vv

Output:
command: /bin/ps axwo 'stat uid pid ppid vsz rss pcpu cgroup:256 comm args'
NAGIOS CRITICAL: Could not locate a running Nagios process!
```

After getting the verbose output I compared the commands used in both versions:

v2.0.3:
```
command: /bin/ps axwo 'stat uid pid ppid vsz rss pcpu comm args'
```
v2.1.1
```
command: /bin/ps axwo 'stat uid pid ppid vsz rss pcpu cgroup:256 comm args'
```

They seem slightly different, I'm sure this is the key to the problem.

**Comment by mnietz** [comment]
I'm having exactly the same issue after upgrading from 2.0.3 to 2.1.1.

Debian 7.8 & Nagios Core 4.1.1

**Comment by zen2** [comment]
Same problem on Gentoo with net-analyzer/nagios-plugins-2.1.1-r1 and net-analyzer/nagios-core-4.1.1

**Comment by CrystalPalace** [comment]
Same problem Ubuntu 14.04 / Nagios 4.1.1 / Nagios Plugin 2.1.1

**Comment by PaulLebmann** [comment]
Same problem on Debian 8.0, Nagios 4.1.1 and Nagios Plugins 2.1.1

I don't know c, but it looks like the variable (or constant or whatever) PS_COMMAND which defines the command that is run, is also used by check_procs.
Maybe there the cgroup is needed - it is at least mentioned in the code - and that broke check_nagios?

**Comment by PierrePezot** [comment]
I wrote my own version of the check using libprocps. It's more stable and safer in my opinion. Works well with Ubuntu 14.04 and Nagios 4.1.1
https://github.com/PierrePezot/nagios-plugins

**Comment by waja** [comment]
You may have noticed that the origin plugin also checks the status logfile to check, if the process is ALSO working and not just a zombie.

**Comment by PierrePezot** [comment]
I should add this indeed. But thinking about this, isn't checking the Nagios process a bit pointless? If Nagios isn't runnning, the check won't be performed. Shouldn't we just check the status logfile?

**Comment by waja** [comment]
check_nagios can also be used by a remote check, not just by a local monitoring daemon.

**Comment by PierrePezot** [comment]
I added the zombie check in my code. I will work on cleaning the code and using nagios-plugins libs in order to make a proper pull request.

**Comment by morozen** [comment]
@PierrePezot do you have any updated on that?

**Comment by baamf** [comment]
Okay, just realized this is a known problem...  Having the same issue on Redhat 7.2 with nagios 4.1.1

**Comment by simoneriggi** [comment]
Hi, 
it seems I have the same problem with check_nagios plugin: 

./check_nagios -t 20 -e 5 -C /opt/nagios/bin/nagios -F /var/nagios/nagios.log -v
NAGIOS CRITICAL: Could not locate a running Nagios process!

Nagios v4.1.1
Plugins 2.1.1
Ubuntu 14.04

Do you know if it has been fixed? 
Thanks

**Comment by morozen** [comment]
@simoneriggi 

my understanding is that you will need to tune ./configure options and adopt them for your version of 'ps' program (check_nagios relies on ps output)

for example:

```
./configure \
    --with-ps-cols=2 \
    --with-ps-format="%s %d %d %d %d %d %f %s %s %n" \
    --with-ps-varlist="procstat,&procuid,&procpid,&procppid,&procvsz,&procrss,&procpcpu,procetime,procprog,&pos" \
    --with-ps-command="/bin/ps axwo 'stat uid pid ppid vsz rss pcpu etime comm args'" 

```

**Comment by simoneriggi** [comment]
@morozen 
Many thanks, I will follow your suggestion.

**Comment by yuwtennis** [comment]
I think @morozen is correct.

Looks like check_nagios does not properly process the lines from default ps
command.

[root@dev libexec]# ./check_nagios -vvv  -F
/usr/local/nagios/var/status.dat -C nagios
command: /bin/ps axwo 'stat uid pid ppid vsz rss pcpu cgroup:256 comm args'
NAGIOS CRITICAL: Could not locate a running Nagios process!

Default command is /bin/ps axwo 'stat uid pid ppid vsz rss pcpu cgroup:256
comm args'. However, when executed nagios process is there.

[root@dev libexec]# /bin/ps axwo 'stat uid pid ppid vsz rss pcpu cgroup:256
comm args' | grep /usr/local/nagios/bin/nagios | head -1
Ss     502 13050     1  24832  3860  0.0
blkio:/;net_cls:/;freezer:/;devices:/;memory:/;cpuacct:/;cpu:/;cpuset:/

                                                               nagios
                                             /usr/local/nagios/bin/nagios
-d /usr/local/nagios/etc/nagios.cfg

In the code, check_nagios.c, ps lines should be parsed by sscanf.

                cols = sscanf (chld_out.line[i], PS_FORMAT, PS_VARLIST);

All 10 fields should be parsed eventually not. Only first 7 fields are
processed.
This ends up with not comparing the ps result with -C argument.

PS_FORMAT is  "%s %d %d %d %d %d %f %s %s %n"
and
PS_VARLIST is
 procstat,&procuid,&procpid,&procppid,&procvsz,&procrss,&procpcpu,proc_cgroup_hierarchy,procprog,&pos

"procprog" is the value which is compared with the -C argument.

      if (!strstr(procargs, argv[0]) && strstr(procargs, process_string) &&
strcmp(procargs,"")) {


Is this a bug ? Or code is correct and you need to adjust by the compile
option?

On Wed, Apr 6, 2016 at 5:15 PM, simoneriggi <notifications@github.com>
wrote:

> @morozen <https://github.com/morozen>
> Many thanks, I will follow your suggestion.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nagios-plugins/nagios-plugins/issues/94#issuecomment-206210140>
>



-- 
Yu Watanabe
渡辺 裕

LinkedIn : jp.linkedin.com/in/yuwatanabe1

**Comment by robotto7831a** [comment]
On Debian and Oracle Linux the compiler option works perfect.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/cd0d850963848e68d6872f70ece94ef9c0f618ad
