### ISSUE TITLE
check_mailq line 38 not terminated

### ISSUE THREAD

**Issue by jrdalrymple** [nagios-plugins/nagios-plugins#95]
Barf:

`use utils qw(%ERRORS &print_revision &support &usage );`
`my ($sudo)`
`sub print_help ();`

**Comment by tmcnag** [comment]
For clarity, line 38 in the script needs a semi-colon.  Reported here:

https://support.nagios.com/forum/viewtopic.php?f=35&t=34330&p=149763#p149677

**Comment by jfrickson** [comment]
Fixed previously in monitoring_plugins
