### ISSUE TITLE
Extend check_http to support TLSv1.1 and TLSv1.2

### ISSUE THREAD

**Issue by jasonwilk** [nagios-plugins/nagios-plugins#97]
Please add TLS v1.2 to check_http. Currently only v1 is supported.

 -S, --ssl=VERSION
    Connect via SSL. Port defaults to 443. VERSION is optional, and prevents
    auto-negotiation (1 = TLSv1, 2 = SSLv2, 3 = SSLv3).
  
Some QSAs are starting to vail PCI scans when TLSv1 is enabled. They've already disallowed SSLv2 and SSLv3. That means that there are no checks that would be available via SSL with this command unless it's extended to support TLSv1.1 and TLSv1.2. This needs to be updated for this plugin to be useful in any environment that has PCI implications.

**Comment by jfrickson** [comment]
Fixed by commit https://github.com/nagios-plugins/nagios-plugins/commit/8e03ae73402956e3f6f247fbac98bcf5c0bd6e3a in maint branch https://github.com/nagios-plugins/nagios-plugins/tree/maint
