### ISSUE TITLE
check_http: Failed to parse chunked body, too large for destination

### ISSUE THREAD

**Issue by IdahoPL** [nagios-plugins/nagios-plugins#98]
After transition to 2.1.1 from 2.0.3 I'm having problem with one service check - http_check of 'http://delivery.way2traffic.com/campaign=3782/view/24041/count.gif?tcookie=set&pc=219273&W2TDEBUG=1' should return 1x1 px gif image. I'm checking it with:

/usr/local/libexec/nagios/check_http -H delivery.way2traffic.com -u '/campaign=3782/view/24041/count.gif?tcookie=set&pc=219273&W2TDEBUG=1' -s 'GIF89a'

On 2.0.3 it worked fine, on 2.1.1 I'm getting:

$ /usr/local/libexec/nagios/check_http -H delivery.way2traffic.com -u '/campaign=3782/view/24041/count.gif?tcookie=set&pc=219273&W2TDEBUG=1' -s 'GIF89a'
HTTP UNKNOWN - Failed to parse chunked body, too large for destination

**Comment by shane-axiom** [comment]
I'm seeing this too. Perhaps [decode_chunked_page](https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_http.c#L688) is broken?

**Comment by jfrickson** [comment]
I've put a fix in the 'maint' branch that should fix the problems with chunked encoding. (commit https://github.com/nagios-plugins/nagios-plugins/commit/f6fc07e72d72ae389fc55bb129959febbacbc476) Please try it out with as many chunked-encoded URLs as you can, including text and non-text, and report back if it's working properly.

**Comment by jfrickson** [comment]
No response, so I'm assuming my fix worked. Closing.
